// THIS FILE IS GENERATED BY tools/codegen. Do not edit by hand.
// Re-generate with `just codegen` (or `just kotlin`).

package dev.bridgething.gateway

import dev.bridgething.schema.*
import kotlinx.coroutines.async
import kotlinx.coroutines.awaitAll
import kotlinx.coroutines.coroutineScope
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.filter
import kotlinx.coroutines.flow.filterIsInstance
import kotlinx.coroutines.flow.mapNotNull
import java.util.UUID
import kotlin.time.Duration
import kotlin.time.Duration.Companion.seconds

/** Outcome of a typed gateway request. */
public sealed class RequestResult<out R, out E> {
  public data class Ok<R>(val response: R): RequestResult<R, Nothing>()
  public data class DomainErr<E>(val error: E): RequestResult<Nothing, E>()
  public data class ProtocolErr(val error: GatewayError): RequestResult<Nothing, Nothing>()
}

/** Cross-peer methods for the `System` wire surface. */
public class SystemSurface(private val gateway: BridgethingGateway) {
  /** Cross-peer stream of `System::OtaProgress` messages. */
  public val otaProgress: Flow<Pair<String, OtaProgress>> = gateway.events
    .filterIsInstance<GatewayEvent.Message>()
    .mapNotNull {
      val outer = it.message.data as? BridgeToGatewayMsgData.System ?: return@mapNotNull null
      val inner = outer.data as? BridgeToGatewaySystemMsg.OtaProgress ?: return@mapNotNull null
      it.deviceId to inner.data
    }

  /** Cross-peer stream of `System::OtaError` messages. */
  public val otaError: Flow<Pair<String, OtaError>> = gateway.events
    .filterIsInstance<GatewayEvent.Message>()
    .mapNotNull {
      val outer = it.message.data as? BridgeToGatewayMsgData.System ?: return@mapNotNull null
      val inner = outer.data as? BridgeToGatewaySystemMsg.OtaError ?: return@mapNotNull null
      it.deviceId to inner.data
    }

  /** Cross-peer stream of `System::OtaBeginAck` messages. */
  public val otaBeginAck: Flow<Pair<String, OtaBeginAck>> = gateway.events
    .filterIsInstance<GatewayEvent.Message>()
    .mapNotNull {
      val outer = it.message.data as? BridgeToGatewayMsgData.System ?: return@mapNotNull null
      val inner = outer.data as? BridgeToGatewaySystemMsg.OtaBeginAck ?: return@mapNotNull null
      it.deviceId to inner.data
    }

  /** Cross-peer stream of `System::OtaBeginRejected` messages. */
  public val otaBeginRejected: Flow<Pair<String, OtaBeginRejected>> = gateway.events
    .filterIsInstance<GatewayEvent.Message>()
    .mapNotNull {
      val outer = it.message.data as? BridgeToGatewayMsgData.System ?: return@mapNotNull null
      val inner = outer.data as? BridgeToGatewaySystemMsg.OtaBeginRejected ?: return@mapNotNull null
      it.deviceId to inner.data
    }

  /** Send `System::OtaChunk` to every connected peer (broadcast). */
  public suspend fun otaChunk(payload: OtaChunk, priority: Priority = Priority.Normal) {
    val ids = gateway.connectedDeviceIds()
    coroutineScope {
      ids.map { deviceId ->
        async {
          val msg = GatewayToBridgeMsg(
            id = UUID.randomUUID().toBytes(),
            meta = GatewayMsgMeta.Event,
            data = GatewayToBridgeMsgData.System(GatewayToBridgeSystemMsg.OtaChunk(payload)),
          )
          gateway.send(deviceId, msg, priority)
        }
      }.awaitAll()
    }
  }

  /** Send `System::OtaAbandon` to every connected peer (broadcast). */
  public suspend fun otaAbandon(payload: OtaAbandon, priority: Priority = Priority.Normal) {
    val ids = gateway.connectedDeviceIds()
    coroutineScope {
      ids.map { deviceId ->
        async {
          val msg = GatewayToBridgeMsg(
            id = UUID.randomUUID().toBytes(),
            meta = GatewayMsgMeta.Command,
            data = GatewayToBridgeMsgData.System(GatewayToBridgeSystemMsg.OtaAbandon(payload)),
          )
          gateway.send(deviceId, msg, priority)
        }
      }.awaitAll()
    }
  }

  /** Send `System::CancelUpdate` to every connected peer (broadcast). */
  public suspend fun cancelUpdate(priority: Priority = Priority.Normal) {
    val ids = gateway.connectedDeviceIds()
    coroutineScope {
      ids.map { deviceId ->
        async {
          val msg = GatewayToBridgeMsg(
            id = UUID.randomUUID().toBytes(),
            meta = GatewayMsgMeta.Command,
            data = GatewayToBridgeMsgData.System(GatewayToBridgeSystemMsg.CancelUpdate),
          )
          gateway.send(deviceId, msg, priority)
        }
      }.awaitAll()
    }
  }

  /** Typed request to a specific peer: companion sends, daemon responds. */
  public suspend fun otaBegin(deviceId: String, req: OtaBegin, timeout: Duration = 30.seconds): RequestResult<OtaBeginAck, OtaBeginRejected> {
    val outboundData = GatewayToBridgeMsgData.System(GatewayToBridgeSystemMsg.OtaBegin(req))
    val response = gateway.request(deviceId, outboundData, timeout)
    return when (val d = response.data) {
      is BridgeToGatewayMsgData.System -> when (val inner = d.data) {
        is BridgeToGatewaySystemMsg.OtaBeginAck -> RequestResult.Ok(inner.data)
        is BridgeToGatewaySystemMsg.OtaBeginRejected -> RequestResult.DomainErr(inner.data)
        else -> RequestResult.ProtocolErr(GatewayError.Unsupported)
      }
      is BridgeToGatewayMsgData.Error -> RequestResult.ProtocolErr(d.data)
      else -> RequestResult.ProtocolErr(GatewayError.Unsupported)
    }
  }

}

/** Cross-peer methods for the `Transport` wire surface. */
public class TransportSurface(private val gateway: BridgethingGateway) {
  /** Cross-peer stream of `Transport::Play` messages. */
  public val play: Flow<String> = gateway.events
    .filterIsInstance<GatewayEvent.Message>()
    .mapNotNull {
      val outer = it.message.data as? BridgeToGatewayMsgData.Transport ?: return@mapNotNull null
      if (outer.data !is BridgeToGatewayTransportMsg.Play) return@mapNotNull null
      it.deviceId
    }

  /** Cross-peer stream of `Transport::Pause` messages. */
  public val pause: Flow<String> = gateway.events
    .filterIsInstance<GatewayEvent.Message>()
    .mapNotNull {
      val outer = it.message.data as? BridgeToGatewayMsgData.Transport ?: return@mapNotNull null
      if (outer.data !is BridgeToGatewayTransportMsg.Pause) return@mapNotNull null
      it.deviceId
    }

  /** Cross-peer stream of `Transport::PlayPause` messages. */
  public val playPause: Flow<String> = gateway.events
    .filterIsInstance<GatewayEvent.Message>()
    .mapNotNull {
      val outer = it.message.data as? BridgeToGatewayMsgData.Transport ?: return@mapNotNull null
      if (outer.data !is BridgeToGatewayTransportMsg.PlayPause) return@mapNotNull null
      it.deviceId
    }

  /** Cross-peer stream of `Transport::Next` messages. */
  public val next: Flow<String> = gateway.events
    .filterIsInstance<GatewayEvent.Message>()
    .mapNotNull {
      val outer = it.message.data as? BridgeToGatewayMsgData.Transport ?: return@mapNotNull null
      if (outer.data !is BridgeToGatewayTransportMsg.Next) return@mapNotNull null
      it.deviceId
    }

  /** Cross-peer stream of `Transport::Prev` messages. */
  public val prev: Flow<String> = gateway.events
    .filterIsInstance<GatewayEvent.Message>()
    .mapNotNull {
      val outer = it.message.data as? BridgeToGatewayMsgData.Transport ?: return@mapNotNull null
      if (outer.data !is BridgeToGatewayTransportMsg.Prev) return@mapNotNull null
      it.deviceId
    }

  /** Cross-peer stream of `Transport::VolumeUp` messages. */
  public val volumeUp: Flow<String> = gateway.events
    .filterIsInstance<GatewayEvent.Message>()
    .mapNotNull {
      val outer = it.message.data as? BridgeToGatewayMsgData.Transport ?: return@mapNotNull null
      if (outer.data !is BridgeToGatewayTransportMsg.VolumeUp) return@mapNotNull null
      it.deviceId
    }

  /** Cross-peer stream of `Transport::VolumeDown` messages. */
  public val volumeDown: Flow<String> = gateway.events
    .filterIsInstance<GatewayEvent.Message>()
    .mapNotNull {
      val outer = it.message.data as? BridgeToGatewayMsgData.Transport ?: return@mapNotNull null
      if (outer.data !is BridgeToGatewayTransportMsg.VolumeDown) return@mapNotNull null
      it.deviceId
    }

  /** Cross-peer stream of `Transport::MuteToggle` messages. */
  public val muteToggle: Flow<String> = gateway.events
    .filterIsInstance<GatewayEvent.Message>()
    .mapNotNull {
      val outer = it.message.data as? BridgeToGatewayMsgData.Transport ?: return@mapNotNull null
      if (outer.data !is BridgeToGatewayTransportMsg.MuteToggle) return@mapNotNull null
      it.deviceId
    }

  /** Cross-peer stream of `Transport::Shuffle` messages. */
  public val shuffle: Flow<Pair<String, ShuffleSet>> = gateway.events
    .filterIsInstance<GatewayEvent.Message>()
    .mapNotNull {
      val outer = it.message.data as? BridgeToGatewayMsgData.Transport ?: return@mapNotNull null
      val inner = outer.data as? BridgeToGatewayTransportMsg.Shuffle ?: return@mapNotNull null
      it.deviceId to inner.data
    }

  /** Cross-peer stream of `Transport::Repeat` messages. */
  public val repeat: Flow<Pair<String, RepeatSet>> = gateway.events
    .filterIsInstance<GatewayEvent.Message>()
    .mapNotNull {
      val outer = it.message.data as? BridgeToGatewayMsgData.Transport ?: return@mapNotNull null
      val inner = outer.data as? BridgeToGatewayTransportMsg.Repeat ?: return@mapNotNull null
      it.deviceId to inner.data
    }

  /** Cross-peer stream of `Transport::SeekTo` messages. */
  public val seekTo: Flow<Pair<String, SeekToSet>> = gateway.events
    .filterIsInstance<GatewayEvent.Message>()
    .mapNotNull {
      val outer = it.message.data as? BridgeToGatewayMsgData.Transport ?: return@mapNotNull null
      val inner = outer.data as? BridgeToGatewayTransportMsg.SeekTo ?: return@mapNotNull null
      it.deviceId to inner.data
    }

  /** Cross-peer stream of `Transport::SkipToIndex` messages. */
  public val skipToIndex: Flow<Pair<String, SkipToIndexSet>> = gateway.events
    .filterIsInstance<GatewayEvent.Message>()
    .mapNotNull {
      val outer = it.message.data as? BridgeToGatewayMsgData.Transport ?: return@mapNotNull null
      val inner = outer.data as? BridgeToGatewayTransportMsg.SkipToIndex ?: return@mapNotNull null
      it.deviceId to inner.data
    }

}

/** Cross-peer methods for the `Forward` wire surface. */
public class ForwardSurface(private val gateway: BridgethingGateway) {
  /** Cross-peer stream of `Forward::Text` messages. */
  public val text: Flow<Pair<String, String>> = gateway.events
    .filterIsInstance<GatewayEvent.Message>()
    .mapNotNull {
      val outer = it.message.data as? BridgeToGatewayMsgData.Forward ?: return@mapNotNull null
      val inner = outer.data as? ForwardMessage.Text ?: return@mapNotNull null
      it.deviceId to inner.data
    }

  /** Cross-peer stream of `Forward::Json` messages. */
  public val json: Flow<Pair<String, Value>> = gateway.events
    .filterIsInstance<GatewayEvent.Message>()
    .mapNotNull {
      val outer = it.message.data as? BridgeToGatewayMsgData.Forward ?: return@mapNotNull null
      val inner = outer.data as? ForwardMessage.Json ?: return@mapNotNull null
      it.deviceId to inner.data
    }

  /** Cross-peer stream of `Forward::Binary` messages. */
  public val binary: Flow<Pair<String, ByteArray>> = gateway.events
    .filterIsInstance<GatewayEvent.Message>()
    .mapNotNull {
      val outer = it.message.data as? BridgeToGatewayMsgData.Forward ?: return@mapNotNull null
      val inner = outer.data as? ForwardMessage.Binary ?: return@mapNotNull null
      it.deviceId to inner.data
    }

}

/** Cross-peer methods for the `Version` wire surface. */
public class VersionSurface(private val gateway: BridgethingGateway) {
  /** Send a `Version` event to every connected peer (broadcast). */
  public suspend fun send(payload: GatewayMeta, priority: Priority = Priority.Normal) {
    val ids = gateway.connectedDeviceIds()
    coroutineScope {
      ids.map { deviceId ->
        async {
          val msg = GatewayToBridgeMsg(
            id = UUID.randomUUID().toBytes(),
            meta = GatewayMsgMeta.Event,
            data = GatewayToBridgeMsgData.Version(payload),
          )
          gateway.send(deviceId, msg, priority)
        }
      }.awaitAll()
    }
  }

}

/** Cross-peer methods for the `Asset` wire surface. */
public class AssetSurface(private val gateway: BridgethingGateway) {
  /** Send `Asset::Push` to every connected peer (broadcast). */
  public suspend fun push(payload: AssetPush, priority: Priority = Priority.Normal) {
    val ids = gateway.connectedDeviceIds()
    coroutineScope {
      ids.map { deviceId ->
        async {
          val msg = GatewayToBridgeMsg(
            id = UUID.randomUUID().toBytes(),
            meta = GatewayMsgMeta.Event,
            data = GatewayToBridgeMsgData.Asset(GatewayToBridgeAssetMsg.Push(payload)),
          )
          gateway.send(deviceId, msg, priority)
        }
      }.awaitAll()
    }
  }

  /** Send `Asset::Clear` to every connected peer (broadcast). */
  public suspend fun clear(payload: AssetClear, priority: Priority = Priority.Normal) {
    val ids = gateway.connectedDeviceIds()
    coroutineScope {
      ids.map { deviceId ->
        async {
          val msg = GatewayToBridgeMsg(
            id = UUID.randomUUID().toBytes(),
            meta = GatewayMsgMeta.Event,
            data = GatewayToBridgeMsgData.Asset(GatewayToBridgeAssetMsg.Clear(payload)),
          )
          gateway.send(deviceId, msg, priority)
        }
      }.awaitAll()
    }
  }

  /** Send `Asset::PushChunk` to every connected peer (broadcast). */
  public suspend fun pushChunk(payload: AssetPushChunk, priority: Priority = Priority.Normal) {
    val ids = gateway.connectedDeviceIds()
    coroutineScope {
      ids.map { deviceId ->
        async {
          val msg = GatewayToBridgeMsg(
            id = UUID.randomUUID().toBytes(),
            meta = GatewayMsgMeta.Event,
            data = GatewayToBridgeMsgData.Asset(GatewayToBridgeAssetMsg.PushChunk(payload)),
          )
          gateway.send(deviceId, msg, priority)
        }
      }.awaitAll()
    }
  }

  /** Send `Asset::PushAbandon` to every connected peer (broadcast). */
  public suspend fun pushAbandon(payload: AssetPushAbandon, priority: Priority = Priority.Normal) {
    val ids = gateway.connectedDeviceIds()
    coroutineScope {
      ids.map { deviceId ->
        async {
          val msg = GatewayToBridgeMsg(
            id = UUID.randomUUID().toBytes(),
            meta = GatewayMsgMeta.Command,
            data = GatewayToBridgeMsgData.Asset(GatewayToBridgeAssetMsg.PushAbandon(payload)),
          )
          gateway.send(deviceId, msg, priority)
        }
      }.awaitAll()
    }
  }

  /** Typed request to a specific peer: companion sends, daemon responds. */
  public suspend fun pushBegin(deviceId: String, req: AssetPushBegin, timeout: Duration = 30.seconds): RequestResult<AssetPushBeginAck, AssetPushBeginRejected> {
    val outboundData = GatewayToBridgeMsgData.Asset(GatewayToBridgeAssetMsg.PushBegin(req))
    val response = gateway.request(deviceId, outboundData, timeout)
    return when (val d = response.data) {
      is BridgeToGatewayMsgData.Asset -> when (val inner = d.data) {
        is BridgeToGatewayAssetMsg.PushBeginAck -> RequestResult.Ok(inner.data)
        is BridgeToGatewayAssetMsg.PushBeginRejected -> RequestResult.DomainErr(inner.data)
        else -> RequestResult.ProtocolErr(GatewayError.Unsupported)
      }
      is BridgeToGatewayMsgData.Error -> RequestResult.ProtocolErr(d.data)
      else -> RequestResult.ProtocolErr(GatewayError.Unsupported)
    }
  }

  /** Stream of typed inbound `AssetRequest` requests. */
  public val requests: Flow<Pair<AssetRequestHandle, AssetRequest>> = gateway.events
    .filterIsInstance<GatewayEvent.Message>()
    .filter { it.message.meta is GatewayMsgMeta.Request }
    .mapNotNull {
      val outer = it.message.data as? BridgeToGatewayMsgData.Asset ?: return@mapNotNull null
      val inner = outer.data as? BridgeToGatewayAssetMsg.Request ?: return@mapNotNull null
      val handle = AssetRequestHandle(gateway, it.deviceId, it.message.id)
      handle to inner.data
    }

}

/** Cross-peer methods for the `Authority` wire surface. */
public class AuthoritySurface(private val gateway: BridgethingGateway) {
  /** Send `Authority::Claim` to every connected peer (broadcast). */
  public suspend fun claim(payload: AuthorityClaim, priority: Priority = Priority.Normal) {
    val ids = gateway.connectedDeviceIds()
    coroutineScope {
      ids.map { deviceId ->
        async {
          val msg = GatewayToBridgeMsg(
            id = UUID.randomUUID().toBytes(),
            meta = GatewayMsgMeta.Event,
            data = GatewayToBridgeMsgData.Authority(GatewayToBridgeAuthorityMsg.Claim(payload)),
          )
          gateway.send(deviceId, msg, priority)
        }
      }.awaitAll()
    }
  }

  /** Send `Authority::Release` to every connected peer (broadcast). */
  public suspend fun release(payload: AuthorityRelease, priority: Priority = Priority.Normal) {
    val ids = gateway.connectedDeviceIds()
    coroutineScope {
      ids.map { deviceId ->
        async {
          val msg = GatewayToBridgeMsg(
            id = UUID.randomUUID().toBytes(),
            meta = GatewayMsgMeta.Event,
            data = GatewayToBridgeMsgData.Authority(GatewayToBridgeAuthorityMsg.Release(payload)),
          )
          gateway.send(deviceId, msg, priority)
        }
      }.awaitAll()
    }
  }

}

/** Cross-peer methods for the `Chrome` wire surface. */
public class ChromeSurface(private val gateway: BridgethingGateway) {
  /** Send `Chrome::Navigate` to every connected peer (broadcast). */
  public suspend fun navigate(payload: ChromeNavigate, priority: Priority = Priority.Normal) {
    val ids = gateway.connectedDeviceIds()
    coroutineScope {
      ids.map { deviceId ->
        async {
          val msg = GatewayToBridgeMsg(
            id = UUID.randomUUID().toBytes(),
            meta = GatewayMsgMeta.Command,
            data = GatewayToBridgeMsgData.Chrome(GatewayToBridgeChromeMsg.Navigate(payload)),
          )
          gateway.send(deviceId, msg, priority)
        }
      }.awaitAll()
    }
  }

}

/** Cross-peer methods for the `NowPlayingUpdate` wire surface. */
public class NowPlayingUpdateSurface(private val gateway: BridgethingGateway) {
  /** Send a `NowPlayingUpdate` event to every connected peer (broadcast). */
  public suspend fun send(payload: NowPlayingUpdate, priority: Priority = Priority.Normal) {
    val ids = gateway.connectedDeviceIds()
    coroutineScope {
      ids.map { deviceId ->
        async {
          val msg = GatewayToBridgeMsg(
            id = UUID.randomUUID().toBytes(),
            meta = GatewayMsgMeta.Event,
            data = GatewayToBridgeMsgData.NowPlayingUpdate(payload),
          )
          gateway.send(deviceId, msg, priority)
        }
      }.awaitAll()
    }
  }

}

/** Cross-peer methods for the `Webapp` wire surface. */
public class WebappSurface(private val gateway: BridgethingGateway) {
  /** Typed request to a specific peer: companion sends, daemon responds. */
  public suspend fun list(deviceId: String, timeout: Duration = 30.seconds): RequestResult<WebappList, Nothing> {
    val outboundData = GatewayToBridgeMsgData.Webapp(GatewayToBridgeWebappMsg.List)
    val response = gateway.request(deviceId, outboundData, timeout)
    return when (val d = response.data) {
      is BridgeToGatewayMsgData.Webapp -> when (val inner = d.data) {
        is BridgeToGatewayWebappMsg.Webapps -> RequestResult.Ok(inner.data)
        else -> RequestResult.ProtocolErr(GatewayError.Unsupported)
      }
      is BridgeToGatewayMsgData.Error -> RequestResult.ProtocolErr(d.data)
      else -> RequestResult.ProtocolErr(GatewayError.Unsupported)
    }
  }

  /** Typed request to a specific peer: companion sends, daemon responds. */
  public suspend fun getActive(deviceId: String, timeout: Duration = 30.seconds): RequestResult<WebappActive, Nothing> {
    val outboundData = GatewayToBridgeMsgData.Webapp(GatewayToBridgeWebappMsg.GetActive)
    val response = gateway.request(deviceId, outboundData, timeout)
    return when (val d = response.data) {
      is BridgeToGatewayMsgData.Webapp -> when (val inner = d.data) {
        is BridgeToGatewayWebappMsg.Active -> RequestResult.Ok(inner.data)
        else -> RequestResult.ProtocolErr(GatewayError.Unsupported)
      }
      is BridgeToGatewayMsgData.Error -> RequestResult.ProtocolErr(d.data)
      else -> RequestResult.ProtocolErr(GatewayError.Unsupported)
    }
  }

  /** Typed request to a specific peer: companion sends, daemon responds. */
  public suspend fun switchTo(deviceId: String, req: WebappSwitchTo, timeout: Duration = 30.seconds): RequestResult<WebappActive, WebappError> {
    val outboundData = GatewayToBridgeMsgData.Webapp(GatewayToBridgeWebappMsg.SwitchTo(req))
    val response = gateway.request(deviceId, outboundData, timeout)
    return when (val d = response.data) {
      is BridgeToGatewayMsgData.Webapp -> when (val inner = d.data) {
        is BridgeToGatewayWebappMsg.Switched -> RequestResult.Ok(inner.data)
        is BridgeToGatewayWebappMsg.WebappError -> RequestResult.DomainErr(inner.data)
        else -> RequestResult.ProtocolErr(GatewayError.Unsupported)
      }
      is BridgeToGatewayMsgData.Error -> RequestResult.ProtocolErr(d.data)
      else -> RequestResult.ProtocolErr(GatewayError.Unsupported)
    }
  }

  /** Typed request to a specific peer: companion sends, daemon responds. */
  public suspend fun install(deviceId: String, req: WebappInstall, timeout: Duration = 30.seconds): RequestResult<WebappInfo, WebappError> {
    val outboundData = GatewayToBridgeMsgData.Webapp(GatewayToBridgeWebappMsg.Install(req))
    val response = gateway.request(deviceId, outboundData, timeout)
    return when (val d = response.data) {
      is BridgeToGatewayMsgData.Webapp -> when (val inner = d.data) {
        is BridgeToGatewayWebappMsg.Installed -> RequestResult.Ok(inner.data)
        is BridgeToGatewayWebappMsg.WebappError -> RequestResult.DomainErr(inner.data)
        else -> RequestResult.ProtocolErr(GatewayError.Unsupported)
      }
      is BridgeToGatewayMsgData.Error -> RequestResult.ProtocolErr(d.data)
      else -> RequestResult.ProtocolErr(GatewayError.Unsupported)
    }
  }

  /** Typed request to a specific peer: companion sends, daemon responds. */
  public suspend fun uninstall(deviceId: String, req: WebappUninstall, timeout: Duration = 30.seconds): RequestResult<WebappActive, WebappError> {
    val outboundData = GatewayToBridgeMsgData.Webapp(GatewayToBridgeWebappMsg.Uninstall(req))
    val response = gateway.request(deviceId, outboundData, timeout)
    return when (val d = response.data) {
      is BridgeToGatewayMsgData.Webapp -> when (val inner = d.data) {
        is BridgeToGatewayWebappMsg.Uninstalled -> RequestResult.Ok(inner.data)
        is BridgeToGatewayWebappMsg.WebappError -> RequestResult.DomainErr(inner.data)
        else -> RequestResult.ProtocolErr(GatewayError.Unsupported)
      }
      is BridgeToGatewayMsgData.Error -> RequestResult.ProtocolErr(d.data)
      else -> RequestResult.ProtocolErr(GatewayError.Unsupported)
    }
  }

}

/** Per-peer methods for the `System` wire surface (deviceId is baked in). */
public class SystemSurfaceForDevice(
  private val gateway: BridgethingGateway,
  public val deviceId: String,
) {
  /** Stream of `System::OtaProgress` from this peer. */
  public val otaProgress: Flow<OtaProgress> = gateway.events
    .filterIsInstance<GatewayEvent.Message>()
    .filter { it.deviceId == deviceId }
    .mapNotNull {
      val outer = it.message.data as? BridgeToGatewayMsgData.System ?: return@mapNotNull null
      val inner = outer.data as? BridgeToGatewaySystemMsg.OtaProgress ?: return@mapNotNull null
      inner.data
    }

  /** Stream of `System::OtaError` from this peer. */
  public val otaError: Flow<OtaError> = gateway.events
    .filterIsInstance<GatewayEvent.Message>()
    .filter { it.deviceId == deviceId }
    .mapNotNull {
      val outer = it.message.data as? BridgeToGatewayMsgData.System ?: return@mapNotNull null
      val inner = outer.data as? BridgeToGatewaySystemMsg.OtaError ?: return@mapNotNull null
      inner.data
    }

  /** Stream of `System::OtaBeginAck` from this peer. */
  public val otaBeginAck: Flow<OtaBeginAck> = gateway.events
    .filterIsInstance<GatewayEvent.Message>()
    .filter { it.deviceId == deviceId }
    .mapNotNull {
      val outer = it.message.data as? BridgeToGatewayMsgData.System ?: return@mapNotNull null
      val inner = outer.data as? BridgeToGatewaySystemMsg.OtaBeginAck ?: return@mapNotNull null
      inner.data
    }

  /** Stream of `System::OtaBeginRejected` from this peer. */
  public val otaBeginRejected: Flow<OtaBeginRejected> = gateway.events
    .filterIsInstance<GatewayEvent.Message>()
    .filter { it.deviceId == deviceId }
    .mapNotNull {
      val outer = it.message.data as? BridgeToGatewayMsgData.System ?: return@mapNotNull null
      val inner = outer.data as? BridgeToGatewaySystemMsg.OtaBeginRejected ?: return@mapNotNull null
      inner.data
    }

  /** Send `System::OtaChunk` to this peer. */
  public suspend fun otaChunk(payload: OtaChunk, priority: Priority = Priority.Normal) {
    val msg = GatewayToBridgeMsg(
      id = UUID.randomUUID().toBytes(),
      meta = GatewayMsgMeta.Event,
      data = GatewayToBridgeMsgData.System(GatewayToBridgeSystemMsg.OtaChunk(payload)),
    )
    gateway.send(deviceId, msg, priority)
  }

  /** Send `System::OtaAbandon` to this peer. */
  public suspend fun otaAbandon(payload: OtaAbandon, priority: Priority = Priority.Normal) {
    val msg = GatewayToBridgeMsg(
      id = UUID.randomUUID().toBytes(),
      meta = GatewayMsgMeta.Command,
      data = GatewayToBridgeMsgData.System(GatewayToBridgeSystemMsg.OtaAbandon(payload)),
    )
    gateway.send(deviceId, msg, priority)
  }

  /** Send `System::CancelUpdate` to this peer. */
  public suspend fun cancelUpdate(priority: Priority = Priority.Normal) {
    val msg = GatewayToBridgeMsg(
      id = UUID.randomUUID().toBytes(),
      meta = GatewayMsgMeta.Command,
      data = GatewayToBridgeMsgData.System(GatewayToBridgeSystemMsg.CancelUpdate),
    )
    gateway.send(deviceId, msg, priority)
  }

  /** Typed request to this peer: companion sends, daemon responds. */
  public suspend fun otaBegin(req: OtaBegin, timeout: Duration = 30.seconds): RequestResult<OtaBeginAck, OtaBeginRejected> {
    val outboundData = GatewayToBridgeMsgData.System(GatewayToBridgeSystemMsg.OtaBegin(req))
    val response = gateway.request(deviceId, outboundData, timeout)
    return when (val d = response.data) {
      is BridgeToGatewayMsgData.System -> when (val inner = d.data) {
        is BridgeToGatewaySystemMsg.OtaBeginAck -> RequestResult.Ok(inner.data)
        is BridgeToGatewaySystemMsg.OtaBeginRejected -> RequestResult.DomainErr(inner.data)
        else -> RequestResult.ProtocolErr(GatewayError.Unsupported)
      }
      is BridgeToGatewayMsgData.Error -> RequestResult.ProtocolErr(d.data)
      else -> RequestResult.ProtocolErr(GatewayError.Unsupported)
    }
  }

}

/** Per-peer methods for the `Transport` wire surface (deviceId is baked in). */
public class TransportSurfaceForDevice(
  private val gateway: BridgethingGateway,
  public val deviceId: String,
) {
  /** Stream of `Transport::Play` from this peer. */
  public val play: Flow<Unit> = gateway.events
    .filterIsInstance<GatewayEvent.Message>()
    .filter { it.deviceId == deviceId }
    .mapNotNull {
      val outer = it.message.data as? BridgeToGatewayMsgData.Transport ?: return@mapNotNull null
      if (outer.data !is BridgeToGatewayTransportMsg.Play) return@mapNotNull null
      Unit
    }

  /** Stream of `Transport::Pause` from this peer. */
  public val pause: Flow<Unit> = gateway.events
    .filterIsInstance<GatewayEvent.Message>()
    .filter { it.deviceId == deviceId }
    .mapNotNull {
      val outer = it.message.data as? BridgeToGatewayMsgData.Transport ?: return@mapNotNull null
      if (outer.data !is BridgeToGatewayTransportMsg.Pause) return@mapNotNull null
      Unit
    }

  /** Stream of `Transport::PlayPause` from this peer. */
  public val playPause: Flow<Unit> = gateway.events
    .filterIsInstance<GatewayEvent.Message>()
    .filter { it.deviceId == deviceId }
    .mapNotNull {
      val outer = it.message.data as? BridgeToGatewayMsgData.Transport ?: return@mapNotNull null
      if (outer.data !is BridgeToGatewayTransportMsg.PlayPause) return@mapNotNull null
      Unit
    }

  /** Stream of `Transport::Next` from this peer. */
  public val next: Flow<Unit> = gateway.events
    .filterIsInstance<GatewayEvent.Message>()
    .filter { it.deviceId == deviceId }
    .mapNotNull {
      val outer = it.message.data as? BridgeToGatewayMsgData.Transport ?: return@mapNotNull null
      if (outer.data !is BridgeToGatewayTransportMsg.Next) return@mapNotNull null
      Unit
    }

  /** Stream of `Transport::Prev` from this peer. */
  public val prev: Flow<Unit> = gateway.events
    .filterIsInstance<GatewayEvent.Message>()
    .filter { it.deviceId == deviceId }
    .mapNotNull {
      val outer = it.message.data as? BridgeToGatewayMsgData.Transport ?: return@mapNotNull null
      if (outer.data !is BridgeToGatewayTransportMsg.Prev) return@mapNotNull null
      Unit
    }

  /** Stream of `Transport::VolumeUp` from this peer. */
  public val volumeUp: Flow<Unit> = gateway.events
    .filterIsInstance<GatewayEvent.Message>()
    .filter { it.deviceId == deviceId }
    .mapNotNull {
      val outer = it.message.data as? BridgeToGatewayMsgData.Transport ?: return@mapNotNull null
      if (outer.data !is BridgeToGatewayTransportMsg.VolumeUp) return@mapNotNull null
      Unit
    }

  /** Stream of `Transport::VolumeDown` from this peer. */
  public val volumeDown: Flow<Unit> = gateway.events
    .filterIsInstance<GatewayEvent.Message>()
    .filter { it.deviceId == deviceId }
    .mapNotNull {
      val outer = it.message.data as? BridgeToGatewayMsgData.Transport ?: return@mapNotNull null
      if (outer.data !is BridgeToGatewayTransportMsg.VolumeDown) return@mapNotNull null
      Unit
    }

  /** Stream of `Transport::MuteToggle` from this peer. */
  public val muteToggle: Flow<Unit> = gateway.events
    .filterIsInstance<GatewayEvent.Message>()
    .filter { it.deviceId == deviceId }
    .mapNotNull {
      val outer = it.message.data as? BridgeToGatewayMsgData.Transport ?: return@mapNotNull null
      if (outer.data !is BridgeToGatewayTransportMsg.MuteToggle) return@mapNotNull null
      Unit
    }

  /** Stream of `Transport::Shuffle` from this peer. */
  public val shuffle: Flow<ShuffleSet> = gateway.events
    .filterIsInstance<GatewayEvent.Message>()
    .filter { it.deviceId == deviceId }
    .mapNotNull {
      val outer = it.message.data as? BridgeToGatewayMsgData.Transport ?: return@mapNotNull null
      val inner = outer.data as? BridgeToGatewayTransportMsg.Shuffle ?: return@mapNotNull null
      inner.data
    }

  /** Stream of `Transport::Repeat` from this peer. */
  public val repeat: Flow<RepeatSet> = gateway.events
    .filterIsInstance<GatewayEvent.Message>()
    .filter { it.deviceId == deviceId }
    .mapNotNull {
      val outer = it.message.data as? BridgeToGatewayMsgData.Transport ?: return@mapNotNull null
      val inner = outer.data as? BridgeToGatewayTransportMsg.Repeat ?: return@mapNotNull null
      inner.data
    }

  /** Stream of `Transport::SeekTo` from this peer. */
  public val seekTo: Flow<SeekToSet> = gateway.events
    .filterIsInstance<GatewayEvent.Message>()
    .filter { it.deviceId == deviceId }
    .mapNotNull {
      val outer = it.message.data as? BridgeToGatewayMsgData.Transport ?: return@mapNotNull null
      val inner = outer.data as? BridgeToGatewayTransportMsg.SeekTo ?: return@mapNotNull null
      inner.data
    }

  /** Stream of `Transport::SkipToIndex` from this peer. */
  public val skipToIndex: Flow<SkipToIndexSet> = gateway.events
    .filterIsInstance<GatewayEvent.Message>()
    .filter { it.deviceId == deviceId }
    .mapNotNull {
      val outer = it.message.data as? BridgeToGatewayMsgData.Transport ?: return@mapNotNull null
      val inner = outer.data as? BridgeToGatewayTransportMsg.SkipToIndex ?: return@mapNotNull null
      inner.data
    }

}

/** Per-peer methods for the `Forward` wire surface (deviceId is baked in). */
public class ForwardSurfaceForDevice(
  private val gateway: BridgethingGateway,
  public val deviceId: String,
) {
  /** Stream of `Forward::Text` from this peer. */
  public val text: Flow<String> = gateway.events
    .filterIsInstance<GatewayEvent.Message>()
    .filter { it.deviceId == deviceId }
    .mapNotNull {
      val outer = it.message.data as? BridgeToGatewayMsgData.Forward ?: return@mapNotNull null
      val inner = outer.data as? ForwardMessage.Text ?: return@mapNotNull null
      inner.data
    }

  /** Stream of `Forward::Json` from this peer. */
  public val json: Flow<Value> = gateway.events
    .filterIsInstance<GatewayEvent.Message>()
    .filter { it.deviceId == deviceId }
    .mapNotNull {
      val outer = it.message.data as? BridgeToGatewayMsgData.Forward ?: return@mapNotNull null
      val inner = outer.data as? ForwardMessage.Json ?: return@mapNotNull null
      inner.data
    }

  /** Stream of `Forward::Binary` from this peer. */
  public val binary: Flow<ByteArray> = gateway.events
    .filterIsInstance<GatewayEvent.Message>()
    .filter { it.deviceId == deviceId }
    .mapNotNull {
      val outer = it.message.data as? BridgeToGatewayMsgData.Forward ?: return@mapNotNull null
      val inner = outer.data as? ForwardMessage.Binary ?: return@mapNotNull null
      inner.data
    }

}

/** Per-peer methods for the `Version` wire surface (deviceId is baked in). */
public class VersionSurfaceForDevice(
  private val gateway: BridgethingGateway,
  public val deviceId: String,
) {
  /** Send a `Version` event to this peer. */
  public suspend fun send(payload: GatewayMeta, priority: Priority = Priority.Normal) {
    val msg = GatewayToBridgeMsg(
      id = UUID.randomUUID().toBytes(),
      meta = GatewayMsgMeta.Event,
      data = GatewayToBridgeMsgData.Version(payload),
    )
    gateway.send(deviceId, msg, priority)
  }

}

/** Per-peer methods for the `Asset` wire surface (deviceId is baked in). */
public class AssetSurfaceForDevice(
  private val gateway: BridgethingGateway,
  public val deviceId: String,
) {
  /** Send `Asset::Push` to this peer. */
  public suspend fun push(payload: AssetPush, priority: Priority = Priority.Normal) {
    val msg = GatewayToBridgeMsg(
      id = UUID.randomUUID().toBytes(),
      meta = GatewayMsgMeta.Event,
      data = GatewayToBridgeMsgData.Asset(GatewayToBridgeAssetMsg.Push(payload)),
    )
    gateway.send(deviceId, msg, priority)
  }

  /** Send `Asset::Clear` to this peer. */
  public suspend fun clear(payload: AssetClear, priority: Priority = Priority.Normal) {
    val msg = GatewayToBridgeMsg(
      id = UUID.randomUUID().toBytes(),
      meta = GatewayMsgMeta.Event,
      data = GatewayToBridgeMsgData.Asset(GatewayToBridgeAssetMsg.Clear(payload)),
    )
    gateway.send(deviceId, msg, priority)
  }

  /** Send `Asset::PushChunk` to this peer. */
  public suspend fun pushChunk(payload: AssetPushChunk, priority: Priority = Priority.Normal) {
    val msg = GatewayToBridgeMsg(
      id = UUID.randomUUID().toBytes(),
      meta = GatewayMsgMeta.Event,
      data = GatewayToBridgeMsgData.Asset(GatewayToBridgeAssetMsg.PushChunk(payload)),
    )
    gateway.send(deviceId, msg, priority)
  }

  /** Send `Asset::PushAbandon` to this peer. */
  public suspend fun pushAbandon(payload: AssetPushAbandon, priority: Priority = Priority.Normal) {
    val msg = GatewayToBridgeMsg(
      id = UUID.randomUUID().toBytes(),
      meta = GatewayMsgMeta.Command,
      data = GatewayToBridgeMsgData.Asset(GatewayToBridgeAssetMsg.PushAbandon(payload)),
    )
    gateway.send(deviceId, msg, priority)
  }

  /** Typed request to this peer: companion sends, daemon responds. */
  public suspend fun pushBegin(req: AssetPushBegin, timeout: Duration = 30.seconds): RequestResult<AssetPushBeginAck, AssetPushBeginRejected> {
    val outboundData = GatewayToBridgeMsgData.Asset(GatewayToBridgeAssetMsg.PushBegin(req))
    val response = gateway.request(deviceId, outboundData, timeout)
    return when (val d = response.data) {
      is BridgeToGatewayMsgData.Asset -> when (val inner = d.data) {
        is BridgeToGatewayAssetMsg.PushBeginAck -> RequestResult.Ok(inner.data)
        is BridgeToGatewayAssetMsg.PushBeginRejected -> RequestResult.DomainErr(inner.data)
        else -> RequestResult.ProtocolErr(GatewayError.Unsupported)
      }
      is BridgeToGatewayMsgData.Error -> RequestResult.ProtocolErr(d.data)
      else -> RequestResult.ProtocolErr(GatewayError.Unsupported)
    }
  }

  /** Stream of typed inbound `AssetRequest` requests. */
  public val requests: Flow<Pair<AssetRequestHandle, AssetRequest>> = gateway.events
    .filterIsInstance<GatewayEvent.Message>()
    .filter { it.message.meta is GatewayMsgMeta.Request }
    .filter { it.deviceId == deviceId }
    .mapNotNull {
      val outer = it.message.data as? BridgeToGatewayMsgData.Asset ?: return@mapNotNull null
      val inner = outer.data as? BridgeToGatewayAssetMsg.Request ?: return@mapNotNull null
      val handle = AssetRequestHandle(gateway, it.deviceId, it.message.id)
      handle to inner.data
    }

}

/** Per-peer methods for the `Authority` wire surface (deviceId is baked in). */
public class AuthoritySurfaceForDevice(
  private val gateway: BridgethingGateway,
  public val deviceId: String,
) {
  /** Send `Authority::Claim` to this peer. */
  public suspend fun claim(payload: AuthorityClaim, priority: Priority = Priority.Normal) {
    val msg = GatewayToBridgeMsg(
      id = UUID.randomUUID().toBytes(),
      meta = GatewayMsgMeta.Event,
      data = GatewayToBridgeMsgData.Authority(GatewayToBridgeAuthorityMsg.Claim(payload)),
    )
    gateway.send(deviceId, msg, priority)
  }

  /** Send `Authority::Release` to this peer. */
  public suspend fun release(payload: AuthorityRelease, priority: Priority = Priority.Normal) {
    val msg = GatewayToBridgeMsg(
      id = UUID.randomUUID().toBytes(),
      meta = GatewayMsgMeta.Event,
      data = GatewayToBridgeMsgData.Authority(GatewayToBridgeAuthorityMsg.Release(payload)),
    )
    gateway.send(deviceId, msg, priority)
  }

}

/** Per-peer methods for the `Chrome` wire surface (deviceId is baked in). */
public class ChromeSurfaceForDevice(
  private val gateway: BridgethingGateway,
  public val deviceId: String,
) {
  /** Send `Chrome::Navigate` to this peer. */
  public suspend fun navigate(payload: ChromeNavigate, priority: Priority = Priority.Normal) {
    val msg = GatewayToBridgeMsg(
      id = UUID.randomUUID().toBytes(),
      meta = GatewayMsgMeta.Command,
      data = GatewayToBridgeMsgData.Chrome(GatewayToBridgeChromeMsg.Navigate(payload)),
    )
    gateway.send(deviceId, msg, priority)
  }

}

/** Per-peer methods for the `NowPlayingUpdate` wire surface (deviceId is baked in). */
public class NowPlayingUpdateSurfaceForDevice(
  private val gateway: BridgethingGateway,
  public val deviceId: String,
) {
  /** Send a `NowPlayingUpdate` event to this peer. */
  public suspend fun send(payload: NowPlayingUpdate, priority: Priority = Priority.Normal) {
    val msg = GatewayToBridgeMsg(
      id = UUID.randomUUID().toBytes(),
      meta = GatewayMsgMeta.Event,
      data = GatewayToBridgeMsgData.NowPlayingUpdate(payload),
    )
    gateway.send(deviceId, msg, priority)
  }

}

/** Per-peer methods for the `Webapp` wire surface (deviceId is baked in). */
public class WebappSurfaceForDevice(
  private val gateway: BridgethingGateway,
  public val deviceId: String,
) {
  /** Typed request to this peer: companion sends, daemon responds. */
  public suspend fun list(timeout: Duration = 30.seconds): RequestResult<WebappList, Nothing> {
    val outboundData = GatewayToBridgeMsgData.Webapp(GatewayToBridgeWebappMsg.List)
    val response = gateway.request(deviceId, outboundData, timeout)
    return when (val d = response.data) {
      is BridgeToGatewayMsgData.Webapp -> when (val inner = d.data) {
        is BridgeToGatewayWebappMsg.Webapps -> RequestResult.Ok(inner.data)
        else -> RequestResult.ProtocolErr(GatewayError.Unsupported)
      }
      is BridgeToGatewayMsgData.Error -> RequestResult.ProtocolErr(d.data)
      else -> RequestResult.ProtocolErr(GatewayError.Unsupported)
    }
  }

  /** Typed request to this peer: companion sends, daemon responds. */
  public suspend fun getActive(timeout: Duration = 30.seconds): RequestResult<WebappActive, Nothing> {
    val outboundData = GatewayToBridgeMsgData.Webapp(GatewayToBridgeWebappMsg.GetActive)
    val response = gateway.request(deviceId, outboundData, timeout)
    return when (val d = response.data) {
      is BridgeToGatewayMsgData.Webapp -> when (val inner = d.data) {
        is BridgeToGatewayWebappMsg.Active -> RequestResult.Ok(inner.data)
        else -> RequestResult.ProtocolErr(GatewayError.Unsupported)
      }
      is BridgeToGatewayMsgData.Error -> RequestResult.ProtocolErr(d.data)
      else -> RequestResult.ProtocolErr(GatewayError.Unsupported)
    }
  }

  /** Typed request to this peer: companion sends, daemon responds. */
  public suspend fun switchTo(req: WebappSwitchTo, timeout: Duration = 30.seconds): RequestResult<WebappActive, WebappError> {
    val outboundData = GatewayToBridgeMsgData.Webapp(GatewayToBridgeWebappMsg.SwitchTo(req))
    val response = gateway.request(deviceId, outboundData, timeout)
    return when (val d = response.data) {
      is BridgeToGatewayMsgData.Webapp -> when (val inner = d.data) {
        is BridgeToGatewayWebappMsg.Switched -> RequestResult.Ok(inner.data)
        is BridgeToGatewayWebappMsg.WebappError -> RequestResult.DomainErr(inner.data)
        else -> RequestResult.ProtocolErr(GatewayError.Unsupported)
      }
      is BridgeToGatewayMsgData.Error -> RequestResult.ProtocolErr(d.data)
      else -> RequestResult.ProtocolErr(GatewayError.Unsupported)
    }
  }

  /** Typed request to this peer: companion sends, daemon responds. */
  public suspend fun install(req: WebappInstall, timeout: Duration = 30.seconds): RequestResult<WebappInfo, WebappError> {
    val outboundData = GatewayToBridgeMsgData.Webapp(GatewayToBridgeWebappMsg.Install(req))
    val response = gateway.request(deviceId, outboundData, timeout)
    return when (val d = response.data) {
      is BridgeToGatewayMsgData.Webapp -> when (val inner = d.data) {
        is BridgeToGatewayWebappMsg.Installed -> RequestResult.Ok(inner.data)
        is BridgeToGatewayWebappMsg.WebappError -> RequestResult.DomainErr(inner.data)
        else -> RequestResult.ProtocolErr(GatewayError.Unsupported)
      }
      is BridgeToGatewayMsgData.Error -> RequestResult.ProtocolErr(d.data)
      else -> RequestResult.ProtocolErr(GatewayError.Unsupported)
    }
  }

  /** Typed request to this peer: companion sends, daemon responds. */
  public suspend fun uninstall(req: WebappUninstall, timeout: Duration = 30.seconds): RequestResult<WebappActive, WebappError> {
    val outboundData = GatewayToBridgeMsgData.Webapp(GatewayToBridgeWebappMsg.Uninstall(req))
    val response = gateway.request(deviceId, outboundData, timeout)
    return when (val d = response.data) {
      is BridgeToGatewayMsgData.Webapp -> when (val inner = d.data) {
        is BridgeToGatewayWebappMsg.Uninstalled -> RequestResult.Ok(inner.data)
        is BridgeToGatewayWebappMsg.WebappError -> RequestResult.DomainErr(inner.data)
        else -> RequestResult.ProtocolErr(GatewayError.Unsupported)
      }
      is BridgeToGatewayMsgData.Error -> RequestResult.ProtocolErr(d.data)
      else -> RequestResult.ProtocolErr(GatewayError.Unsupported)
    }
  }

}

/** Per-peer view of [BridgethingGateway] returned by [device]. */
public class BridgethingGatewayDevice(
  public val gateway: BridgethingGateway,
  public val deviceId: String,
) {
  /** Per-peer methods for the `System` wire surface. */
  public val system: SystemSurfaceForDevice get() = SystemSurfaceForDevice(gateway, deviceId)
  /** Per-peer methods for the `Transport` wire surface. */
  public val transport: TransportSurfaceForDevice get() = TransportSurfaceForDevice(gateway, deviceId)
  /** Per-peer methods for the `Forward` wire surface. */
  public val forward: ForwardSurfaceForDevice get() = ForwardSurfaceForDevice(gateway, deviceId)
  /** Per-peer methods for the `Version` wire surface. */
  public val version: VersionSurfaceForDevice get() = VersionSurfaceForDevice(gateway, deviceId)
  /** Per-peer methods for the `Asset` wire surface. */
  public val asset: AssetSurfaceForDevice get() = AssetSurfaceForDevice(gateway, deviceId)
  /** Per-peer methods for the `Authority` wire surface. */
  public val authority: AuthoritySurfaceForDevice get() = AuthoritySurfaceForDevice(gateway, deviceId)
  /** Per-peer methods for the `Chrome` wire surface. */
  public val chrome: ChromeSurfaceForDevice get() = ChromeSurfaceForDevice(gateway, deviceId)
  /** Per-peer methods for the `NowPlayingUpdate` wire surface. */
  public val nowPlayingUpdate: NowPlayingUpdateSurfaceForDevice get() = NowPlayingUpdateSurfaceForDevice(gateway, deviceId)
  /** Per-peer methods for the `Webapp` wire surface. */
  public val webapp: WebappSurfaceForDevice get() = WebappSurfaceForDevice(gateway, deviceId)
}

/** Methods scoped to the `System` wire surface. */
public val BridgethingGateway.system: SystemSurface
  get() = SystemSurface(this)

/** Methods scoped to the `Transport` wire surface. */
public val BridgethingGateway.transport: TransportSurface
  get() = TransportSurface(this)

/** Methods scoped to the `Forward` wire surface. */
public val BridgethingGateway.forward: ForwardSurface
  get() = ForwardSurface(this)

/** Methods scoped to the `Version` wire surface. */
public val BridgethingGateway.version: VersionSurface
  get() = VersionSurface(this)

/** Methods scoped to the `Asset` wire surface. */
public val BridgethingGateway.asset: AssetSurface
  get() = AssetSurface(this)

/** Methods scoped to the `Authority` wire surface. */
public val BridgethingGateway.authority: AuthoritySurface
  get() = AuthoritySurface(this)

/** Methods scoped to the `Chrome` wire surface. */
public val BridgethingGateway.chrome: ChromeSurface
  get() = ChromeSurface(this)

/** Methods scoped to the `NowPlayingUpdate` wire surface. */
public val BridgethingGateway.nowPlayingUpdate: NowPlayingUpdateSurface
  get() = NowPlayingUpdateSurface(this)

/** Methods scoped to the `Webapp` wire surface. */
public val BridgethingGateway.webapp: WebappSurface
  get() = WebappSurface(this)

/** Returns a per-device proxy with `deviceId` baked into every method and Flow. */
public fun BridgethingGateway.device(deviceId: String): BridgethingGatewayDevice = BridgethingGatewayDevice(this, deviceId)

public class AssetRequestHandle internal constructor(
  private val gateway: BridgethingGateway,
  public val deviceId: String,
  private val requestId: ByteArray,
) {
  public suspend fun respond(response: AssetGotReply) {
    val msg = GatewayToBridgeMsg(
      id = UUID.randomUUID().toBytes(),
      meta = GatewayMsgMeta.Response(ResponseMeta(requestId = requestId)),
      data = GatewayToBridgeMsgData.Asset(GatewayToBridgeAssetMsg.Got(response)),
    )
    gateway.send(deviceId, msg)
  }

  public suspend fun respondErr(error: AssetNotFoundReply) {
    val msg = GatewayToBridgeMsg(
      id = UUID.randomUUID().toBytes(),
      meta = GatewayMsgMeta.Response(ResponseMeta(requestId = requestId)),
      data = GatewayToBridgeMsgData.Asset(GatewayToBridgeAssetMsg.NotFound(error)),
    )
    gateway.send(deviceId, msg)
  }

  public suspend fun respondProtocolErr(error: GatewayError) {
    val msg = GatewayToBridgeMsg(
      id = UUID.randomUUID().toBytes(),
      meta = GatewayMsgMeta.Response(ResponseMeta(requestId = requestId)),
      data = GatewayToBridgeMsgData.Error(error),
    )
    gateway.send(deviceId, msg)
  }
}

