//! Emits a wire-surface coverage manifest (Swift + Kotlin) listing every
//! inbound variant the companion can receive, grouped by kind, as
//! `"<surface>.<variant>"` ids.
//!
//! The companion test suites consume it as a coverage ratchet: every
//! inbound REQUEST must be answered within a short timeout (even an
//! `unimplemented` reply) instead of hanging the daemon's `request()`, and
//! every inbound command/event must be explicitly classified (handled or
//! deliberately dropped). A new `#[bridge_*]` surface appears here
//! automatically the next time codegen runs, forcing a conscious decision
//! in the tests rather than silently going unhandled.

use std::path::Path;

use anyhow::{Context, Result};

use super::plan::{EntryCategory, Plan, surfaces};

const SWIFT_OUTPUT: &str = "packages/gateway/swift/Sources/BridgethingGateway/WireSurfaceManifest+Generated.swift";
const KOTLIN_OUTPUT: &str =
  "packages/gateway/kotlin/gateway/src/main/kotlin/dev/bridgething/gateway/WireSurfaceManifest.kt";
const KOTLIN_PACKAGE: &str = "com.bridgething.gateway";

struct ManifestData {
  requests: Vec<String>,
  commands: Vec<String>,
  events: Vec<String>,
}

/// Collect inbound (BridgeToGateway) variant ids from the gateway plan.
/// Outbound-only surfaces (capabilities, authority, time, ...) contribute
/// nothing - they have no inbound entry or requests.
fn collect(plan: &Plan) -> ManifestData {
  let surfaces = surfaces(plan);
  let mut requests = Vec::new();
  let mut commands = Vec::new();
  let mut events = Vec::new();
  for s in &surfaces {
    for r in &s.inbound_requests {
      requests.push(format!("{}.{}", s.prop, r.request_disc));
    }
    for iv in s.inbound_event_variants() {
      let id = format!("{}.{}", s.prop, iv.disc);
      match iv.category {
        Some(EntryCategory::Command) => commands.push(id),
        // Event, Skip, or untagged: treat as a fire-and-forget event for
        // classification purposes (the ratchet only distinguishes
        // request-vs-not; command/event split is informational).
        _ => events.push(id),
      }
    }
  }
  requests.sort();
  requests.dedup();
  commands.sort();
  commands.dedup();
  events.sort();
  events.dedup();
  ManifestData {
    requests,
    commands,
    events,
  }
}

const DOC: &str = "Every inbound (BridgeToGateway) wire variant the companion can receive, \
grouped by kind, as `\"<surface>.<variant>\"` ids. Drives the companion test suite's coverage \
ratchet: every request must be answered (even `unimplemented`) and every command/event \
classified (handled or explicitly dropped). New `#[bridge_*]` surfaces appear here automatically.";

pub fn emit_swift_manifest(plan: &Plan) -> Result<()> {
  let d = collect(plan);
  let mut out = String::new();
  out.push_str("// @generated by tools/codegen - do not edit. Run `just codegen` to regenerate.\n\n");
  out.push_str("import Foundation\n\n");
  out.push_str(&format!("/// {DOC}\n"));
  out.push_str("public enum WireSurfaceManifest {\n");
  push_swift_array(&mut out, "inboundRequests", &d.requests);
  push_swift_array(&mut out, "inboundCommands", &d.commands);
  push_swift_array(&mut out, "inboundEvents", &d.events);
  out.push_str("}\n");
  std::fs::create_dir_all(Path::new(SWIFT_OUTPUT).parent().unwrap()).context("ensure swift manifest dir")?;
  std::fs::write(SWIFT_OUTPUT, out).context("write swift manifest")?;
  Ok(())
}

fn push_swift_array(out: &mut String, name: &str, items: &[String]) {
  out.push_str(&format!("  public static let {name}: [String] = [\n"));
  for it in items {
    out.push_str(&format!("    \"{it}\",\n"));
  }
  out.push_str("  ]\n");
}

pub fn emit_kotlin_manifest(plan: &Plan) -> Result<()> {
  let d = collect(plan);
  let mut out = String::new();
  out.push_str("// @generated by tools/codegen - do not edit. Run `just codegen` to regenerate.\n");
  out.push_str(&format!("package {KOTLIN_PACKAGE}\n\n"));
  out.push_str(&format!("/** {DOC} */\n"));
  out.push_str("object WireSurfaceManifest {\n");
  push_kotlin_list(&mut out, "inboundRequests", &d.requests);
  push_kotlin_list(&mut out, "inboundCommands", &d.commands);
  push_kotlin_list(&mut out, "inboundEvents", &d.events);
  out.push_str("}\n");
  std::fs::create_dir_all(Path::new(KOTLIN_OUTPUT).parent().unwrap()).context("ensure kotlin manifest dir")?;
  std::fs::write(KOTLIN_OUTPUT, out).context("write kotlin manifest")?;
  Ok(())
}

fn push_kotlin_list(out: &mut String, name: &str, items: &[String]) {
  out.push_str(&format!("  val {name}: List<String> = listOf(\n"));
  for it in items {
    out.push_str(&format!("    \"{it}\",\n"));
  }
  out.push_str("  )\n");
}
