//! Swift emitter for surface-namespaced gateway dispatch.
//!
//! Each surface gets two structs:
//! - `<Name>Surface` — gateway-level: cross-peer AsyncStreams, broadcast
//!   sends, typed queries with explicit deviceId parameter.
//! - `<Name>SurfaceForDevice` — per-peer: filtered AsyncStreams, deviceId
//!   baked into sends and queries.
//!
//! `gateway.<surface>` is a nonisolated extension property returning a
//! fresh struct; `gateway.device(_:)` returns a `BridgethingGatewayDevice`
//! proxy whose surfaces are device-scoped.

use std::path::Path;

use anyhow::{Context, Result};

use super::plan::{EntryCategory, Plan, Surface, TypedRequestEntry, rename_camel, surfaces};

/// Wrap an identifier in backticks if it collides with a Swift keyword.
/// Used for codegen-emitted method/property names that come from wire
/// discriminators (e.g. `repeat`).
fn swift_ident(s: &str) -> String {
  match s {
    "associatedtype" | "class" | "deinit" | "enum" | "extension" | "fileprivate" | "func" | "import" | "init"
    | "inout" | "internal" | "let" | "open" | "operator" | "private" | "protocol" | "public" | "rethrows"
    | "static" | "struct" | "subscript" | "typealias" | "var" | "break" | "case" | "continue" | "default" | "defer"
    | "do" | "else" | "fallthrough" | "for" | "guard" | "if" | "in" | "repeat" | "return" | "switch" | "where"
    | "while" | "as" | "Any" | "catch" | "false" | "is" | "nil" | "super" | "self" | "Self" | "throw" | "throws"
    | "true" | "try" | "Type" | "Protocol" => format!("`{s}`"),
    _ => s.to_string(),
  }
}

const SWIFT_OUTPUT: &str = "packages/gateway/swift/Sources/BridgethingGateway/Dispatch+Generated.swift";

pub fn emit_swift(plan: &Plan) -> Result<()> {
  let surfaces = surfaces(plan);
  let mut out = String::new();
  out.push_str("// THIS FILE IS GENERATED BY tools/codegen. Do not edit by hand.\n");
  out.push_str("// Re-generate with `just codegen` (or `just swift`).\n\n");
  out.push_str("import BridgethingSchema\n");
  out.push_str("import Foundation\n\n");

  if !plan.outbound_requests.is_empty() || !plan.inbound_requests.is_empty() {
    out.push_str(&swift_request_result_enum());
  }

  for s in &surfaces {
    push_gateway_surface_struct(&mut out, s);
  }

  for s in &surfaces {
    push_device_surface_struct(&mut out, s);
  }

  push_device_proxy_struct(&mut out, &surfaces);

  out.push_str("extension BridgethingGateway {\n");
  for s in &surfaces {
    out.push_str(&format!(
      "  /// Methods scoped to the `{}` wire surface.\n  public nonisolated var {}: {}Surface {{ {}Surface(gateway: self) }}\n",
      s.name, s.prop, s.name, s.name
    ));
  }
  out.push_str(
    "  /// Returns a per-device proxy with `deviceId` baked into every method and stream.\n  public nonisolated func device(_ deviceId: String) -> BridgethingGatewayDevice {\n    BridgethingGatewayDevice(gateway: self, deviceId: deviceId)\n  }\n}\n\n",
  );

  for s in &surfaces {
    for r in &s.inbound_requests {
      out.push_str(&swift_request_handle_class(r));
    }
  }

  std::fs::create_dir_all(Path::new(SWIFT_OUTPUT).parent().unwrap()).context("ensure swift dispatch dir")?;
  std::fs::write(SWIFT_OUTPUT, out).context("write swift dispatch")?;
  Ok(())
}

fn swift_request_result_enum() -> String {
  r#"public enum RequestResult<R: Sendable, E: Sendable>: Sendable {
  case ok(R)
  case domain(E)
  case protocolError(GatewayError)
}

"#
  .to_string()
}

// ---------------------------------------------------------------------------
// Gateway-level surface struct
// ---------------------------------------------------------------------------

fn push_gateway_surface_struct(out: &mut String, s: &Surface) {
  out.push_str(&format!(
    "/// Cross-peer methods for the `{}` wire surface.\npublic struct {}Surface: Sendable {{\n  public let gateway: BridgethingGateway\n\n",
    s.name, s.name
  ));
  push_inbound_streams_gateway(out, s);
  push_request_streams(out, s, /* device_scope */ false);
  push_outbound_methods_gateway(out, s);
  push_query_methods_gateway(out, s);
  out.push_str("}\n\n");
}

fn push_inbound_streams_gateway(out: &mut String, s: &Surface) {
  let Some(e) = &s.inbound else {
    return;
  };
  let outer_camel = swift_ident(&rename_camel(&e.outer_variant));
  let leaf = e.inner_variants.is_empty();
  if leaf && e.outer_payload.is_some() {
    let payload_swift = e.outer_payload.as_ref().map(|p| p.swift()).unwrap();
    out.push_str(&format!(
      "  /// Cross-peer stream of `{}` messages.\n  public var all: AsyncStream<(deviceId: String, msg: {payload_swift})> {{\n    AsyncStream {{ continuation in\n      let task = Task {{ [gateway] in\n        for await event in gateway.events {{\n          if case .message(let deviceId, let message) = event,\n             case .{outer_camel}(let payload) = message.data {{\n            continuation.yield((deviceId: deviceId, msg: payload))\n          }}\n        }}\n        continuation.finish()\n      }}\n      continuation.onTermination = {{ _ in task.cancel() }}\n    }}\n  }}\n\n",
      s.name
    ));
    return;
  }
  if leaf {
    return;
  }
  for iv in s.inbound_event_variants() {
    let prop = swift_ident(&rename_camel(&iv.variant));
    let inner_camel = swift_ident(&rename_camel(&iv.variant));
    let stream_ty = match &iv.payload {
      Some(p) => format!("(deviceId: String, msg: {})", p.swift()),
      None => "String".to_string(),
    };
    let yield_body = match &iv.payload {
      Some(_) => format!(
        "          if case .message(let deviceId, let message) = event,\n             case .{outer_camel}(let outer) = message.data,\n             case .{inner_camel}(let inner) = outer {{\n            continuation.yield((deviceId: deviceId, msg: inner))\n          }}"
      ),
      None => format!(
        "          if case .message(let deviceId, let message) = event,\n             case .{outer_camel}(let outer) = message.data,\n             case .{inner_camel} = outer {{\n            continuation.yield(deviceId)\n          }}"
      ),
    };
    out.push_str(&format!(
      "  /// Cross-peer stream of `{}::{}` messages.\n  public var {prop}: AsyncStream<{stream_ty}> {{\n    AsyncStream {{ continuation in\n      let task = Task {{ [gateway] in\n        for await event in gateway.events {{\n{yield_body}\n        }}\n        continuation.finish()\n      }}\n      continuation.onTermination = {{ _ in task.cancel() }}\n    }}\n  }}\n\n",
      s.name, iv.variant
    ));
  }
}

fn push_request_streams(out: &mut String, s: &Surface, device_scope: bool) {
  for r in &s.inbound_requests {
    push_request_stream(out, r, device_scope);
  }
}

fn push_request_stream(out: &mut String, r: &TypedRequestEntry, device_scope: bool) {
  let surface_camel = swift_ident(&rename_camel(&r.surface));
  let req_variant_camel = swift_ident(&rename_camel(&r.request_disc));
  let stream_ty = if r.request_takes_payload {
    format!("(handle: {}Handle, req: {})", r.request, r.request)
  } else {
    format!("{}Handle", r.request)
  };
  let yield_expr = if r.request_takes_payload {
    "continuation.yield((handle: handle, req: payload))"
  } else {
    "continuation.yield(handle)"
  };
  let inner_pat = if r.request_takes_payload {
    format!("case .{req_variant_camel}(let payload)")
  } else {
    format!("case .{req_variant_camel}")
  };
  let device_filter = if device_scope {
    "          guard deviceId == self.deviceId else { continue }\n"
  } else {
    ""
  };
  out.push_str(&format!(
    "  /// Stream of typed inbound `{}` requests with handles for typed responses.\n  public var requests: AsyncStream<{stream_ty}> {{\n    AsyncStream {{ continuation in\n      let task = Task {{ [gateway] in\n        for await event in gateway.events {{\n          guard case .message(let deviceId, let message) = event else {{ continue }}\n{device_filter}          guard case .request = message.meta else {{ continue }}\n          guard case .{surface_camel}(let outer) = message.data else {{ continue }}\n          guard {inner_pat} = outer else {{ continue }}\n          let handle = {}Handle(gateway: gateway, deviceId: deviceId, requestId: message.id)\n          {yield_expr}\n        }}\n        continuation.finish()\n      }}\n      continuation.onTermination = {{ _ in task.cancel() }}\n    }}\n  }}\n\n",
    r.request, r.request
  ));
}

fn push_outbound_methods_gateway(out: &mut String, s: &Surface) {
  let Some(e) = &s.outbound else {
    return;
  };
  let category_meta = match e.category {
    EntryCategory::Event => ".event",
    EntryCategory::Command => ".command",
    EntryCategory::Skip => ".event",
  };
  let leaf = e.inner_variants.is_empty();
  let outer_camel = swift_ident(&rename_camel(&e.outer_variant));
  if leaf && e.outer_payload.is_some() {
    let payload_swift = e.outer_payload.as_ref().map(|p| p.swift()).unwrap();
    let device_param = if e.unicast { "deviceId: String, " } else { "" };
    let body = if e.unicast {
      format!(
        "    let msg = GatewayToBridgeMsg(id: UUID().data, meta: {category_meta}, data: .{outer_camel}(payload))\n    try await gateway.send(deviceId: deviceId, msg, priority: priority)"
      )
    } else {
      format!(
        "    let ids = await gateway.connectedDeviceIds()\n    try await withThrowingTaskGroup(of: Void.self) {{ [gateway] group in\n      for deviceId in ids {{\n        group.addTask {{\n          let msg = GatewayToBridgeMsg(id: UUID().data, meta: {category_meta}, data: .{outer_camel}(payload))\n          try await gateway.send(deviceId: deviceId, msg, priority: priority)\n        }}\n      }}\n      try await group.waitForAll()\n    }}"
      )
    };
    let doc = if e.unicast {
      format!("Send a `{}` event to a specific peer.", s.name)
    } else {
      format!("Send a `{}` event to every connected peer (broadcast).", s.name)
    };
    out.push_str(&format!(
      "  /// {doc}\n  public func send({device_param}_ payload: {payload_swift}, priority: Priority = .normal) async throws {{\n{body}\n  }}\n\n"
    ));
    return;
  }
  if leaf {
    return;
  }
  for iv in s.outbound_send_variants() {
    let method = swift_ident(&rename_camel(&iv.variant));
    let inner_camel = swift_ident(&rename_camel(&iv.variant));
    let device_param = if e.unicast { "deviceId: String, " } else { "" };
    let (param, inner_arg) = match &iv.payload {
      Some(p) => (format!("_ payload: {}, ", p.swift()), "(payload)".to_string()),
      None => (String::new(), String::new()),
    };
    let data_expr = format!(".{outer_camel}(.{inner_camel}{inner_arg})");
    let body = if e.unicast {
      format!(
        "    let msg = GatewayToBridgeMsg(id: UUID().data, meta: {category_meta}, data: {data_expr})\n    try await gateway.send(deviceId: deviceId, msg, priority: priority)"
      )
    } else {
      format!(
        "    let ids = await gateway.connectedDeviceIds()\n    try await withThrowingTaskGroup(of: Void.self) {{ [gateway] group in\n      for deviceId in ids {{\n        group.addTask {{\n          let msg = GatewayToBridgeMsg(id: UUID().data, meta: {category_meta}, data: {data_expr})\n          try await gateway.send(deviceId: deviceId, msg, priority: priority)\n        }}\n      }}\n      try await group.waitForAll()\n    }}"
      )
    };
    let doc = if e.unicast {
      format!("Send `{}::{}` to a specific peer.", s.name, iv.variant)
    } else {
      format!("Send `{}::{}` to every connected peer (broadcast).", s.name, iv.variant)
    };
    out.push_str(&format!(
      "  /// {doc}\n  public func {method}({device_param}{param}priority: Priority = .normal) async throws {{\n{body}\n  }}\n\n"
    ));
  }
}

fn push_query_methods_gateway(out: &mut String, s: &Surface) {
  for r in &s.outbound_queries {
    push_query_method_gateway(out, r);
  }
}

fn push_query_method_gateway(out: &mut String, r: &TypedRequestEntry) {
  let method = swift_ident(&rename_camel(&r.request_variant_pascal()));
  let req_param = if r.request_takes_payload {
    format!(", _ req: {}", r.request)
  } else {
    String::new()
  };
  let domain = r.error.as_deref().unwrap_or("Never");
  let surface_camel = swift_ident(&rename_camel(&r.surface));
  let req_variant_camel = swift_ident(&rename_camel(&r.request_disc));
  let resp_variant_camel = swift_ident(&rename_camel(&r.response_disc));
  let request_data_expr = if r.request_takes_payload {
    format!(".{surface_camel}(.{req_variant_camel}(req))")
  } else {
    format!(".{surface_camel}(.{req_variant_camel})")
  };
  out.push_str(&format!(
    "  /// Typed request to a specific peer: companion sends, daemon responds.\n  public func {method}(deviceId: String{req_param}, timeout: Duration = .seconds(30)) async throws -> RequestResult<{}, {domain}> {{\n",
    r.response
  ));
  out.push_str(&format!(
    "    let response = try await gateway.request(deviceId: deviceId, {request_data_expr}, timeout: timeout)\n"
  ));
  out.push_str("    switch response.data {\n");
  out.push_str(&format!(
    "    case .{surface_camel}(let inner):\n      switch inner {{\n      case .{resp_variant_camel}(let value): return .ok(value)\n"
  ));
  if let Some(err_disc) = &r.error_disc {
    let err_variant_camel = swift_ident(err_disc);
    out.push_str(&format!(
      "      case .{err_variant_camel}(let err): return .domain(err)\n"
    ));
  }
  out.push_str("      default: return .protocolError(.unsupported)\n      }\n");
  out.push_str("    case .error(let err): return .protocolError(err)\n");
  out.push_str("    default: return .protocolError(.unsupported)\n");
  out.push_str("    }\n  }\n\n");
}

// ---------------------------------------------------------------------------
// Device-level surface struct
// ---------------------------------------------------------------------------

fn push_device_surface_struct(out: &mut String, s: &Surface) {
  out.push_str(&format!(
    "/// Per-peer methods for the `{}` wire surface (deviceId is baked in).\npublic struct {}SurfaceForDevice: Sendable {{\n  public let gateway: BridgethingGateway\n  public let deviceId: String\n\n",
    s.name, s.name
  ));
  push_inbound_streams_device(out, s);
  push_request_streams(out, s, /* device_scope */ true);
  push_outbound_methods_device(out, s);
  push_query_methods_device(out, s);
  out.push_str("}\n\n");
}

fn push_inbound_streams_device(out: &mut String, s: &Surface) {
  let Some(e) = &s.inbound else {
    return;
  };
  let outer_camel = swift_ident(&rename_camel(&e.outer_variant));
  let leaf = e.inner_variants.is_empty();
  if leaf && e.outer_payload.is_some() {
    let payload_swift = e.outer_payload.as_ref().map(|p| p.swift()).unwrap();
    out.push_str(&format!(
      "  /// Stream of `{}` messages from this peer.\n  public var all: AsyncStream<{payload_swift}> {{\n    AsyncStream {{ continuation in\n      let task = Task {{ [gateway, deviceId = self.deviceId] in\n        for await event in gateway.events {{\n          if case .message(let evDeviceId, let message) = event,\n             evDeviceId == deviceId,\n             case .{outer_camel}(let payload) = message.data {{\n            continuation.yield(payload)\n          }}\n        }}\n        continuation.finish()\n      }}\n      continuation.onTermination = {{ _ in task.cancel() }}\n    }}\n  }}\n\n",
      s.name
    ));
    return;
  }
  if leaf {
    return;
  }
  for iv in s.inbound_event_variants() {
    let prop = swift_ident(&rename_camel(&iv.variant));
    let inner_camel = swift_ident(&rename_camel(&iv.variant));
    let stream_ty = match &iv.payload {
      Some(p) => p.swift(),
      None => "Void".to_string(),
    };
    let yield_body = match &iv.payload {
      Some(_) => format!(
        "          if case .message(let evDeviceId, let message) = event,\n             evDeviceId == deviceId,\n             case .{outer_camel}(let outer) = message.data,\n             case .{inner_camel}(let inner) = outer {{\n            continuation.yield(inner)\n          }}"
      ),
      None => format!(
        "          if case .message(let evDeviceId, let message) = event,\n             evDeviceId == deviceId,\n             case .{outer_camel}(let outer) = message.data,\n             case .{inner_camel} = outer {{\n            continuation.yield(())\n          }}"
      ),
    };
    out.push_str(&format!(
      "  /// Stream of `{}::{}` from this peer.\n  public var {prop}: AsyncStream<{stream_ty}> {{\n    AsyncStream {{ continuation in\n      let task = Task {{ [gateway, deviceId = self.deviceId] in\n        for await event in gateway.events {{\n{yield_body}\n        }}\n        continuation.finish()\n      }}\n      continuation.onTermination = {{ _ in task.cancel() }}\n    }}\n  }}\n\n",
      s.name, iv.variant
    ));
  }
}

fn push_outbound_methods_device(out: &mut String, s: &Surface) {
  let Some(e) = &s.outbound else {
    return;
  };
  let category_meta = match e.category {
    EntryCategory::Event => ".event",
    EntryCategory::Command => ".command",
    EntryCategory::Skip => ".event",
  };
  let leaf = e.inner_variants.is_empty();
  let outer_camel = swift_ident(&rename_camel(&e.outer_variant));
  if leaf && e.outer_payload.is_some() {
    let payload_swift = e.outer_payload.as_ref().map(|p| p.swift()).unwrap();
    out.push_str(&format!(
      "  /// Send a `{}` event to this peer.\n  public func send(_ payload: {payload_swift}, priority: Priority = .normal) async throws {{\n    let msg = GatewayToBridgeMsg(id: UUID().data, meta: {category_meta}, data: .{outer_camel}(payload))\n    try await gateway.send(deviceId: deviceId, msg, priority: priority)\n  }}\n\n",
      s.name
    ));
    return;
  }
  if leaf {
    return;
  }
  for iv in s.outbound_send_variants() {
    let method = swift_ident(&rename_camel(&iv.variant));
    let inner_camel = swift_ident(&rename_camel(&iv.variant));
    let (param, inner_arg) = match &iv.payload {
      Some(p) => (format!("_ payload: {}, ", p.swift()), "(payload)".to_string()),
      None => (String::new(), String::new()),
    };
    let data_expr = format!(".{outer_camel}(.{inner_camel}{inner_arg})");
    out.push_str(&format!(
      "  /// Send `{}::{}` to this peer.\n  public func {method}({param}priority: Priority = .normal) async throws {{\n    let msg = GatewayToBridgeMsg(id: UUID().data, meta: {category_meta}, data: {data_expr})\n    try await gateway.send(deviceId: deviceId, msg, priority: priority)\n  }}\n\n",
      s.name, iv.variant
    ));
  }
}

fn push_query_methods_device(out: &mut String, s: &Surface) {
  for r in &s.outbound_queries {
    push_query_method_device(out, r);
  }
}

fn push_query_method_device(out: &mut String, r: &TypedRequestEntry) {
  let method = swift_ident(&rename_camel(&r.request_variant_pascal()));
  let req_param = if r.request_takes_payload {
    format!("_ req: {}, ", r.request)
  } else {
    String::new()
  };
  let domain = r.error.as_deref().unwrap_or("Never");
  let surface_camel = swift_ident(&rename_camel(&r.surface));
  let req_variant_camel = swift_ident(&rename_camel(&r.request_disc));
  let resp_variant_camel = swift_ident(&rename_camel(&r.response_disc));
  let request_data_expr = if r.request_takes_payload {
    format!(".{surface_camel}(.{req_variant_camel}(req))")
  } else {
    format!(".{surface_camel}(.{req_variant_camel})")
  };
  out.push_str(&format!(
    "  /// Typed request to this peer: companion sends, daemon responds.\n  public func {method}({req_param}timeout: Duration = .seconds(30)) async throws -> RequestResult<{}, {domain}> {{\n",
    r.response
  ));
  out.push_str(&format!(
    "    let response = try await gateway.request(deviceId: deviceId, {request_data_expr}, timeout: timeout)\n"
  ));
  out.push_str("    switch response.data {\n");
  out.push_str(&format!(
    "    case .{surface_camel}(let inner):\n      switch inner {{\n      case .{resp_variant_camel}(let value): return .ok(value)\n"
  ));
  if let Some(err_disc) = &r.error_disc {
    let err_variant_camel = swift_ident(err_disc);
    out.push_str(&format!(
      "      case .{err_variant_camel}(let err): return .domain(err)\n"
    ));
  }
  out.push_str("      default: return .protocolError(.unsupported)\n      }\n");
  out.push_str("    case .error(let err): return .protocolError(err)\n");
  out.push_str("    default: return .protocolError(.unsupported)\n");
  out.push_str("    }\n  }\n\n");
}

// ---------------------------------------------------------------------------
// Device proxy struct
// ---------------------------------------------------------------------------

fn push_device_proxy_struct(out: &mut String, surfaces: &[Surface]) {
  out.push_str("/// Per-peer view of `BridgethingGateway` returned by `device(_:)`.\npublic struct BridgethingGatewayDevice: Sendable {\n  public let gateway: BridgethingGateway\n  public let deviceId: String\n\n");
  for s in surfaces {
    out.push_str(&format!(
      "  /// Per-peer methods for the `{}` wire surface.\n  public var {}: {}SurfaceForDevice {{ {}SurfaceForDevice(gateway: gateway, deviceId: deviceId) }}\n",
      s.name, s.prop, s.name, s.name
    ));
  }
  out.push_str("}\n\n");
}

// ---------------------------------------------------------------------------
// Request handle classes
// ---------------------------------------------------------------------------

fn swift_request_handle_class(r: &TypedRequestEntry) -> String {
  let mut out = String::new();
  let surface_camel = swift_ident(&rename_camel(&r.surface));
  let resp_variant_camel = swift_ident(&rename_camel(&r.response_disc));
  out.push_str(&format!(
    "public final class {}Handle: @unchecked Sendable {{\n",
    r.request
  ));
  out.push_str("  private let gateway: BridgethingGateway\n");
  out.push_str("  public let deviceId: String\n");
  out.push_str("  private let requestId: Data\n\n");
  out.push_str(
    "  init(gateway: BridgethingGateway, deviceId: String, requestId: Data) {\n    self.gateway = gateway\n    self.deviceId = deviceId\n    self.requestId = requestId\n  }\n\n",
  );
  out.push_str(&format!(
    "  public func respond(_ response: {}) async throws {{\n    let msg = GatewayToBridgeMsg(\n      id: UUID().data,\n      meta: .response(ResponseMeta(requestId: requestId)),\n      data: .{surface_camel}(.{resp_variant_camel}(response))\n    )\n    try await gateway.send(deviceId: deviceId, msg)\n  }}\n\n",
    r.response
  ));
  if let (Some(err_type), Some(err_disc)) = (&r.error, &r.error_disc) {
    let err_variant_camel = swift_ident(err_disc);
    out.push_str(&format!(
      "  public func respondErr(_ error: {err_type}) async throws {{\n    let msg = GatewayToBridgeMsg(\n      id: UUID().data,\n      meta: .response(ResponseMeta(requestId: requestId)),\n      data: .{surface_camel}(.{err_variant_camel}(error))\n    )\n    try await gateway.send(deviceId: deviceId, msg)\n  }}\n\n"
    ));
  }
  out.push_str("  public func respondProtocolErr(_ error: GatewayError) async throws {\n    let msg = GatewayToBridgeMsg(\n      id: UUID().data,\n      meta: .response(ResponseMeta(requestId: requestId)),\n      data: .error(error)\n    )\n    try await gateway.send(deviceId: deviceId, msg)\n  }\n");
  out.push_str("}\n\n");
  out
}
