//! TypeScript emitter for surface-namespaced gateway dispatch.
//!
//! Output shape:
//! - one `<Name>Surface` class per surface, accessed via
//!   `gateway.<name>` - broadcast methods and cross-peer listeners.
//! - one `<Name>SurfaceForDevice` class per surface, accessed via
//!   `gateway.device(id).<name>` - unicast methods and per-peer listeners.
//! - `BridgethingGatewayDevice` proxy class returned by `gateway.device(id)`.
//! - typed-switch dispatch in the runtime - no string-keyed lookups,
//!   no `as` casts in either generated dispatch or user code.

use std::{collections::BTreeSet, path::Path};

use anyhow::{Context, Result};

use super::{
  inventory::PayloadType,
  plan::{Plan, Surface, TypedRequestEntry, surfaces},
};

const TS_OUTPUT: &str = "packages/gateway/typescript/src/dispatch.generated.ts";

pub fn emit_typescript(plan: &Plan) -> Result<()> {
  let surfaces = surfaces(plan);
  let mut out = String::new();
  push_header(&mut out);
  push_imports(&mut out, &surfaces);
  push_typed_request_result(&mut out);

  for s in &surfaces {
    push_inbound_handlers_types(&mut out, s);
  }

  for s in &surfaces {
    push_gateway_surface_class(&mut out, s);
  }

  for s in &surfaces {
    push_device_surface_class(&mut out, s);
  }

  push_outer_handlers_types(&mut out, &surfaces);

  push_module_augmentation(&mut out, &surfaces);

  for s in &surfaces {
    for r in &s.inbound_requests {
      push_request_handle_class(&mut out, r);
    }
  }

  push_device_proxy_class(&mut out, &surfaces);

  push_apply_dispatch(&mut out, &surfaces);

  std::fs::create_dir_all(Path::new(TS_OUTPUT).parent().unwrap()).context("ensure ts dispatch dir")?;
  std::fs::write(TS_OUTPUT, out).context("write ts dispatch")?;
  Ok(())
}

fn push_header(out: &mut String) {
  out.push_str("// THIS FILE IS GENERATED BY tools/codegen. Do not edit by hand.\n");
  out.push_str("// Re-generate with `just codegen` (or `just typescript`).\n\n");
}

fn push_imports(out: &mut String, surfaces: &[Surface]) {
  let mut imports: BTreeSet<String> = BTreeSet::new();
  for s in surfaces {
    if let Some(e) = &s.inbound {
      if let Some(PayloadType::Named(n)) = &e.outer_payload {
        imports.insert(n.clone());
      }
      for iv in &e.inner_variants {
        if let Some(PayloadType::Named(n)) = &iv.payload {
          imports.insert(n.clone());
        }
      }
    }
    if let Some(e) = &s.outbound {
      if let Some(PayloadType::Named(n)) = &e.outer_payload {
        imports.insert(n.clone());
      }
      for iv in &e.inner_variants {
        if let Some(PayloadType::Named(n)) = &iv.payload {
          imports.insert(n.clone());
        }
      }
    }
    for r in s.outbound_queries.iter().chain(&s.inbound_requests) {
      if r.request_takes_payload {
        imports.insert(r.request.clone());
      }
      imports.insert(r.response.clone());
      if let Some(e) = &r.error {
        imports.insert(e.clone());
      }
    }
  }
  imports.insert("BridgeToGatewayMsg".to_string());
  imports.insert("WireError".to_string());
  imports.insert("GatewayToBridgeMsg".to_string());
  imports.insert("Priority".to_string());

  out.push_str("import {\n");
  for name in &imports {
    out.push_str(&format!("  type {name},\n"));
  }
  out.push_str("  newUuid,\n");
  out.push_str("} from '@bridgething/lib';\n");
  out.push_str("import { BridgethingGateway, type GatewayEvent } from './index';\n\n");
}

fn push_typed_request_result(out: &mut String) {
  out.push_str(
    "export type TypedRequestResult<R, E> =\n  | { ok: true; response: R }\n  | { ok: false; kind: 'domain'; error: E }\n  | { ok: false; kind: 'protocol'; error: WireError };\n\n",
  );
}

/// Two records per surface: one for gateway-level (deviceId in callback),
/// one for device-level (no deviceId). Only emitted when a surface has
/// >= 2 inbound entries.
fn push_inbound_handlers_types(out: &mut String, s: &Surface) {
  let entries = inbound_handler_entries(s);
  if entries.len() < 2 {
    return;
  }
  out.push_str(&format!("export type {}InboundHandlers = {{\n", s.name));
  for (k, gw_sig, _) in &entries {
    out.push_str(&format!("  {k}: {gw_sig};\n"));
  }
  out.push_str("};\n\n");

  out.push_str(&format!("export type {}DeviceInboundHandlers = {{\n", s.name));
  for (k, _, dev_sig) in &entries {
    out.push_str(&format!("  {k}: {dev_sig};\n"));
  }
  out.push_str("};\n\n");
}

/// Returns (key, gateway-level signature, device-level signature) for
/// each inbound entry of a surface (event variants + typed-request handles).
fn inbound_handler_entries(s: &Surface) -> Vec<(String, String, String)> {
  let mut keys: Vec<(String, String, String)> = Vec::new();
  for iv in s.inbound_event_variants() {
    let gw = match &iv.payload {
      Some(p) => format!("(deviceId: string, msg: {}) => void", p.ts()),
      None => "(deviceId: string) => void".to_string(),
    };
    let dev = match &iv.payload {
      Some(p) => format!("(msg: {}) => void", p.ts()),
      None => "() => void".to_string(),
    };
    keys.push((iv.disc.clone(), gw, dev));
  }
  for r in &s.inbound_requests {
    let payload_arg = if r.request_takes_payload {
      format!(", req: {}", r.request)
    } else {
      String::new()
    };
    let sig = format!("(handle: {}Handle{payload_arg}) => Promise<void> | void", r.request);
    keys.push((r.request_disc.clone(), sig.clone(), sig));
  }
  keys
}

// ---------------------------------------------------------------------------
// Gateway-level surface class
// ---------------------------------------------------------------------------

fn push_gateway_surface_class(out: &mut String, s: &Surface) {
  out.push_str(&format!("export class {}Surface {{\n", s.name));
  out.push_str("  constructor(private readonly _gateway: BridgethingGateway) {}\n\n");

  push_inbound_methods_gateway(out, s);
  push_subscribe_methods_gateway(out, s);
  push_outbound_methods_gateway(out, s);
  push_query_methods_gateway(out, s);

  out.push_str("}\n\n");
}

fn push_inbound_methods_gateway(out: &mut String, s: &Surface) {
  let Some(e) = &s.inbound else {
    // No inbound dispatch entry, but we may still have typed inbound
    // requests (e.g. Asset surface where BridgeToGatewayAssetMsg holds
    // only request/response variants - no event markers). Emit those.
    for r in &s.inbound_requests {
      push_request_handler_method_gateway(out, r);
    }
    return;
  };
  let leaf_inbound = e.inner_variants.is_empty();
  if leaf_inbound && e.outer_payload.is_some() {
    let payload_ts = e.outer_payload.as_ref().map(|p| p.ts()).unwrap();
    out.push_str(&format!(
      "  /** Subscribe to `{}` messages across all peers. */\n  on(handler: (deviceId: string, msg: {payload_ts}) => void): () => void {{\n    return this._gateway.on(event => {{\n      if (event.type !== 'message') return;\n      const data = event.message.data;\n      if (data.type !== '{}') return;\n      handler(event.deviceId, data.data);\n    }});\n  }}\n\n",
      s.name, e.outer_disc
    ));
    return;
  }
  let inner_tag = e.inner_tag_field.as_deref().unwrap_or("event");
  for iv in s.inbound_event_variants() {
    let method = format!("on{}", iv.variant);
    let sig = match &iv.payload {
      Some(p) => format!("(deviceId: string, msg: {}) => void", p.ts()),
      None => "(deviceId: string) => void".to_string(),
    };
    let invoke = match &iv.payload {
      Some(_) => "handler(event.deviceId, inner.data);",
      None => "handler(event.deviceId);",
    };
    out.push_str(&format!(
      "  /** Subscribe to `{}::{}` across all peers. */\n  {method}(handler: {sig}): () => void {{\n    return this._gateway.on(event => {{\n      if (event.type !== 'message') return;\n      const data = event.message.data;\n      if (data.type !== '{}') return;\n      const inner = data.data;\n      if (inner.{inner_tag} !== '{}') return;\n      {invoke}\n    }});\n  }}\n\n",
      s.name, iv.variant, e.outer_disc, iv.disc
    ));
  }
  for r in &s.inbound_requests {
    push_request_handler_method_gateway(out, r);
  }
}

fn push_request_handler_method_gateway(out: &mut String, r: &TypedRequestEntry) {
  let payload_arg = if r.request_takes_payload {
    format!(", req: {}", r.request)
  } else {
    String::new()
  };
  let pass_payload = if r.request_takes_payload {
    ", inner.data".to_string()
  } else {
    String::new()
  };
  let method = format!("on{}", r.request_variant_pascal());
  out.push_str(&format!(
    "  /** Typed inbound `{}` request: handler is given a typed handle for the response. */\n  {method}(handler: (handle: {}Handle{payload_arg}) => Promise<void> | void): () => void {{\n    return this._gateway.on(event => {{\n      if (event.type !== 'message') return;\n      const message = event.message;\n      if (message.meta.kind !== 'request') return;\n      const data = message.data;\n      if (data.type !== '{}') return;\n      const inner = data.data;\n      if (inner.{} !== '{}') return;\n      const handle = new {}Handle(this._gateway, event.deviceId, message.id);\n      const result = handler(handle{pass_payload});\n      if (result && typeof result.then === 'function') {{\n        result.catch((err: unknown) => {{ this._gateway.logger.error('on{} handler threw:', err); }});\n      }}\n    }});\n  }}\n\n",
    r.request, r.request, r.surface_disc, r.inner_tag, r.request_disc, r.request, r.request_variant_pascal()
  ));
}

fn push_subscribe_methods_gateway(out: &mut String, s: &Surface) {
  let total_inbound = s.inbound_event_variants().len() + s.inbound_requests.len();
  if total_inbound < 2 {
    return;
  }
  out.push_str(&format!(
    "  /** Exhaustive subscribe over all inbound `{}` variants. */\n  subscribe(handlers: {}InboundHandlers): () => void {{\n    return this._subscribe(handlers, false);\n  }}\n\n",
    s.name, s.name
  ));
  out.push_str(&format!(
    "  /** Same as `subscribe` but every handler is optional. */\n  subscribePartial(handlers: Partial<{}InboundHandlers>): () => void {{\n    return this._subscribe(handlers, true);\n  }}\n\n",
    s.name
  ));
  push_subscribe_impl_gateway(out, s);
}

fn push_subscribe_impl_gateway(out: &mut String, s: &Surface) {
  let Some(e) = &s.inbound else {
    return;
  };
  let inner_tag = e.inner_tag_field.as_deref().unwrap_or("event");
  out.push_str(&format!(
    "  private _subscribe(handlers: Partial<{}InboundHandlers>, partial: boolean): () => void {{\n    return this._gateway.on(event => {{\n      if (event.type !== 'message') return;\n      const data = event.message.data;\n      if (data.type !== '{}') return;\n      const inner = data.data;\n      switch (inner.{inner_tag}) {{\n",
    s.name, e.outer_disc
  ));
  for iv in s.inbound_event_variants() {
    let invoke = match &iv.payload {
      Some(_) => format!("          handlers.{}?.(event.deviceId, inner.data);", iv.disc),
      None => format!("          handlers.{}?.(event.deviceId);", iv.disc),
    };
    out.push_str(&format!(
      "        case '{}': {{\n{invoke}\n          return;\n        }}\n",
      iv.disc
    ));
  }
  for r in &s.inbound_requests {
    let pass_payload = if r.request_takes_payload {
      ", inner.data".to_string()
    } else {
      String::new()
    };
    out.push_str(&format!(
      "        case '{}': {{\n          if (event.message.meta.kind !== 'request') return;\n          const handler = handlers.{};\n          if (!handler) {{ if (!partial) this._gateway.logger.warn('{}: no handler for inner', '{}'); return; }}\n          const handle = new {}Handle(this._gateway, event.deviceId, event.message.id);\n          const result = handler(handle{pass_payload});\n          if (result && typeof result.then === 'function') {{\n            result.catch((err: unknown) => this._gateway.logger.error('subscribe handler threw:', err));\n          }}\n          return;\n        }}\n",
      r.request_disc, r.request_disc, s.name, r.request_disc, r.request
    ));
  }
  out.push_str(&format!(
    "        default: {{\n          if (!partial) this._gateway.logger.warn('{}: no handler for inner', inner);\n          return;\n        }}\n      }}\n    }});\n  }}\n\n",
    s.name
  ));
  // We need to silence "case fallthrough" / exhaustiveness - for variants
  // that aren't in handlers, the per-case still does `?.()` which is no-op
  // when missing. The `partial` flag controls warning only for default
  // (unknown variant from wire).
  // Note: `case '<variant>'` for variants without handlers still hits its
  // own case (returns early); the warning only fires from `default`.
  // When `partial` is true, *missing* handlers do nothing silently per
  // the optional-chaining `?.`. When `partial` is false, the per-case
  // call still no-ops if undefined; the user contract is to provide all.
  // We intentionally don't enforce no-undefined at runtime - TS does
  // exhaustiveness statically via the `<S>InboundHandlers` type.
  let _ = out;
}

fn push_outbound_methods_gateway(out: &mut String, s: &Surface) {
  let Some(e) = &s.outbound else {
    return;
  };
  let leaf_outbound = e.inner_variants.is_empty();
  let entry_meta = e.category.meta_kind();
  if leaf_outbound && e.outer_payload.is_some() {
    let payload_ts = e.outer_payload.as_ref().map(|p| p.ts()).unwrap();
    let device_arg = if e.unicast { "deviceId: string, " } else { "" };
    let body = if e.unicast {
      format!(
        "    const msg: GatewayToBridgeMsg = {{ id: newUuid(), meta: {{ kind: '{entry_meta}' }}, data: {{ type: '{}', data: payload }} }};\n    await this._gateway.send(deviceId, msg, options);",
        e.outer_disc
      )
    } else {
      format!(
        "    const ids = this._gateway.connectedDeviceIds;\n    await Promise.all(ids.map(deviceId => {{\n      const msg: GatewayToBridgeMsg = {{ id: newUuid(), meta: {{ kind: '{entry_meta}' }}, data: {{ type: '{}', data: payload }} }};\n      return this._gateway.send(deviceId, msg, options);\n    }}));",
        e.outer_disc
      )
    };
    let doc = if e.unicast {
      format!("Send a `{}` event to a specific peer.", s.name)
    } else {
      format!("Send a `{}` event to every connected peer (broadcast).", s.name)
    };
    out.push_str(&format!(
      "  /** {doc} */\n  async send({device_arg}payload: {payload_ts}, options?: {{ priority?: Priority }}): Promise<void> {{\n{body}\n  }}\n\n"
    ));
    return;
  }
  if leaf_outbound {
    return;
  }
  let inner_tag = e.inner_tag_field.as_deref().unwrap_or("event");
  for iv in s.outbound_send_variants() {
    let method = camel_first(&iv.variant);
    let payload_param = match &iv.payload {
      Some(p) => format!("payload: {}", p.ts()),
      None => String::new(),
    };
    let inner_object = match &iv.payload {
      Some(_) => format!("{{ {inner_tag}: '{}', data: payload }}", iv.disc),
      None => format!("{{ {inner_tag}: '{}' }}", iv.disc),
    };
    let device_arg = if e.unicast { "deviceId: string" } else { "" };
    let arg_list = match (device_arg.is_empty(), payload_param.is_empty()) {
      (true, true) => "options?: { priority?: Priority }".to_string(),
      (true, false) => format!("{payload_param}, options?: {{ priority?: Priority }}"),
      (false, true) => format!("{device_arg}, options?: {{ priority?: Priority }}"),
      (false, false) => format!("{device_arg}, {payload_param}, options?: {{ priority?: Priority }}"),
    };
    let variant_meta = iv.category.map(|c| c.meta_kind()).unwrap_or(entry_meta);
    let body = if e.unicast {
      format!(
        "    const msg: GatewayToBridgeMsg = {{ id: newUuid(), meta: {{ kind: '{variant_meta}' }}, data: {{ type: '{}', data: {inner_object} }} }};\n    await this._gateway.send(deviceId, msg, options);",
        e.outer_disc
      )
    } else {
      format!(
        "    const ids = this._gateway.connectedDeviceIds;\n    await Promise.all(ids.map(deviceId => {{\n      const msg: GatewayToBridgeMsg = {{ id: newUuid(), meta: {{ kind: '{variant_meta}' }}, data: {{ type: '{}', data: {inner_object} }} }};\n      return this._gateway.send(deviceId, msg, options);\n    }}));",
        e.outer_disc
      )
    };
    let doc = if e.unicast {
      format!("Send `{}::{}` to a specific peer.", s.name, iv.variant)
    } else {
      format!("Send `{}::{}` to every connected peer (broadcast).", s.name, iv.variant)
    };
    out.push_str(&format!(
      "  /** {doc} */\n  async {method}({arg_list}): Promise<void> {{\n{body}\n  }}\n\n"
    ));
  }
}

fn push_query_methods_gateway(out: &mut String, s: &Surface) {
  for r in &s.outbound_queries {
    push_query_method_gateway(out, r);
  }
}

fn push_query_method_gateway(out: &mut String, r: &TypedRequestEntry) {
  let method = camel_first(&r.request_variant_pascal());
  let req_param = if r.request_takes_payload {
    format!(", req: {}", r.request)
  } else {
    String::new()
  };
  let domain = r.error.as_deref().unwrap_or("never");
  let inner_object = if r.request_takes_payload {
    format!("{{ {}: '{}', data: req }}", r.inner_tag, r.request_disc)
  } else {
    format!("{{ {}: '{}' }}", r.inner_tag, r.request_disc)
  };
  out.push_str(&format!(
    "  /** Typed request to a specific peer: companion sends, daemon responds. */\n  async {method}(deviceId: string{req_param}, options?: {{ timeoutMs?: number }}): Promise<TypedRequestResult<{}, {domain}>> {{\n    const wireData: GatewayToBridgeMsg['data'] = {{ type: '{}', data: {inner_object} }};\n    const response = await this._gateway.request(deviceId, wireData, options?.timeoutMs);\n    const d = response.data;\n    if (d.type === '{}') {{\n      const inner = d.data;\n      if (inner.{} === '{}') return {{ ok: true, response: inner.data }};\n",
    r.response, r.surface_disc, r.surface_disc, r.inner_tag, r.response_disc
  ));
  if let Some(err_disc) = &r.error_disc {
    out.push_str(&format!(
      "      if (inner.{} === '{}') return {{ ok: false, kind: 'domain', error: inner.data }};\n",
      r.inner_tag, err_disc
    ));
  }
  out.push_str("    }\n");
  out.push_str("    if (d.type === 'error') return { ok: false, kind: 'protocol', error: d.data };\n");
  out.push_str("    return { ok: false, kind: 'protocol', error: { type: 'unsupported' } };\n");
  out.push_str("  }\n\n");
}

// ---------------------------------------------------------------------------
// Device-scoped surface class (deviceId baked in)
// ---------------------------------------------------------------------------

fn push_device_surface_class(out: &mut String, s: &Surface) {
  out.push_str(&format!("export class {}SurfaceForDevice {{\n", s.name));
  out.push_str("  constructor(\n    private readonly _gateway: BridgethingGateway,\n    public readonly deviceId: string,\n  ) {}\n\n");

  push_inbound_methods_device(out, s);
  push_subscribe_methods_device(out, s);
  push_outbound_methods_device(out, s);
  push_query_methods_device(out, s);

  out.push_str("}\n\n");
}

fn push_inbound_methods_device(out: &mut String, s: &Surface) {
  let Some(e) = &s.inbound else {
    for r in &s.inbound_requests {
      push_request_handler_method_device(out, r);
    }
    return;
  };
  let leaf_inbound = e.inner_variants.is_empty();
  if leaf_inbound && e.outer_payload.is_some() {
    let payload_ts = e.outer_payload.as_ref().map(|p| p.ts()).unwrap();
    out.push_str(&format!(
      "  /** Subscribe to `{}` messages from this peer. */\n  on(handler: (msg: {payload_ts}) => void): () => void {{\n    return this._gateway.on(event => {{\n      if (event.type !== 'message') return;\n      if (event.deviceId !== this.deviceId) return;\n      const data = event.message.data;\n      if (data.type !== '{}') return;\n      handler(data.data);\n    }});\n  }}\n\n",
      s.name, e.outer_disc
    ));
    return;
  }
  let inner_tag = e.inner_tag_field.as_deref().unwrap_or("event");
  for iv in s.inbound_event_variants() {
    let method = format!("on{}", iv.variant);
    let sig = match &iv.payload {
      Some(p) => format!("(msg: {}) => void", p.ts()),
      None => "() => void".to_string(),
    };
    let invoke = match &iv.payload {
      Some(_) => "handler(inner.data);",
      None => "handler();",
    };
    out.push_str(&format!(
      "  /** Subscribe to `{}::{}` from this peer. */\n  {method}(handler: {sig}): () => void {{\n    return this._gateway.on(event => {{\n      if (event.type !== 'message') return;\n      if (event.deviceId !== this.deviceId) return;\n      const data = event.message.data;\n      if (data.type !== '{}') return;\n      const inner = data.data;\n      if (inner.{inner_tag} !== '{}') return;\n      {invoke}\n    }});\n  }}\n\n",
      s.name, iv.variant, e.outer_disc, iv.disc
    ));
  }
  for r in &s.inbound_requests {
    push_request_handler_method_device(out, r);
  }
}

fn push_request_handler_method_device(out: &mut String, r: &TypedRequestEntry) {
  let payload_arg = if r.request_takes_payload {
    format!(", req: {}", r.request)
  } else {
    String::new()
  };
  let pass_payload = if r.request_takes_payload {
    ", inner.data".to_string()
  } else {
    String::new()
  };
  let method = format!("on{}", r.request_variant_pascal());
  out.push_str(&format!(
    "  /** Typed inbound `{}` request from this peer: handler is given a typed handle for the response. */\n  {method}(handler: (handle: {}Handle{payload_arg}) => Promise<void> | void): () => void {{\n    return this._gateway.on(event => {{\n      if (event.type !== 'message') return;\n      if (event.deviceId !== this.deviceId) return;\n      const message = event.message;\n      if (message.meta.kind !== 'request') return;\n      const data = message.data;\n      if (data.type !== '{}') return;\n      const inner = data.data;\n      if (inner.{} !== '{}') return;\n      const handle = new {}Handle(this._gateway, event.deviceId, message.id);\n      const result = handler(handle{pass_payload});\n      if (result && typeof result.then === 'function') {{\n        result.catch((err: unknown) => {{ this._gateway.logger.error('on{} handler threw:', err); }});\n      }}\n    }});\n  }}\n\n",
    r.request, r.request, r.surface_disc, r.inner_tag, r.request_disc, r.request, r.request_variant_pascal()
  ));
}

fn push_subscribe_methods_device(out: &mut String, s: &Surface) {
  let total_inbound = s.inbound_event_variants().len() + s.inbound_requests.len();
  if total_inbound < 2 {
    return;
  }
  out.push_str(&format!(
    "  /** Exhaustive subscribe over all inbound `{}` variants from this peer. */\n  subscribe(handlers: {}DeviceInboundHandlers): () => void {{\n    return this._subscribe(handlers, false);\n  }}\n\n",
    s.name, s.name
  ));
  out.push_str(&format!(
    "  /** Same as `subscribe` but every handler is optional. */\n  subscribePartial(handlers: Partial<{}DeviceInboundHandlers>): () => void {{\n    return this._subscribe(handlers, true);\n  }}\n\n",
    s.name
  ));
  push_subscribe_impl_device(out, s);
}

fn push_subscribe_impl_device(out: &mut String, s: &Surface) {
  let Some(e) = &s.inbound else {
    return;
  };
  let inner_tag = e.inner_tag_field.as_deref().unwrap_or("event");
  out.push_str(&format!(
    "  private _subscribe(handlers: Partial<{}DeviceInboundHandlers>, partial: boolean): () => void {{\n    return this._gateway.on(event => {{\n      if (event.type !== 'message') return;\n      if (event.deviceId !== this.deviceId) return;\n      const data = event.message.data;\n      if (data.type !== '{}') return;\n      const inner = data.data;\n      switch (inner.{inner_tag}) {{\n",
    s.name, e.outer_disc
  ));
  for iv in s.inbound_event_variants() {
    let invoke = match &iv.payload {
      Some(_) => format!("          handlers.{}?.(inner.data);", iv.disc),
      None => format!("          handlers.{}?.();", iv.disc),
    };
    out.push_str(&format!(
      "        case '{}': {{\n{invoke}\n          return;\n        }}\n",
      iv.disc
    ));
  }
  for r in &s.inbound_requests {
    let pass_payload = if r.request_takes_payload {
      ", inner.data".to_string()
    } else {
      String::new()
    };
    out.push_str(&format!(
      "        case '{}': {{\n          if (event.message.meta.kind !== 'request') return;\n          const handler = handlers.{};\n          if (!handler) {{ if (!partial) this._gateway.logger.warn('{}: no handler for inner', '{}'); return; }}\n          const handle = new {}Handle(this._gateway, event.deviceId, event.message.id);\n          const result = handler(handle{pass_payload});\n          if (result && typeof result.then === 'function') {{\n            result.catch((err: unknown) => this._gateway.logger.error('subscribe handler threw:', err));\n          }}\n          return;\n        }}\n",
      r.request_disc, r.request_disc, s.name, r.request_disc, r.request
    ));
  }
  out.push_str(&format!(
    "        default: {{\n          if (!partial) this._gateway.logger.warn('{}: no handler for inner', inner);\n          return;\n        }}\n      }}\n    }});\n  }}\n\n",
    s.name
  ));
}

fn push_outbound_methods_device(out: &mut String, s: &Surface) {
  let Some(e) = &s.outbound else {
    return;
  };
  let leaf_outbound = e.inner_variants.is_empty();
  let entry_meta = e.category.meta_kind();
  if leaf_outbound && e.outer_payload.is_some() {
    let payload_ts = e.outer_payload.as_ref().map(|p| p.ts()).unwrap();
    out.push_str(&format!(
      "  /** Send a `{}` event to this peer. */\n  async send(payload: {payload_ts}, options?: {{ priority?: Priority }}): Promise<void> {{\n    const msg: GatewayToBridgeMsg = {{ id: newUuid(), meta: {{ kind: '{entry_meta}' }}, data: {{ type: '{}', data: payload }} }};\n    await this._gateway.send(this.deviceId, msg, options);\n  }}\n\n",
      s.name, e.outer_disc
    ));
    return;
  }
  if leaf_outbound {
    return;
  }
  let inner_tag = e.inner_tag_field.as_deref().unwrap_or("event");
  for iv in s.outbound_send_variants() {
    let method = camel_first(&iv.variant);
    let arg_list = match &iv.payload {
      Some(p) => format!("payload: {}, options?: {{ priority?: Priority }}", p.ts()),
      None => "options?: { priority?: Priority }".to_string(),
    };
    let inner_object = match &iv.payload {
      Some(_) => format!("{{ {inner_tag}: '{}', data: payload }}", iv.disc),
      None => format!("{{ {inner_tag}: '{}' }}", iv.disc),
    };
    let variant_meta = iv.category.map(|c| c.meta_kind()).unwrap_or(entry_meta);
    out.push_str(&format!(
      "  /** Send `{}::{}` to this peer. */\n  async {method}({arg_list}): Promise<void> {{\n    const msg: GatewayToBridgeMsg = {{ id: newUuid(), meta: {{ kind: '{variant_meta}' }}, data: {{ type: '{}', data: {inner_object} }} }};\n    await this._gateway.send(this.deviceId, msg, options);\n  }}\n\n",
      s.name, iv.variant, e.outer_disc
    ));
  }
}

fn push_query_methods_device(out: &mut String, s: &Surface) {
  for r in &s.outbound_queries {
    push_query_method_device(out, r);
  }
}

fn push_query_method_device(out: &mut String, r: &TypedRequestEntry) {
  let method = camel_first(&r.request_variant_pascal());
  let req_param = if r.request_takes_payload {
    format!("req: {}, ", r.request)
  } else {
    String::new()
  };
  let domain = r.error.as_deref().unwrap_or("never");
  let inner_object = if r.request_takes_payload {
    format!("{{ {}: '{}', data: req }}", r.inner_tag, r.request_disc)
  } else {
    format!("{{ {}: '{}' }}", r.inner_tag, r.request_disc)
  };
  out.push_str(&format!(
    "  /** Typed request to this peer: companion sends, daemon responds. */\n  async {method}({req_param}options?: {{ timeoutMs?: number }}): Promise<TypedRequestResult<{}, {domain}>> {{\n    const wireData: GatewayToBridgeMsg['data'] = {{ type: '{}', data: {inner_object} }};\n    const response = await this._gateway.request(this.deviceId, wireData, options?.timeoutMs);\n    const d = response.data;\n    if (d.type === '{}') {{\n      const inner = d.data;\n      if (inner.{} === '{}') return {{ ok: true, response: inner.data }};\n",
    r.response, r.surface_disc, r.surface_disc, r.inner_tag, r.response_disc
  ));
  if let Some(err_disc) = &r.error_disc {
    out.push_str(&format!(
      "      if (inner.{} === '{}') return {{ ok: false, kind: 'domain', error: inner.data }};\n",
      r.inner_tag, err_disc
    ));
  }
  out.push_str("    }\n");
  out.push_str("    if (d.type === 'error') return { ok: false, kind: 'protocol', error: d.data };\n");
  out.push_str("    return { ok: false, kind: 'protocol', error: { type: 'unsupported' } };\n");
  out.push_str("  }\n\n");
}

// ---------------------------------------------------------------------------
// Outer handler types
// ---------------------------------------------------------------------------

fn push_outer_handlers_types(out: &mut String, surfaces: &[Surface]) {
  out.push_str("export type BridgeMessageHandlers = {\n");
  for s in surfaces {
    if let Some(value) = outer_gateway_value(s) {
      out.push_str(&format!("  {}: {value};\n", s.prop));
    }
  }
  out.push_str("};\n\n");

  out.push_str("export type PartialBridgeMessageHandlers = {\n");
  for s in surfaces {
    if let Some(value) = outer_gateway_value(s) {
      let partial = partialize(&value);
      out.push_str(&format!("  {}?: {partial};\n", s.prop));
    }
  }
  out.push_str("};\n\n");

  out.push_str("export type BridgeMessageDeviceHandlers = {\n");
  for s in surfaces {
    if let Some(value) = outer_device_value(s) {
      out.push_str(&format!("  {}: {value};\n", s.prop));
    }
  }
  out.push_str("};\n\n");

  out.push_str("export type PartialBridgeMessageDeviceHandlers = {\n");
  for s in surfaces {
    if let Some(value) = outer_device_value(s) {
      let partial = partialize(&value);
      out.push_str(&format!("  {}?: {partial};\n", s.prop));
    }
  }
  out.push_str("};\n\n");
}

fn outer_gateway_value(s: &Surface) -> Option<String> {
  let has_event_inner = !s.inbound_event_variants().is_empty();
  let has_typed_req = !s.inbound_requests.is_empty();
  if !has_event_inner && !has_typed_req {
    return None;
  }
  if let Some(e) = &s.inbound
    && e.inner_variants.is_empty()
    && e.outer_payload.is_some()
    && !has_typed_req
  {
    let p = e.outer_payload.as_ref().map(|p| p.ts()).unwrap();
    return Some(format!("(deviceId: string, msg: {p}) => void"));
  }
  if !has_event_inner && s.inbound_requests.len() == 1 {
    let r = &s.inbound_requests[0];
    let payload_arg = if r.request_takes_payload {
      format!(", req: {}", r.request)
    } else {
      String::new()
    };
    return Some(format!(
      "(handle: {}Handle{payload_arg}) => Promise<void> | void",
      r.request
    ));
  }
  Some(format!("{}InboundHandlers", s.name))
}

fn outer_device_value(s: &Surface) -> Option<String> {
  let has_event_inner = !s.inbound_event_variants().is_empty();
  let has_typed_req = !s.inbound_requests.is_empty();
  if !has_event_inner && !has_typed_req {
    return None;
  }
  if let Some(e) = &s.inbound
    && e.inner_variants.is_empty()
    && e.outer_payload.is_some()
    && !has_typed_req
  {
    let p = e.outer_payload.as_ref().map(|p| p.ts()).unwrap();
    return Some(format!("(msg: {p}) => void"));
  }
  if !has_event_inner && s.inbound_requests.len() == 1 {
    let r = &s.inbound_requests[0];
    let payload_arg = if r.request_takes_payload {
      format!(", req: {}", r.request)
    } else {
      String::new()
    };
    return Some(format!(
      "(handle: {}Handle{payload_arg}) => Promise<void> | void",
      r.request
    ));
  }
  Some(format!("{}DeviceInboundHandlers", s.name))
}

fn partialize(ty: &str) -> String {
  if ty.starts_with('(') {
    ty.to_string()
  } else {
    format!("Partial<{ty}>")
  }
}

// ---------------------------------------------------------------------------
// Module augmentation
// ---------------------------------------------------------------------------

fn push_module_augmentation(out: &mut String, surfaces: &[Surface]) {
  out.push_str("declare module './index' {\n");
  out.push_str("  interface BridgethingGateway {\n");
  for s in surfaces {
    out.push_str(&format!(
      "    /** Methods scoped to the `{}` wire surface. */\n    readonly {}: {}Surface;\n",
      s.name, s.prop, s.name
    ));
  }
  out.push_str("    /** Returns a per-device proxy with `deviceId` baked into every method and listener. */\n");
  out.push_str("    device(deviceId: string): BridgethingGatewayDevice;\n");
  out.push_str("    /** Exhaustive subscribe across every inbound wire surface (cross-peer). */\n");
  out.push_str("    subscribe(handlers: BridgeMessageHandlers): () => void;\n");
  out.push_str("    subscribePartial(handlers: PartialBridgeMessageHandlers): () => void;\n");
  out.push_str("  }\n}\n\n");
}

// ---------------------------------------------------------------------------
// Per-request handle classes
// ---------------------------------------------------------------------------

fn push_request_handle_class(out: &mut String, r: &TypedRequestEntry) {
  out.push_str(&format!(
    "export class {}Handle {{\n  constructor(\n    private readonly _gateway: BridgethingGateway,\n    public readonly deviceId: string,\n    public readonly requestId: string,\n  ) {{}}\n\n",
    r.request
  ));
  out.push_str(&format!(
    "  async respond(response: {}): Promise<void> {{\n    const msg: GatewayToBridgeMsg = {{ id: newUuid(), meta: {{ kind: 'response', data: {{ requestId: this.requestId }} }}, data: {{ type: '{}', data: {{ {}: '{}', data: response }} }} }};\n    await this._gateway.send(this.deviceId, msg);\n  }}\n\n",
    r.response, r.surface_disc, r.inner_tag, r.response_disc
  ));
  if let (Some(err_type), Some(err_disc)) = (&r.error, &r.error_disc) {
    out.push_str(&format!(
      "  async respondErr(error: {err_type}): Promise<void> {{\n    const msg: GatewayToBridgeMsg = {{ id: newUuid(), meta: {{ kind: 'response', data: {{ requestId: this.requestId }} }}, data: {{ type: '{}', data: {{ {}: '{}', data: error }} }} }};\n    await this._gateway.send(this.deviceId, msg);\n  }}\n\n",
      r.surface_disc, r.inner_tag, err_disc
    ));
  }
  out.push_str("  async respondProtocolErr(error: WireError): Promise<void> {\n    const msg: GatewayToBridgeMsg = { id: newUuid(), meta: { kind: 'response', data: { requestId: this.requestId } }, data: { type: 'error', data: error } };\n    await this._gateway.send(this.deviceId, msg);\n  }\n");
  out.push_str("}\n\n");
}

// ---------------------------------------------------------------------------
// Device proxy class
// ---------------------------------------------------------------------------

fn push_device_proxy_class(out: &mut String, surfaces: &[Surface]) {
  out.push_str("type DeviceSurfaceCache = {\n");
  for s in surfaces {
    out.push_str(&format!("  {}?: {}SurfaceForDevice;\n", s.prop, s.name));
  }
  out.push_str("};\n\n");
  out.push_str("export class BridgethingGatewayDevice {\n");
  out.push_str(
    "  private readonly _surfaces: DeviceSurfaceCache = {};\n  constructor(\n    public readonly _gateway: BridgethingGateway,\n    public readonly deviceId: string,\n  ) {}\n\n",
  );
  for s in surfaces {
    out.push_str(&format!(
      "  get {}(): {}SurfaceForDevice {{\n    return (this._surfaces.{} ??= new {}SurfaceForDevice(this._gateway, this.deviceId));\n  }}\n",
      s.prop, s.name, s.prop, s.name
    ));
  }
  out.push_str(
    "\n  /** Exhaustive subscribe across every inbound wire surface from this peer. */\n  subscribe(handlers: BridgeMessageDeviceHandlers): () => void {\n    return outerSubscribeDevice(this._gateway, this.deviceId, handlers, false);\n  }\n  subscribePartial(handlers: PartialBridgeMessageDeviceHandlers): () => void {\n    return outerSubscribeDevice(this._gateway, this.deviceId, handlers, true);\n  }\n}\n\n",
  );
}

// ---------------------------------------------------------------------------
// applyDispatch runtime
// ---------------------------------------------------------------------------

fn push_apply_dispatch(out: &mut String, surfaces: &[Surface]) {
  out.push_str("type GatewaySurfaceCache = {\n");
  for s in surfaces {
    out.push_str(&format!("  {}?: {}Surface;\n", s.prop, s.name));
  }
  out.push_str("};\n\n");

  out.push_str("/**\n * Apply codegen-emitted prototype augmentations to BridgethingGateway.\n * Called once from `index.ts` after the class definition. Idempotent.\n */\nexport function applyDispatch(): void {\n");
  out.push_str("  const surfaceCache = new WeakMap<BridgethingGateway, GatewaySurfaceCache>();\n");
  out.push_str("  function bucketFor(g: BridgethingGateway): GatewaySurfaceCache {\n    let bucket = surfaceCache.get(g);\n    if (!bucket) { bucket = {}; surfaceCache.set(g, bucket); }\n    return bucket;\n  }\n\n");
  for s in surfaces {
    out.push_str(&format!(
      "  Object.defineProperty(BridgethingGateway.prototype, '{}', {{\n    configurable: true,\n    enumerable: true,\n    get(this: BridgethingGateway): {}Surface {{\n      const bucket = bucketFor(this);\n      return (bucket.{} ??= new {}Surface(this));\n    }},\n  }});\n",
      s.prop, s.name, s.prop, s.name
    ));
  }
  out.push('\n');

  out.push_str("  const deviceCache = new WeakMap<BridgethingGateway, Map<string, BridgethingGatewayDevice>>();\n");
  out.push_str("  BridgethingGateway.prototype.device = function (deviceId: string): BridgethingGatewayDevice {\n    let cache = deviceCache.get(this);\n    if (!cache) { cache = new Map(); deviceCache.set(this, cache); }\n    let proxy = cache.get(deviceId);\n    if (!proxy) { proxy = new BridgethingGatewayDevice(this, deviceId); cache.set(deviceId, proxy); }\n    return proxy;\n  };\n\n");

  out.push_str("  BridgethingGateway.prototype.subscribe = function (handlers: BridgeMessageHandlers): () => void {\n    return outerSubscribeGateway(this, handlers, false);\n  };\n");
  out.push_str("  BridgethingGateway.prototype.subscribePartial = function (handlers: PartialBridgeMessageHandlers): () => void {\n    return outerSubscribeGateway(this, handlers, true);\n  };\n");
  out.push_str("}\n\n");

  push_outer_subscribe_gateway(out, surfaces);
  push_outer_subscribe_device(out, surfaces);
}

fn push_outer_subscribe_gateway(out: &mut String, surfaces: &[Surface]) {
  out.push_str("function outerSubscribeGateway(g: BridgethingGateway, handlers: PartialBridgeMessageHandlers, partial: boolean): () => void {\n  return g.on((event: GatewayEvent) => {\n    if (event.type !== 'message') return;\n    const data = event.message.data;\n    switch (data.type) {\n");
  for s in surfaces {
    push_outer_case_gateway(out, s);
  }
  out.push_str("      default: {\n        if (!partial) g.logger.warn('subscribe: no handler for unknown wire variant', data);\n        return;\n      }\n    }\n  });\n}\n\n");
}

fn push_outer_case_gateway(out: &mut String, s: &Surface) {
  if outer_gateway_value(s).is_none() {
    return;
  }
  let prop = &s.prop;
  let leaf_only = s
    .inbound
    .as_ref()
    .map(|e| e.inner_variants.is_empty() && e.outer_payload.is_some())
    .unwrap_or(false);
  let has_typed_req = !s.inbound_requests.is_empty();
  let single_request_only = s.inbound_event_variants().is_empty() && s.inbound_requests.len() == 1;
  if leaf_only && !has_typed_req {
    out.push_str(&format!(
      "      case '{prop}': {{\n        const handler = handlers.{prop};\n        if (!handler) {{ if (!partial) g.logger.warn('subscribe: no handler for {prop}'); return; }}\n        handler(event.deviceId, data.data);\n        return;\n      }}\n"
    ));
    return;
  }
  if single_request_only {
    let r = &s.inbound_requests[0];
    let payload_pass = if r.request_takes_payload {
      ", data.data.data".to_string()
    } else {
      String::new()
    };
    out.push_str(&format!(
      "      case '{prop}': {{\n        if (event.message.meta.kind !== 'request') return;\n        const handler = handlers.{prop};\n        if (!handler) {{ if (!partial) g.logger.warn('subscribe: no handler for {prop}'); return; }}\n        const handle = new {}Handle(g, event.deviceId, event.message.id);\n        const result = handler(handle{payload_pass});\n        if (result && typeof result.then === 'function') result.catch((err: unknown) => g.logger.error('subscribe handler threw:', err));\n        return;\n      }}\n",
      r.request
    ));
    return;
  }
  let inner_tag = s
    .inbound
    .as_ref()
    .and_then(|e| e.inner_tag_field.as_deref())
    .unwrap_or("event");
  out.push_str(&format!(
    "      case '{prop}': {{\n        const innerHandlers = handlers.{prop};\n        if (!innerHandlers) {{ if (!partial) g.logger.warn('subscribe: no handler for {prop}'); return; }}\n        const inner = data.data;\n        switch (inner.{inner_tag}) {{\n"
  ));
  for iv in s.inbound_event_variants() {
    let invoke = match &iv.payload {
      Some(_) => format!("            innerHandlers.{}?.(event.deviceId, inner.data);", iv.disc),
      None => format!("            innerHandlers.{}?.(event.deviceId);", iv.disc),
    };
    out.push_str(&format!(
      "          case '{}': {{\n{invoke}\n            return;\n          }}\n",
      iv.disc
    ));
  }
  for r in &s.inbound_requests {
    let pass_payload = if r.request_takes_payload {
      ", inner.data".to_string()
    } else {
      String::new()
    };
    out.push_str(&format!(
      "          case '{}': {{\n            if (event.message.meta.kind !== 'request') return;\n            const handler = innerHandlers.{};\n            if (!handler) {{ if (!partial) g.logger.warn('{}: no handler for inner', '{}'); return; }}\n            const handle = new {}Handle(g, event.deviceId, event.message.id);\n            const result = handler(handle{pass_payload});\n            if (result && typeof result.then === 'function') result.catch((err: unknown) => g.logger.error('subscribe handler threw:', err));\n            return;\n          }}\n",
      r.request_disc, r.request_disc, s.name, r.request_disc, r.request
    ));
  }
  out.push_str(&format!(
    "          default: {{\n            if (!partial) g.logger.warn('{}: no handler for inner', inner);\n            return;\n          }}\n        }}\n      }}\n",
    s.name
  ));
}

fn push_outer_subscribe_device(out: &mut String, surfaces: &[Surface]) {
  out.push_str("function outerSubscribeDevice(g: BridgethingGateway, deviceId: string, handlers: PartialBridgeMessageDeviceHandlers, partial: boolean): () => void {\n  return g.on((event: GatewayEvent) => {\n    if (event.type !== 'message') return;\n    if (event.deviceId !== deviceId) return;\n    const data = event.message.data;\n    switch (data.type) {\n");
  for s in surfaces {
    push_outer_case_device(out, s);
  }
  out.push_str("      default: {\n        if (!partial) g.logger.warn('subscribe: no handler for unknown wire variant', data);\n        return;\n      }\n    }\n  });\n}\n\n");
}

fn push_outer_case_device(out: &mut String, s: &Surface) {
  if outer_device_value(s).is_none() {
    return;
  }
  let prop = &s.prop;
  let leaf_only = s
    .inbound
    .as_ref()
    .map(|e| e.inner_variants.is_empty() && e.outer_payload.is_some())
    .unwrap_or(false);
  let has_typed_req = !s.inbound_requests.is_empty();
  let single_request_only = s.inbound_event_variants().is_empty() && s.inbound_requests.len() == 1;
  if leaf_only && !has_typed_req {
    out.push_str(&format!(
      "      case '{prop}': {{\n        const handler = handlers.{prop};\n        if (!handler) {{ if (!partial) g.logger.warn('subscribe: no handler for {prop}'); return; }}\n        handler(data.data);\n        return;\n      }}\n"
    ));
    return;
  }
  if single_request_only {
    let r = &s.inbound_requests[0];
    let payload_pass = if r.request_takes_payload {
      ", data.data.data".to_string()
    } else {
      String::new()
    };
    out.push_str(&format!(
      "      case '{prop}': {{\n        if (event.message.meta.kind !== 'request') return;\n        const handler = handlers.{prop};\n        if (!handler) {{ if (!partial) g.logger.warn('subscribe: no handler for {prop}'); return; }}\n        const handle = new {}Handle(g, event.deviceId, event.message.id);\n        const result = handler(handle{payload_pass});\n        if (result && typeof result.then === 'function') result.catch((err: unknown) => g.logger.error('subscribe handler threw:', err));\n        return;\n      }}\n",
      r.request
    ));
    return;
  }
  let inner_tag = s
    .inbound
    .as_ref()
    .and_then(|e| e.inner_tag_field.as_deref())
    .unwrap_or("event");
  out.push_str(&format!(
    "      case '{prop}': {{\n        const innerHandlers = handlers.{prop};\n        if (!innerHandlers) {{ if (!partial) g.logger.warn('subscribe: no handler for {prop}'); return; }}\n        const inner = data.data;\n        switch (inner.{inner_tag}) {{\n"
  ));
  for iv in s.inbound_event_variants() {
    let invoke = match &iv.payload {
      Some(_) => format!("            innerHandlers.{}?.(inner.data);", iv.disc),
      None => format!("            innerHandlers.{}?.();", iv.disc),
    };
    out.push_str(&format!(
      "          case '{}': {{\n{invoke}\n            return;\n          }}\n",
      iv.disc
    ));
  }
  for r in &s.inbound_requests {
    let pass_payload = if r.request_takes_payload {
      ", inner.data".to_string()
    } else {
      String::new()
    };
    out.push_str(&format!(
      "          case '{}': {{\n            if (event.message.meta.kind !== 'request') return;\n            const handler = innerHandlers.{};\n            if (!handler) {{ if (!partial) g.logger.warn('{}: no handler for inner', '{}'); return; }}\n            const handle = new {}Handle(g, event.deviceId, event.message.id);\n            const result = handler(handle{pass_payload});\n            if (result && typeof result.then === 'function') result.catch((err: unknown) => g.logger.error('subscribe handler threw:', err));\n            return;\n          }}\n",
      r.request_disc, r.request_disc, s.name, r.request_disc, r.request
    ));
  }
  out.push_str(&format!(
    "          default: {{\n            if (!partial) g.logger.warn('{}: no handler for inner', inner);\n            return;\n          }}\n        }}\n      }}\n",
    s.name
  ));
}

// ---------------------------------------------------------------------------
// helpers
// ---------------------------------------------------------------------------

fn camel_first(s: &str) -> String {
  let mut chars = s.chars();
  let mut out = String::new();
  if let Some(c) = chars.next() {
    out.extend(c.to_lowercase());
  }
  out.extend(chars);
  out
}
