[package]
name = "bridgething-mfi-proxy"
version = "0.1.0"
edition = "2024"
rust-version = "1.85.0"

[[bin]]
name = "bridgething-mfi-proxy"
path = "src/main.rs"

[dependencies]
bridgething-mfi = { path = "../mfi", features = ["remote"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
