[package]
name = "bridgething"
version = "0.1.0"
edition = "2021"
rust-version = "1.82.0"

[dependencies]
bluer = { version = "0.17.3", features = ["bluetoothd", "l2cap"] }
futures = "0.3.31"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.132"
thiserror = "2.0.3"
tokio = { version = "1.41.1", features = ["full"] }
tokio-util = "0.7.12"
tokio-websockets = { version = "0.10.1", features = [
  "server",
  "simd",
  "sha1_smol",
] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }

# systemd feature
sd-notify = { version = "0.4.3", optional = true }
uuid = { version = "1.11.0", features = ["v7", "serde", "fast-rng"] }
serde_with = { version = "3.11.0", features = ["json"] }

# als feature


[features]
default = []
als = []
systemd = ["dep:sd-notify"]
superbird = ["als", "systemd"]

[[example]]
name = "mock-backend"
