[workspace]
resolver = "2"
members = ["core", "adapters/node", "lib", "client/rust"]

[workspace.dependencies]
serde = { version = "1.0.217" }
serde_json = { version = "1.0.138" }
uuid = { version = "1.13.1" }
serde_with = { version = "3.12.0" }
derive_more = { version = "1.0.0" }
bluer = { version = "0.17.3" }
futures = { version = "0.3.31" }
tokio = { version = "1.43.0" }
tokio-util = { version = "0.7.13" }
thiserror = { version = "2.0.11" }
tracing = { version = "0.1.41" }
tracing-subscriber = { version = "0.3.19" }
flate2 = { version = "1.0.35" }
async-trait = { version = "0.1.88" }

[profile.release]
lto = true
strip = "symbols"
