[package]
name = "bridgething-gateway"
rust-version.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
homepage.workspace = true

[dependencies]
bridgething-sdk-runtime = { path = "../sdk-runtime" }
libbridgething = { path = "../lib" }

tokio = { workspace = true, features = ["rt", "sync", "time", "macros"] }
tokio-util = { workspace = true, features = ["codec"] }
futures = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true, features = ["v7"] }
tokio-tungstenite = "0.29.0"
tokio-stream = { version = "0.1.18", features = ["sync"] }

[dev-dependencies]
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "time", "io-util"] }
