generatorName: kotlin
inputSpec: Sources/SpotifyOpenAPI/openapi.yaml
outputDir: ../../packages/spotify/kotlin
modelPackage: dev.bridgething.spotify.api.model
apiPackage: dev.bridgething.spotify.api
packageName: dev.bridgething.spotify.api
modelNamePrefix: ""
generateModelTests: false
generateModelDocumentation: false
generateApiTests: false
generateApiDocumentation: false
additionalProperties:
  library: jvm-ktor
  serializationLibrary: kotlinx_serialization
  enumPropertyNaming: original
  useCoroutines: "true"
  generateRoomModels: "false"
  omitGradleWrapper: "true"
  omitGradlePluginVersions: "true"
globalProperties:
  models: ""
  modelDocs: "false"
  apis: ""
  apiDocs: "false"
  supportingFiles: "false"
