query getShelfSection($id: String!, $limit: Int!, $offset: Int!) {
  section(id: $id, limit: $limit, offset: $offset) {
    ... on ShelfSection {
      id
      title
      children {
        uri
        title
        subtitle
        image_id: imageId
      }
      total
    }
    ... on SectionError {
      message
    }
  }
}
