[package]
edition = "2021"
name = "bridgething-adapter"
version = "0.0.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
libbridgething = { path = "../../lib" }

futures = { workspace = true }
tokio = { workspace = true, features = ["sync", "macros"] }
tokio-util = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
flate2 = { workspace = true }
async-trait = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

# feature-specific cross-platform dependencies (ble)
btleplug = { version = "0.12.0", features = ["serde"], optional = true }

# feature-specific platform-specific dependencies
[target.'cfg(target_os = "linux")'.dependencies]
bluer = { workspace = true, features = [
  "bluetoothd",
  "rfcomm",
], optional = true }

[target.'cfg(target_os = "windows")'.dependencies]
windows = { version = "0.62.2", features = [
  "Devices_Bluetooth",
  "Devices_Radios",
  "Foundation_Collections",
  "Foundation",
  "Storage_Streams",
], optional = true }
# base64 = { version = "0.22.1" }

[target.'cfg(target_os = "macos")'.dependencies]
# objc2 = { version = "0.5.2" }
# objc2-foundation = { version = "0.2.2", features = ["all"] }
# block2 = { version = "0.5.1" }
# core-foundation = { version = "0.10.0" }
# dispatch2 = { version = "0.1.0" }lea
# base64 = { version = "0.22.1" }

[features]
default = ["rfcomm"]
rfcomm = ["windows", "bluer"]
ble = ["btleplug"]


[dependencies.napi]
version = "3.8.5"
default-features = false
# see https://nodejs.org/api/n-api.html#node-api-version-matrix
features = ["napi4", "async", "serde-json"]

[dependencies.napi-derive]
version = "3.5.4"
features = ["type-def"]

[build-dependencies]
napi-build = "2"
