/*
 Generated by typeshare 1.13.4
 */

import Foundation

public struct Album: Codable {
	public let id: String
	public let name: String

	public init(id: String, name: String) {
		self.id = id
		self.name = name
	}
}

public struct Artist: Codable {
	public let id: String
	public let name: String

	public init(id: String, name: String) {
		self.id = id
		self.name = name
	}
}

public struct BridgeFile: Codable {
	public let path: String
	public let data: [UInt8]

	public init(path: String, data: [UInt8]) {
		self.path = path
		self.data = data
	}
}

public struct BridgeThingMeta: Codable {
	public let bridgethingVersion: String
	public let libbridgethingVersion: String
	public let appName: String
	public let appVersion: String
	public let osName: String
	public let osVersion: String
	public let osDescription: String
	public let btMac: String
	public let serialNumber: String
	public let fccId: String
	public let icId: String
	public let modelName: String
	public let imageBuildId: String
	public let imageBuildDate: String
	public let imageDistro: String
	public let imageDistroVersion: String
	public let imageMachine: String
	public let discord: String
	public let credits: String

	public init(bridgethingVersion: String, libbridgethingVersion: String, appName: String, appVersion: String, osName: String, osVersion: String, osDescription: String, btMac: String, serialNumber: String, fccId: String, icId: String, modelName: String, imageBuildId: String, imageBuildDate: String, imageDistro: String, imageDistroVersion: String, imageMachine: String, discord: String, credits: String) {
		self.bridgethingVersion = bridgethingVersion
		self.libbridgethingVersion = libbridgethingVersion
		self.appName = appName
		self.appVersion = appVersion
		self.osName = osName
		self.osVersion = osVersion
		self.osDescription = osDescription
		self.btMac = btMac
		self.serialNumber = serialNumber
		self.fccId = fccId
		self.icId = icId
		self.modelName = modelName
		self.imageBuildId = imageBuildId
		self.imageBuildDate = imageBuildDate
		self.imageDistro = imageDistro
		self.imageDistroVersion = imageDistroVersion
		self.imageMachine = imageMachine
		self.discord = discord
		self.credits = credits
	}
}

public enum GatewayMsgMeta: Codable {
	case command
	case event
	case request
	case response(ResponseMeta)

	enum CodingKeys: String, CodingKey, Codable {
		case command,
			event,
			request,
			response
	}

	private enum ContainerCodingKeys: String, CodingKey {
		case kind, data
	}

	public init(from decoder: Decoder) throws {
		let container = try decoder.container(keyedBy: ContainerCodingKeys.self)
		if let type = try? container.decode(CodingKeys.self, forKey: .kind) {
			switch type {
			case .command:
				self = .command
				return
			case .event:
				self = .event
				return
			case .request:
				self = .request
				return
			case .response:
				if let content = try? container.decode(ResponseMeta.self, forKey: .data) {
					self = .response(content)
					return
				}
			}
		}
		throw DecodingError.typeMismatch(GatewayMsgMeta.self, DecodingError.Context(codingPath: decoder.codingPath, debugDescription: "Wrong type for GatewayMsgMeta"))
	}

	public func encode(to encoder: Encoder) throws {
		var container = encoder.container(keyedBy: ContainerCodingKeys.self)
		switch self {
		case .command:
			try container.encode(CodingKeys.command, forKey: .kind)
		case .event:
			try container.encode(CodingKeys.event, forKey: .kind)
		case .request:
			try container.encode(CodingKeys.request, forKey: .kind)
		case .response(let content):
			try container.encode(CodingKeys.response, forKey: .kind)
			try container.encode(content, forKey: .data)
		}
	}
}

public enum BridgeToGatewayMsgData: Codable {
	case version(BridgeThingMeta)
	case file(BridgeToGatewayFileMsg)
	case forward(ForwardMessage)
	case ack
	case done

	enum CodingKeys: String, CodingKey, Codable {
		case version,
			file,
			forward,
			ack,
			done
	}

	private enum ContainerCodingKeys: String, CodingKey {
		case type, data
	}

	public init(from decoder: Decoder) throws {
		let container = try decoder.container(keyedBy: ContainerCodingKeys.self)
		if let type = try? container.decode(CodingKeys.self, forKey: .type) {
			switch type {
			case .version:
				if let content = try? container.decode(BridgeThingMeta.self, forKey: .data) {
					self = .version(content)
					return
				}
			case .file:
				if let content = try? container.decode(BridgeToGatewayFileMsg.self, forKey: .data) {
					self = .file(content)
					return
				}
			case .forward:
				if let content = try? container.decode(ForwardMessage.self, forKey: .data) {
					self = .forward(content)
					return
				}
			case .ack:
				self = .ack
				return
			case .done:
				self = .done
				return
			}
		}
		throw DecodingError.typeMismatch(BridgeToGatewayMsgData.self, DecodingError.Context(codingPath: decoder.codingPath, debugDescription: "Wrong type for BridgeToGatewayMsgData"))
	}

	public func encode(to encoder: Encoder) throws {
		var container = encoder.container(keyedBy: ContainerCodingKeys.self)
		switch self {
		case .version(let content):
			try container.encode(CodingKeys.version, forKey: .type)
			try container.encode(content, forKey: .data)
		case .file(let content):
			try container.encode(CodingKeys.file, forKey: .type)
			try container.encode(content, forKey: .data)
		case .forward(let content):
			try container.encode(CodingKeys.forward, forKey: .type)
			try container.encode(content, forKey: .data)
		case .ack:
			try container.encode(CodingKeys.ack, forKey: .type)
		case .done:
			try container.encode(CodingKeys.done, forKey: .type)
		}
	}
}

/// bridgething -> gateway
/// messages from bridgething to the gateway (mobile or desktop app).
/// 
/// these messages will pass over bluetooth.
public struct BridgeToGatewayMsg: Codable {
	public let id: String
	public let meta: GatewayMsgMeta
	public let data: BridgeToGatewayMsgData

	public init(id: String, meta: GatewayMsgMeta, data: BridgeToGatewayMsgData) {
		self.id = id
		self.meta = meta
		self.data = data
	}
}

public struct ChromeNavigate: Codable {
	public let url: String

	public init(url: String) {
		self.url = url
	}
}

public struct FileAdd: Codable {
	public let files: [BridgeFile]

	public init(files: [BridgeFile]) {
		self.files = files
	}
}

public struct FileDelete: Codable {
	public let files: [String]

	public init(files: [String]) {
		self.files = files
	}
}

public struct FileList: Codable {
	public let files: [String]

	public init(files: [String]) {
		self.files = files
	}
}

public struct FileRequestData: Codable {
	public let file: String

	public init(file: String) {
		self.file = file
	}
}

public struct FileResponseData: Codable {
	public let file: BridgeFile

	public init(file: BridgeFile) {
		self.file = file
	}
}

public struct GatewayMeta: Codable {
	public let adapterVersion: String
	public let libVersion: String
	public let libbridgethingVersion: String
	public let appName: String
	public let appVersion: String
	public let osName: String

	public init(adapterVersion: String, libVersion: String, libbridgethingVersion: String, appName: String, appVersion: String, osName: String) {
		self.adapterVersion = adapterVersion
		self.libVersion = libVersion
		self.libbridgethingVersion = libbridgethingVersion
		self.appName = appName
		self.appVersion = appVersion
		self.osName = osName
	}
}

public enum GatewayToBridgeMsgData: Codable {
	case version(GatewayMeta)
	case file(GatewayToBridgeFileMsg)
	case chrome(GatewayToBridgeChromeMsg)
	case forward(ForwardMessage)

	enum CodingKeys: String, CodingKey, Codable {
		case version,
			file,
			chrome,
			forward
	}

	private enum ContainerCodingKeys: String, CodingKey {
		case type, data
	}

	public init(from decoder: Decoder) throws {
		let container = try decoder.container(keyedBy: ContainerCodingKeys.self)
		if let type = try? container.decode(CodingKeys.self, forKey: .type) {
			switch type {
			case .version:
				if let content = try? container.decode(GatewayMeta.self, forKey: .data) {
					self = .version(content)
					return
				}
			case .file:
				if let content = try? container.decode(GatewayToBridgeFileMsg.self, forKey: .data) {
					self = .file(content)
					return
				}
			case .chrome:
				if let content = try? container.decode(GatewayToBridgeChromeMsg.self, forKey: .data) {
					self = .chrome(content)
					return
				}
			case .forward:
				if let content = try? container.decode(ForwardMessage.self, forKey: .data) {
					self = .forward(content)
					return
				}
			}
		}
		throw DecodingError.typeMismatch(GatewayToBridgeMsgData.self, DecodingError.Context(codingPath: decoder.codingPath, debugDescription: "Wrong type for GatewayToBridgeMsgData"))
	}

	public func encode(to encoder: Encoder) throws {
		var container = encoder.container(keyedBy: ContainerCodingKeys.self)
		switch self {
		case .version(let content):
			try container.encode(CodingKeys.version, forKey: .type)
			try container.encode(content, forKey: .data)
		case .file(let content):
			try container.encode(CodingKeys.file, forKey: .type)
			try container.encode(content, forKey: .data)
		case .chrome(let content):
			try container.encode(CodingKeys.chrome, forKey: .type)
			try container.encode(content, forKey: .data)
		case .forward(let content):
			try container.encode(CodingKeys.forward, forKey: .type)
			try container.encode(content, forKey: .data)
		}
	}
}

/// gateway -> bridgething
/// messages from the gateway (mobile or desktop app) to bridgething.
/// 
/// these messages will pass over bluetooth.
public struct GatewayToBridgeMsg: Codable {
	public let id: String
	public let meta: GatewayMsgMeta
	public let data: GatewayToBridgeMsgData

	public init(id: String, meta: GatewayMsgMeta, data: GatewayToBridgeMsgData) {
		self.id = id
		self.meta = meta
		self.data = data
	}
}

public struct PlaybackOptions: Codable {
	public let `repeat`: UInt32
	public let shuffle: Bool

	public init(repeat: UInt32, shuffle: Bool) {
		self.repeat = `repeat`
		self.shuffle = shuffle
	}
}

public struct ResponseMeta: Codable {
	public let requestId: String

	public init(requestId: String) {
		self.requestId = requestId
	}
}

public struct Track: Codable {
	public let id: String
	public let name: String
	public let album: Album
	public let artist: Artist
	public let artists: [Artist]
	public let duration_ms: UInt32
	public let image_id: String
	public let saved: Bool

	public init(id: String, name: String, album: Album, artist: Artist, artists: [Artist], duration_ms: UInt32, image_id: String, saved: Bool) {
		self.id = id
		self.name = name
		self.album = album
		self.artist = artist
		self.artists = artists
		self.duration_ms = duration_ms
		self.image_id = image_id
		self.saved = saved
	}
}

public enum BridgeToGatewayFileMsg: Codable {
	case files(FileList)
	/// fileRequest occurs when a file is requested over http that is not known to the bridge
	case fileRequest(FileRequestData)

	enum CodingKeys: String, CodingKey, Codable {
		case files,
			fileRequest
	}

	private enum ContainerCodingKeys: String, CodingKey {
		case event, data
	}

	public init(from decoder: Decoder) throws {
		let container = try decoder.container(keyedBy: ContainerCodingKeys.self)
		if let type = try? container.decode(CodingKeys.self, forKey: .event) {
			switch type {
			case .files:
				if let content = try? container.decode(FileList.self, forKey: .data) {
					self = .files(content)
					return
				}
			case .fileRequest:
				if let content = try? container.decode(FileRequestData.self, forKey: .data) {
					self = .fileRequest(content)
					return
				}
			}
		}
		throw DecodingError.typeMismatch(BridgeToGatewayFileMsg.self, DecodingError.Context(codingPath: decoder.codingPath, debugDescription: "Wrong type for BridgeToGatewayFileMsg"))
	}

	public func encode(to encoder: Encoder) throws {
		var container = encoder.container(keyedBy: ContainerCodingKeys.self)
		switch self {
		case .files(let content):
			try container.encode(CodingKeys.files, forKey: .event)
			try container.encode(content, forKey: .data)
		case .fileRequest(let content):
			try container.encode(CodingKeys.fileRequest, forKey: .event)
			try container.encode(content, forKey: .data)
		}
	}
}

public enum ForwardMessage: Codable {
	case text(String)
	case json(Value)
	case binary([UInt8])

	enum CodingKeys: String, CodingKey, Codable {
		case text,
			json,
			binary
	}

	private enum ContainerCodingKeys: String, CodingKey {
		case encoding, data
	}

	public init(from decoder: Decoder) throws {
		let container = try decoder.container(keyedBy: ContainerCodingKeys.self)
		if let type = try? container.decode(CodingKeys.self, forKey: .encoding) {
			switch type {
			case .text:
				if let content = try? container.decode(String.self, forKey: .data) {
					self = .text(content)
					return
				}
			case .json:
				if let content = try? container.decode(Value.self, forKey: .data) {
					self = .json(content)
					return
				}
			case .binary:
				if let content = try? container.decode([UInt8].self, forKey: .data) {
					self = .binary(content)
					return
				}
			}
		}
		throw DecodingError.typeMismatch(ForwardMessage.self, DecodingError.Context(codingPath: decoder.codingPath, debugDescription: "Wrong type for ForwardMessage"))
	}

	public func encode(to encoder: Encoder) throws {
		var container = encoder.container(keyedBy: ContainerCodingKeys.self)
		switch self {
		case .text(let content):
			try container.encode(CodingKeys.text, forKey: .encoding)
			try container.encode(content, forKey: .data)
		case .json(let content):
			try container.encode(CodingKeys.json, forKey: .encoding)
			try container.encode(content, forKey: .data)
		case .binary(let content):
			try container.encode(CodingKeys.binary, forKey: .encoding)
			try container.encode(content, forKey: .data)
		}
	}
}

public enum GatewayToBridgeChromeMsg: Codable {
	case navigate(ChromeNavigate)

	enum CodingKeys: String, CodingKey, Codable {
		case navigate
	}

	private enum ContainerCodingKeys: String, CodingKey {
		case event, data
	}

	public init(from decoder: Decoder) throws {
		let container = try decoder.container(keyedBy: ContainerCodingKeys.self)
		if let type = try? container.decode(CodingKeys.self, forKey: .event) {
			switch type {
			case .navigate:
				if let content = try? container.decode(ChromeNavigate.self, forKey: .data) {
					self = .navigate(content)
					return
				}
			}
		}
		throw DecodingError.typeMismatch(GatewayToBridgeChromeMsg.self, DecodingError.Context(codingPath: decoder.codingPath, debugDescription: "Wrong type for GatewayToBridgeChromeMsg"))
	}

	public func encode(to encoder: Encoder) throws {
		var container = encoder.container(keyedBy: ContainerCodingKeys.self)
		switch self {
		case .navigate(let content):
			try container.encode(CodingKeys.navigate, forKey: .event)
			try container.encode(content, forKey: .data)
		}
	}
}

public enum GatewayToBridgeFileMsg: Codable {
	case list
	case delete(FileDelete)
	case add(FileAdd)
	/// fileResponse is a response to the fileRequest, which occurs when a file is requested over http that is not known
	/// to the bridge. a fileResponse within a timely matter will be served to the client over http instead of 404'ing
	case fileResponse(FileResponseData)

	enum CodingKeys: String, CodingKey, Codable {
		case list,
			delete,
			add,
			fileResponse
	}

	private enum ContainerCodingKeys: String, CodingKey {
		case event, data
	}

	public init(from decoder: Decoder) throws {
		let container = try decoder.container(keyedBy: ContainerCodingKeys.self)
		if let type = try? container.decode(CodingKeys.self, forKey: .event) {
			switch type {
			case .list:
				self = .list
				return
			case .delete:
				if let content = try? container.decode(FileDelete.self, forKey: .data) {
					self = .delete(content)
					return
				}
			case .add:
				if let content = try? container.decode(FileAdd.self, forKey: .data) {
					self = .add(content)
					return
				}
			case .fileResponse:
				if let content = try? container.decode(FileResponseData.self, forKey: .data) {
					self = .fileResponse(content)
					return
				}
			}
		}
		throw DecodingError.typeMismatch(GatewayToBridgeFileMsg.self, DecodingError.Context(codingPath: decoder.codingPath, debugDescription: "Wrong type for GatewayToBridgeFileMsg"))
	}

	public func encode(to encoder: Encoder) throws {
		var container = encoder.container(keyedBy: ContainerCodingKeys.self)
		switch self {
		case .list:
			try container.encode(CodingKeys.list, forKey: .event)
		case .delete(let content):
			try container.encode(CodingKeys.delete, forKey: .event)
			try container.encode(content, forKey: .data)
		case .add(let content):
			try container.encode(CodingKeys.add, forKey: .event)
			try container.encode(content, forKey: .data)
		case .fileResponse(let content):
			try container.encode(CodingKeys.fileResponse, forKey: .event)
			try container.encode(content, forKey: .data)
		}
	}
}

public enum Image: Codable {
	case id(String)
	case bytes([UInt8])

	enum CodingKeys: String, CodingKey, Codable {
		case id,
			bytes
	}

	private enum ContainerCodingKeys: String, CodingKey {
		case type, data
	}

	public init(from decoder: Decoder) throws {
		let container = try decoder.container(keyedBy: ContainerCodingKeys.self)
		if let type = try? container.decode(CodingKeys.self, forKey: .type) {
			switch type {
			case .id:
				if let content = try? container.decode(String.self, forKey: .data) {
					self = .id(content)
					return
				}
			case .bytes:
				if let content = try? container.decode([UInt8].self, forKey: .data) {
					self = .bytes(content)
					return
				}
			}
		}
		throw DecodingError.typeMismatch(Image.self, DecodingError.Context(codingPath: decoder.codingPath, debugDescription: "Wrong type for Image"))
	}

	public func encode(to encoder: Encoder) throws {
		var container = encoder.container(keyedBy: ContainerCodingKeys.self)
		switch self {
		case .id(let content):
			try container.encode(CodingKeys.id, forKey: .type)
			try container.encode(content, forKey: .data)
		case .bytes(let content):
			try container.encode(CodingKeys.bytes, forKey: .type)
			try container.encode(content, forKey: .data)
		}
	}
}

public enum PhoneCallDirection: String, Codable {
	case incoming = "Incoming"
	case outgoing = "Outgoing"
}

public enum PhoneCallStatus: String, Codable {
	case disconnected = "Disconnected"
	case sending = "Sending"
	case ringing = "Ringing"
	case connecting = "Connecting"
	case active = "Active"
	case held = "Held"
	case disconnecting = "Disconnecting"
}
