[package]
name = "bridgething"
version = "0.1.0"
edition = "2021"
rust-version = "1.82.0"
default-run = "bridgething"

[dependencies]
libbridgething = { path = "../lib" }

# workspace dependencies
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
uuid = { workspace = true, features = ["v7", "serde", "fast-rng"] }
serde_with = { workspace = true, features = ["json"] }
derive_more = { workspace = true, features = ["debug"] }
bluer = { workspace = true, features = ["bluetoothd", "l2cap"] }
futures = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tokio-util = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }

# systemd feature
sd-notify = { version = "0.4.4", optional = true }

# als feature

# mic feature

# dependencies
tokio-websockets = { version = "0.10.1", features = [
  "server",
  "simd",
  "sha1_smol",
] }
dirs = "5.0.1"
bincode = "1.3.3"
zbus = { version = "5.3.0", default-features = false, features = ["tokio"] }
rmp = "0.8.14"
rmp-serde = "1.3.0"
quick_cache = "0.6.9"
dashmap = "6.1.0"
base64 = "0.22.1"
ahash = "0.8.11"


[features]
default = []
als = []
mic = []
systemd = ["dep:sd-notify"]
superbird = ["als", "mic", "systemd"]

[[example]]
name = "cover_art"
path = "./examples/cover_art.rs"
