// @generated by tools/codegen - do not edit. Run `just codegen` to regenerate.

/**
 * Field names whose Rust type is `Uuid`. Both wire codecs walk decoded
 * payloads and convert at these keys: msgpack 16-byte `bin` ↔ uuid string
 * on the gateway path; the daemon already speaks uuid strings on JSON.
 */
export const UUID_FIELD_NAMES: ReadonlySet<string> = new Set([
  'connectionId',
  'id',
  'requestId',
  'streamId',
  'tunnelId',
]);
