use std::{
  collections::{BTreeMap, BTreeSet},
  path::{Path, PathBuf},
  process::Command,
};

use anyhow::{Context, Result, anyhow, bail};
use syn::{Item, Meta};

mod dispatch;

const TS_BINDINGS_DIR: &str = "crates/lib/ts/bindings";
const TS_UUID_FIELDS_OUTPUT: &str = "crates/lib/ts/uuid-fields.generated.ts";
const SWIFT_OUTPUT: &str = "crates/lib/swift/Sources/BridgethingSchema/Generated.swift";
const KOTLIN_OUTPUT: &str = "crates/lib/kotlin/schema/src/main/kotlin/dev/bridgething/schema/Generated.kt";
const KOTLIN_PACKAGE: &str = "dev.bridgething.schema";
const LIB_SRC: &str = "crates/lib/src";

fn workspace_root() -> PathBuf {
  Path::new(env!("CARGO_MANIFEST_DIR"))
    .join("../..")
    .canonicalize()
    .expect("workspace root resolves")
}

fn main() -> Result<()> {
  let args: Vec<String> = std::env::args().skip(1).collect();
  let target = args.first().map(String::as_str).unwrap_or("all");

  std::env::set_current_dir(workspace_root()).context("cd to workspace root")?;

  match target {
    "ts" | "typescript" => gen_typescript()?,
    "swift" => gen_swift()?,
    "kotlin" => gen_kotlin()?,
    "all" => {
      gen_typescript()?;
      gen_swift()?;
      gen_kotlin()?;
    }
    other => bail!("unknown target {other:?}; expected one of: ts, swift, kotlin, all"),
  }
  Ok(())
}

fn gen_typescript() -> Result<()> {
  println!("==> typescript");
  if Path::new(TS_BINDINGS_DIR).exists() {
    std::fs::remove_dir_all(TS_BINDINGS_DIR).context("clear ts/bindings")?;
  }
  run("cargo", &["test", "-p", "libbridgething", "--quiet"])?;
  run("bunx", &["prettier", TS_BINDINGS_DIR, "--write", "--log-level", "warn"])?;

  println!("    emitting ts dispatch helpers");
  let inv = dispatch::inventory(LIB_SRC).context("dispatch inventory")?;
  println!(
    "    dispatch inventory: {} marker-tagged types, {} typed-request decls, {} uuid fields",
    inv.markers.len(),
    inv.typed_requests.len(),
    inv.uuid_field_names.len(),
  );
  let plans = dispatch::build_plans(&inv).context("dispatch plans")?;
  let binding_locations = scan_binding_type_locations(TS_BINDINGS_DIR).context("scan ts bindings")?;
  for plan in &plans {
    match plan.protocol {
      dispatch::Protocol::Gateway => {
        dispatch::emit_typescript(plan, &binding_locations).context("emit gateway typescript dispatch")?
      }
      dispatch::Protocol::Client => {
        dispatch::emit_typescript_client(plan, &binding_locations).context("emit client typescript dispatch")?
      }
    }
  }
  emit_ts_uuid_fields(&inv.uuid_field_names).context("emit ts uuid fields")?;
  run(
    "bunx",
    &[
      "prettier",
      "packages/gateway/typescript/src/dispatch.generated.ts",
      "packages/client-ts/src/dispatch.generated.ts",
      TS_UUID_FIELDS_OUTPUT,
      "--write",
      "--log-level",
      "warn",
    ],
  )?;
  Ok(())
}

/// Scan `ts/bindings/*.ts` and build a `name -> {files}` map (`AssetGet
/// -> {"client.ts"}`, `Priority -> {"shared.ts"}`, `WebappError ->
/// {"client.ts", "gateway.ts"}` for the genuinely-distinct case). The
/// dispatch emitters consult this to route per-type imports into the
/// right `@bridgething/lib` subpath, preferring the protocol-matching
/// file when a name is defined in both client.ts and gateway.ts.
fn scan_binding_type_locations(dir: &str) -> Result<BTreeMap<String, BTreeSet<String>>> {
  let mut map: BTreeMap<String, BTreeSet<String>> = BTreeMap::new();
  for entry in std::fs::read_dir(dir).with_context(|| format!("read_dir {dir}"))? {
    let entry = entry?;
    let path = entry.path();
    if path.extension().and_then(|s| s.to_str()) != Some("ts") {
      continue;
    }
    let file_name = path
      .file_name()
      .and_then(|s| s.to_str())
      .unwrap_or_default()
      .to_string();
    let content = std::fs::read_to_string(&path).with_context(|| format!("read {}", path.display()))?;
    for line in content.lines() {
      let trimmed = line.trim_start();
      let prefix = "export type ";
      if let Some(rest) = trimmed.strip_prefix(prefix) {
        let name: String = rest.chars().take_while(|c| c.is_ascii_alphanumeric() || *c == '_').collect();
        if !name.is_empty() {
          map.entry(name).or_default().insert(file_name.clone());
        }
      }
    }
  }
  Ok(map)
}

fn emit_ts_uuid_fields(names: &BTreeSet<String>) -> Result<()> {
  let mut out = String::new();
  out.push_str("// @generated by tools/codegen - do not edit. Run `just codegen` to regenerate.\n\n");
  out.push_str("/**\n");
  out.push_str(" * Field names whose Rust type is `Uuid`. Both wire codecs walk decoded\n");
  out.push_str(" * payloads and convert at these keys: msgpack 16-byte `bin` ↔ uuid string\n");
  out.push_str(" * on the gateway path; the daemon already speaks uuid strings on JSON.\n");
  out.push_str(" */\n");
  out.push_str("export const UUID_FIELD_NAMES: ReadonlySet<string> = new Set([\n");
  for name in names {
    out.push_str(&format!("  '{name}',\n"));
  }
  out.push_str("]);\n");
  std::fs::write(TS_UUID_FIELDS_OUTPUT, out).context("write uuid-fields.generated.ts")?;
  Ok(())
}

fn gen_swift() -> Result<()> {
  println!("==> swift");
  run("typeshare", &["--lang=swift", "--output-file", SWIFT_OUTPUT, LIB_SRC])?;

  let inv = dispatch::inventory(LIB_SRC).context("dispatch inventory")?;
  let content = std::fs::read_to_string(SWIFT_OUTPUT).context("read swift output")?;
  let patched = patch_swift(&content, &inv.uuid_field_names);
  std::fs::write(SWIFT_OUTPUT, patched).context("write swift output")?;

  println!("    emitting swift dispatch helpers");
  let plan = dispatch::build_plan_for(&inv, dispatch::Protocol::Gateway).context("dispatch plan")?;
  dispatch::emit_swift(&plan).context("emit swift dispatch")?;
  Ok(())
}

fn gen_kotlin() -> Result<()> {
  println!("==> kotlin");
  run(
    "typeshare",
    &[
      "--lang=kotlin",
      &format!("--java-package={KOTLIN_PACKAGE}"),
      "--output-file",
      KOTLIN_OUTPUT,
      LIB_SRC,
    ],
  )?;

  let adjacent_tagged =
    discover_adjacent_tagged_enums(LIB_SRC).context("discover adjacent-tagged enums in crates/lib/src")?;
  println!(
    "    discovered {} adjacent-tagged enum(s): {}",
    adjacent_tagged.len(),
    adjacent_tagged
      .iter()
      .map(|e| e.name.as_str())
      .collect::<Vec<_>>()
      .join(", ")
  );

  let inv = dispatch::inventory(LIB_SRC).context("dispatch inventory")?;
  let content = std::fs::read_to_string(KOTLIN_OUTPUT).context("read kotlin output")?;
  let patched = patch_kotlin(&content, &adjacent_tagged, &inv.uuid_field_names)?;
  std::fs::write(KOTLIN_OUTPUT, patched).context("write kotlin output")?;

  emit_kotlin_serializers(&adjacent_tagged).context("emit kotlin serializers")?;

  println!("    emitting kotlin dispatch helpers");
  let plan = dispatch::build_plan_for(&inv, dispatch::Protocol::Gateway).context("dispatch plan")?;
  dispatch::emit_kotlin(&plan).context("emit kotlin dispatch")?;
  Ok(())
}

fn emit_kotlin_serializers(enums: &[AdjacentTaggedEnum]) -> Result<()> {
  let path = "crates/lib/kotlin/schema/src/main/kotlin/dev/bridgething/schema/Serializers.kt";
  let mut out = String::new();
  out.push_str("// @generated by tools/codegen - do not edit. Run `just codegen` to regenerate.\n");
  out.push_str("package dev.bridgething.schema\n\n");
  out.push_str("import kotlinx.serialization.KSerializer\n\n");
  out.push_str(
    "/**\n * Per-class adjacent-tagged serializers, one per multi-discriminator sealed\n * class in the schema. `patch_kotlin` annotates each affected sealed class\n * with `@Serializable(with = ...)` so kotlinx-serialization picks these up\n * regardless of format (msgpack, json, ...).\n */\n",
  );
  for e in enums {
    out.push_str(&format!(
      "\npublic object {name}Serializer :\n  KSerializer<{name}> by AdjacentTaggedSerializer({name}::class, discriminator = \"{tag}\")\n",
      name = e.name,
      tag = e.tag,
    ));
  }
  std::fs::write(path, out).with_context(|| format!("write {path}"))?;
  Ok(())
}

fn patch_swift(input: &str, uuid_field_names: &BTreeSet<String>) -> String {
  // typeshare emits `[UInt8]` for `Vec<u8>`. Swift's Codable plus every
  // msgpack lib distinguishes Data (encodes as msgpack bin) from
  // [UInt8] (encodes as an array of int). Our wire is bin.
  let mut out = input.replace("[UInt8]", "Data");
  // Generated structs travel through actor-isolated stream events on
  // the gateway side; Swift 6 strict concurrency requires Sendable.
  // Every typeshare-emitted type is a value type whose stored fields
  // are already Sendable, so adding the conformance blanket is safe.
  out = out.replace(": Codable {", ": Codable, Sendable {");
  out = out.replace(": String, Codable {", ": String, Codable, Sendable {");

  // Surface UUID-typed fields as `Foundation.UUID` instead of raw
  // `Data`, with `@MsgpackUuid` bridging the 16-byte msgpack bin via a
  // Codable property wrapper. Field names come from the codegen-emitted
  // set; only `Uuid`-Rust-typed fields are rewritten. Optional UUID
  // fields (Rust `Option<Uuid>`) become `UUID?` and use a sibling
  // `@OptionalMsgpackUuid` wrapper so the underlying `Data?` shape on
  // the wire decodes correctly.
  for name in uuid_field_names {
    let n = regex::escape(name);
    let param = regex::Regex::new(&format!(r"\b{n}: Data\b")).expect("uuid param regex");
    out = param.replace_all(&out, format!("{name}: UUID")).into_owned();
    let optional_field =
      regex::Regex::new(&format!(r"(?m)^\tpublic let {n}: UUID\?$")).expect("uuid optional field regex");
    out = optional_field
      .replace_all(&out, format!("\t@OptionalMsgpackUuid public var {name}: UUID?"))
      .into_owned();
    let field = regex::Regex::new(&format!(r"(?m)^\tpublic let {n}: UUID$")).expect("uuid field regex");
    out = field
      .replace_all(&out, format!("\t@MsgpackUuid public var {name}: UUID"))
      .into_owned();
  }

  out
}

fn patch_kotlin_uuid_imports(input: &str) -> String {
  let needle = "import kotlinx.serialization.SerialName\n";
  if !input.contains(needle) || input.contains("import java.util.UUID\n") {
    return input.to_string();
  }
  let inserted = format!("{needle}import java.util.UUID\n");
  input.replacen(needle, &inserted, 1)
}

fn patch_kotlin(
  input: &str,
  adjacent_tagged: &[AdjacentTaggedEnum],
  uuid_field_names: &BTreeSet<String>,
) -> Result<String> {
  // typeshare emits `List<UByte>` for `Vec<u8>`. kotlinx-msgpack
  // encodes ByteArray as msgpack bin, but List<UByte> as an array of
  // ints. Our wire is bin.
  let mut out = input.replace("List<UByte>", "ByteArray");

  // Surface UUID-typed fields as `java.util.UUID` instead of raw
  // `ByteArray`, with `MsgpackUuidSerializer` bridging the 16-byte
  // msgpack bin. Field names come from the codegen-emitted set; only
  // those with `Uuid` Rust type are rewritten.
  out = patch_kotlin_uuid_imports(&out);
  let uuid_field = regex::Regex::new(r"(?m)^(\t)val (\w+): ByteArray(,?)$")?;
  out = uuid_field
    .replace_all(&out, |caps: &regex::Captures| {
      let indent = &caps[1];
      let name = &caps[2];
      let comma = &caps[3];
      if uuid_field_names.contains(name) {
        format!("{indent}@Serializable(with = MsgpackUuidSerializer::class) val {name}: UUID{comma}")
      } else {
        format!("{indent}val {name}: ByteArray{comma}")
      }
    })
    .into_owned();

  // For every adjacent-tagged enum (`#[serde(tag, content)]`), typeshare
  // emits a sealed class. kotlinx's default polymorphism for binary
  // formats sibling-inlines the discriminator into the parent map; the
  // bridgething wire shape is a nested `{<disc>: "tag", "data": payload}`
  // object. The `XSerializer` proxies in Serializers.kt produce that
  // shape, but only when the sealed class is annotated to use them.
  for e in adjacent_tagged {
    let name = &e.name;
    let pattern = regex::Regex::new(&format!(r"(?m)^@Serializable\nsealed class {}\b", regex::escape(name)))?;
    let replacement = format!("@Serializable(with = {name}Serializer::class)\nsealed class {name}");
    let new_out = pattern.replace_all(&out, replacement.as_str()).into_owned();
    if new_out == out {
      eprintln!(
        "    warning: adjacent-tagged enum {name} found in crates/lib/src but not in kotlin output (unreachable from any #[typeshare]'d root, or typeshare's emitted shape changed)"
      );
    }
    out = new_out;
  }

  // ForwardMessage::Json carries an arbitrary `serde_json::Value`.
  // kotlinx's default JsonElement serializer only works with
  // JsonDecoder. UniversalValueSerializer dispatches on encoder/decoder
  // type so the variant round-trips over msgpack as well.
  let json_pattern = "data class Json(val data: Value)";
  let json_replacement = "data class Json(@Serializable(with = UniversalValueSerializer::class) val data: Value)";
  if !out.contains(json_pattern) {
    return Err(anyhow!(
      "kotlin output is missing expected `{json_pattern}`; ForwardMessage shape may have changed"
    ));
  }
  out = out.replace(json_pattern, json_replacement);

  // Kotlin scopes the variant's name above its sibling sealed-class
  // peers, so `data class WebappError(val data: WebappError)` makes the
  // inner type recursively resolve to the variant itself instead of the
  // package-level `WebappError` sealed class. Fully-qualify any
  // self-shadowing variant payload so it points at the outer type.
  // Match `data class X(val data: Y):` and rewrite when X == Y.
  let self_shadow = regex::Regex::new(r"(?m)^(\tdata class (\w+)\(val data: )(\w+)(\): )")?;
  out = self_shadow
    .replace_all(&out, |caps: &regex::Captures| {
      let prefix = &caps[1];
      let variant = &caps[2];
      let payload = &caps[3];
      let suffix = &caps[4];
      if variant == payload {
        format!("{prefix}{KOTLIN_PACKAGE}.{payload}{suffix}")
      } else {
        format!("{prefix}{payload}{suffix}")
      }
    })
    .into_owned();

  Ok(out)
}

#[derive(Debug, Clone)]
struct AdjacentTaggedEnum {
  name: String,
  tag: String,
}

/// Walk the lib source tree and collect every `#[typeshare]`'d enum
/// that's also tagged `#[serde(tag = "...", content = "...")]`. Those
/// are the enums typeshare emits as kotlin sealed classes that need an
/// `AdjacentTaggedSerializer` proxy. The tag string drives the
/// per-enum discriminator name in the emitted serializer.
fn discover_adjacent_tagged_enums(dir: &str) -> Result<Vec<AdjacentTaggedEnum>> {
  let mut found = Vec::new();
  for entry in walkdir::WalkDir::new(dir) {
    let entry = entry.context("walk crates/lib/src")?;
    let path = entry.path();
    if !entry.file_type().is_file() {
      continue;
    }
    if path.extension().and_then(|s| s.to_str()) != Some("rs") {
      continue;
    }
    let src = std::fs::read_to_string(path).with_context(|| format!("read {}", path.display()))?;
    let parsed = match syn::parse_file(&src) {
      Ok(p) => p,
      Err(e) => {
        eprintln!("    warning: failed to parse {}: {e}", path.display());
        continue;
      }
    };
    collect_enums_from_items(&parsed.items, &mut found);
  }
  found.sort_by(|a, b| a.name.cmp(&b.name));
  found.dedup_by(|a, b| a.name == b.name);
  Ok(found)
}

fn collect_enums_from_items(items: &[Item], out: &mut Vec<AdjacentTaggedEnum>) {
  for item in items {
    match item {
      Item::Enum(en) => {
        if let Some(tag) = typeshared_adjacent_tag(&en.attrs) {
          out.push(AdjacentTaggedEnum {
            name: en.ident.to_string(),
            tag,
          });
        }
      }
      Item::Mod(m) => {
        if let Some((_, items)) = &m.content {
          collect_enums_from_items(items, out);
        }
      }
      _ => {}
    }
  }
}

fn typeshared_adjacent_tag(attrs: &[syn::Attribute]) -> Option<String> {
  let mut typeshared = false;
  let mut tag: Option<String> = None;
  let mut has_content = false;
  for attr in attrs {
    if attr.path().is_ident("typeshare") {
      typeshared = true;
      continue;
    }
    if attr.path().is_ident("serde") {
      let Ok(nested) = attr.parse_args_with(syn::punctuated::Punctuated::<Meta, syn::Token![,]>::parse_terminated)
      else {
        continue;
      };
      for meta in nested {
        if let Meta::NameValue(nv) = meta {
          if nv.path.is_ident("tag") {
            if let syn::Expr::Lit(syn::ExprLit {
              lit: syn::Lit::Str(s), ..
            }) = &nv.value
            {
              tag = Some(s.value());
            }
          }
          if nv.path.is_ident("content") {
            has_content = true;
          }
        }
      }
    }
  }
  if typeshared && has_content { tag } else { None }
}

fn run(program: &str, args: &[&str]) -> Result<()> {
  let status = Command::new(program)
    .args(args)
    .status()
    .with_context(|| format!("spawn {program}"))?;
  if !status.success() {
    bail!("{program} exited with {status}");
  }
  Ok(())
}
