[package]
name = "bridgething-codegen"
rust-version.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
homepage.workspace = true

[dependencies]
anyhow = "1.0.102"
quote = "1.0.41"
regex = "1.12.3"
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
syn = { version = "2.0.117", features = ["full", "parsing"] }
walkdir = "2.5.0"
