[package]
name = "bridgething-test-harness"
rust-version.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
homepage.workspace = true
publish = false

[dependencies]
bridgething = { path = "../core", features = ["test-tap"] }
libbridgething = { path = "../lib", features = ["protocol"] }

tokio = { workspace = true, features = ["full"] }
tokio-util = { workspace = true, features = ["codec"] }
futures = { workspace = true }
bluer = { workspace = true, features = ["bluetoothd", "rfcomm"] }
uuid = { workspace = true, features = ["v7"] }
anyhow = "1.0"
tempfile = "3.23.0"
tokio-tungstenite = { version = "0.29.0", default-features = false, features = ["connect"] }
bridgething-iap2 = { version = "0.1.0", path = "../iap2", features = ["emulator"] }
chromiumoxide = "0.9.1"
serde.workspace = true
serde_json.workspace = true
bridgething-gateway = { version = "0.1.0", path = "../gateway-rs" }
