[package]
name = "bridgething-test-harness"
rust-version.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
homepage.workspace = true
publish = false

[dependencies]
bridgething = { path = "../core", features = ["test-tap"] }
libbridgething = { path = "../lib", features = ["protocol"] }

tokio = { workspace = true, features = ["full"] }
tokio-util = { workspace = true, features = ["codec"] }
futures = { workspace = true }
uuid = { workspace = true, features = ["v7"] }
anyhow = "1.0"
tempfile = "3.23.0"
tokio-tungstenite = { version = "0.29.0", default-features = false, features = [
  "connect",
] }
bridgething-iap2 = { workspace = true, features = ["emulator"] }
chromiumoxide = { version = "0.9.1", optional = true }
serde.workspace = true
serde_json.workspace = true
bridgething-gateway = { workspace = true }
async-trait.workspace = true
bridgething-client = { workspace = true }

[target.'cfg(target_os = "linux")'.dependencies]
bluer = { workspace = true, features = ["bluetoothd", "rfcomm"] }

[features]
default = ["chrome"]
chrome = ["dep:chromiumoxide"]

[dev-dependencies]
base64 = "0.22.1"
bridgething-delivery = { path = "../delivery/core" }
bridgething-host-gateway = { path = "../host-gateway" }
hex = "0.4.3"
proptest = "1.11.0"
reqwest = { version = "0.13.4", default-features = false }
sha2 = "0.11.0"
tracing-subscriber = { workspace = true, features = ["env-filter"] }
