// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BridgeThingMeta } from './shared';

export type ArbitraryData = string | Uint8Array;

export type BridgeFile = { path: string; data: Uint8Array };

/**
 * bridgething -> gateway
 * messages from bridgething to the gateway (mobile or desktop app).
 *
 * these messages will pass over bluetooth.
 */
export type BridgeToGatewayMsg = { id: string } & (
  | { meta: 'command' }
  | { meta: 'event' }
  | { meta: 'request' }
  | { meta: 'response'; request_id: string }
) &
  (
    | { type: 'version'; data: BridgeThingMeta }
    | { type: 'files'; data: { files: Array<string> } }
    | { type: 'data'; data: ArbitraryData }
  );

export type BridgeToGatewayMsgData =
  | { type: 'version'; data: BridgeThingMeta }
  | { type: 'files'; data: { files: Array<string> } }
  | { type: 'data'; data: ArbitraryData };

export type GatewayMsgMeta =
  | { meta: 'command' }
  | { meta: 'event' }
  | { meta: 'request' }
  | { meta: 'response'; request_id: string };

/**
 * gateway -> bridgething
 * messages from the gateway (mobile or desktop app) to bridgething.
 *
 * these messages will pass over bluetooth.
 */
export type GatewayToBridgeMsg = { id: string } & (
  | { meta: 'command' }
  | { meta: 'event' }
  | { meta: 'request' }
  | { meta: 'response'; request_id: string }
) &
  (
    | { type: 'version'; data: { version: string; app: string } }
    | { type: 'listFiles' }
    | { type: 'deleteFiles'; data: { files: Array<string> } }
    | { type: 'addFiles'; data: { files: Array<BridgeFile> } }
    | { type: 'navigate'; data: { url: string } }
    | { type: 'data'; data: ArbitraryData }
  );

export type GatewayToBridgeMsgData =
  | { type: 'version'; data: { version: string; app: string } }
  | { type: 'listFiles' }
  | { type: 'deleteFiles'; data: { files: Array<string> } }
  | { type: 'addFiles'; data: { files: Array<BridgeFile> } }
  | { type: 'navigate'; data: { url: string } }
  | { type: 'data'; data: ArbitraryData };
