// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BridgeThingMeta, ForwardMessage, GatewayMeta } from './shared';

export type BridgeFile = { path: string; data: Uint8Array };

export type BridgeToGatewayFileMsg = { event: 'files'; data: { files: Array<string> } };

/**
 * bridgething -> gateway
 * messages from bridgething to the gateway (mobile or desktop app).
 *
 * these messages will pass over bluetooth.
 */
export type BridgeToGatewayMsg = { id: string } & (
  | { meta: 'command' }
  | { meta: 'event' }
  | { meta: 'request' }
  | { meta: 'response'; requestId: string }
) &
  (
    | { type: 'version'; data: BridgeThingMeta }
    | ({ type: 'file' } & BridgeToGatewayFileMsg)
    | ({ type: 'forward' } & ForwardMessage)
    | { type: 'ack' }
    | { type: 'done' }
  );

export type BridgeToGatewayMsgData =
  | { type: 'version'; data: BridgeThingMeta }
  | ({ type: 'file' } & BridgeToGatewayFileMsg)
  | ({ type: 'forward' } & ForwardMessage)
  | { type: 'ack' }
  | { type: 'done' };

export type GatewayMsgMeta =
  | { meta: 'command' }
  | { meta: 'event' }
  | { meta: 'request' }
  | { meta: 'response'; requestId: string };

export type GatewayToBridgeChromeMsg = { event: 'navigate'; data: { url: string } };

export type GatewayToBridgeFileMsg =
  | { event: 'list' }
  | { event: 'delete'; data: { files: Array<string> } }
  | { event: 'add'; data: { files: Array<BridgeFile> } };

/**
 * gateway -> bridgething
 * messages from the gateway (mobile or desktop app) to bridgething.
 *
 * these messages will pass over bluetooth.
 */
export type GatewayToBridgeMsg = { id: string } & (
  | { meta: 'command' }
  | { meta: 'event' }
  | { meta: 'request' }
  | { meta: 'response'; requestId: string }
) &
  (
    | { type: 'version'; data: GatewayMeta }
    | ({ type: 'file' } & GatewayToBridgeFileMsg)
    | ({ type: 'chrome' } & GatewayToBridgeChromeMsg)
    | ({ type: 'forward' } & ForwardMessage)
  );

export type GatewayToBridgeMsgData =
  | { type: 'version'; data: GatewayMeta }
  | ({ type: 'file' } & GatewayToBridgeFileMsg)
  | ({ type: 'chrome' } & GatewayToBridgeChromeMsg)
  | ({ type: 'forward' } & ForwardMessage);
