// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {
  CurrentlyActiveApplication,
  Device,
  PhoneCallDirection,
  PhoneCallStatus,
  PlaybackOptions,
  PlaybackRestrictions,
  QueueTrack,
  Track,
} from './shared';

export type ServerBluetoothEvent =
  | { action: 'status'; data: { connected: boolean } }
  | { action: 'connectedDevice'; data: { name: string; mac: string } }
  | { action: 'interface'; data: { mac: string; name: string; interface: string } }
  | { action: 'paringResult'; data: { success: boolean } }
  | { action: 'pin'; data: { mac: string; name: string; pin: string } }
  | { action: 'pairedDevices'; data: { [key in string]?: Device } };

export type ServerEvent = { id: string; meta: ServerEventType; stock_msg_id: number | null } & (
  | { type: 'bluetooth'; data: ServerBluetoothEvent }
  | { type: 'storage'; data: ServerStorageEvent }
  | { type: 'system'; data: ServerSystemEvent }
  | { type: 'interaction'; data: ServerInteractionEvent }
  | { type: 'player'; data: ServerPlayerEvent }
  | { type: 'ack' }
);

export type ServerEventData =
  | { type: 'bluetooth'; data: ServerBluetoothEvent }
  | { type: 'storage'; data: ServerStorageEvent }
  | { type: 'system'; data: ServerSystemEvent }
  | { type: 'interaction'; data: ServerInteractionEvent }
  | { type: 'player'; data: ServerPlayerEvent }
  | { type: 'ack' };

export type ServerEventType = 'request' | 'response' | 'info';

export type ServerInteractionEvent = { action: 'legacySpotifyPermissions' };

export type ServerPlayerEvent =
  | {
      action: 'idlePlayerState';
      data: {
        context_uri: string;
        is_paused: boolean;
        is_paused_bool: boolean;
        playback_options: PlaybackOptions;
        playback_position: number;
        playback_restrictions: PlaybackRestrictions;
        playback_speed: number;
      };
    }
  | {
      action: 'simplePlayerState';
      data: {
        currently_active_application: CurrentlyActiveApplication;
        context_uri: string;
        context_title: string;
        is_paused: boolean;
        is_paused_bool: boolean;
        playback_options: PlaybackOptions;
        playback_position: number;
        playback_restrictions: PlaybackRestrictions;
        playback_speed: number;
        track: Track;
      };
    }
  | {
      action: 'spotifyPlayerState';
      data: {
        context_uri: string;
        context_title: string;
        is_paused: boolean;
        is_paused_bool: boolean;
        playback_options: PlaybackOptions;
        playback_position: number;
        playback_restrictions: PlaybackRestrictions;
        playback_speed: number;
        track: Track;
      };
    }
  | { action: 'playerQueue'; data: { next: Array<QueueTrack>; current: QueueTrack; previous: Array<QueueTrack> } }
  | { action: 'image'; data: { height: number; width: number; data: string } };

export type ServerStorageEvent = { action: 'response'; data: { key: string; value: string | null } };

export type ServerSystemEvent =
  | {
      action: 'version';
      data: {
        serial: string;
        os_version: string;
        app_version: string;
        fw_version: string;
        model_name: string;
        fcc_id: string;
        ic_id: string;
        country: string;
        discord: string;
        credits: string;
      };
    }
  | { action: 'otaReboot'; data: { delay_ms: number } }
  | { action: 'otaPowerOff'; data: { delay_ms: number } }
  | { action: 'ambientLightUpdate'; data: { brightness: number } }
  | {
      action: 'phoneCallInfo';
      data: {
        remote_id: string;
        display_name: string;
        status: PhoneCallStatus;
        call_dir: PhoneCallDirection;
        call_id: string;
      };
    };
