[package]
name = "spotify"
rust-version.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
homepage.workspace = true

[dependencies]
uuid = { workspace = true, features = ["v4"] }
tokio = { workspace = true, features = [
  "rt-multi-thread",
  "sync",
  "time",
  "macros",
  "net",
  "io-util",
] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
futures = { workspace = true }
flate2 = { workspace = true }
librespot-protocol = "0.8.0"
base64 = "0.22.1"
hex = "0.4.3"
url = "2.5.8"
rand = "0.10.1"
protobuf = "3.7.2"
shannon = "0.2.0"
num-bigint = "0.4.6"
hmac = "0.13.0"
sha1 = "0.11.0"
bridgething-io = { path = "../io", default-features = false }
http = "1.5.0"

[features]
default = []
native-io = ["bridgething-io/native-io"]

[[bin]]
name = "sfp"
path = "src/bin/sfp.rs"
required-features = ["native-io"]

[build-dependencies]
protobuf-codegen = "3.7.2"

[dev-dependencies]
tokio = { workspace = true, features = ["test-util"] }
