[package]
name = "nlu"
rust-version.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
homepage.workspace = true

[lib]
crate-type = ["lib"]

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokenizers = { version = "0.23.1", default-features = false, features = [
  "fancy-regex",
] }
