query getPresets($serial: String!) {
  presets(serial: $serial) {
    ... on Presets {
      presets {
        context_uri: contextUri
        name
        slot_index: slotIndex
        description
        image_url: imageUrl
      }
    }
    ... on PresetsError {
      message
    }
  }
}
