[package]
edition = "2021"
name = "bridgething-adapter"
version = "0.0.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
libbridgething = { path = "../lib" }

futures = { workspace = true }
tokio = { workspace = true, features = ["sync", "macros"] }
tokio-util = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }

napi = { version = "3.0.0-alpha.27", default-features = false, features = [
  "async",
  "tokio_sync",
] }
napi-derive = "3.0.0-alpha.25"
btleplug = { version = "0.11.7", features = ["serde"] }


[build-dependencies]
napi-build = "2.1.4"
napi-derive = "3.0.0-alpha.25"
