package com.bridgething.companion

import com.bridgething.schema.VoiceCodec
import com.bridgething.schema.VoiceFormat
import java.util.Base64

object NextSongCommandFixture {
    const val UTTERANCE = "next song"

    val format = VoiceFormat(codec = VoiceCodec.Opus, sampleRateHz = 16_000u, channels = 1u)

    val packets: List<ByteArray>
        get() = encoded.map { Base64.getDecoder().decode(it) }

    private val encoded = listOf(
        "SAvkwSIjYfA=",
        "SAfJecUS97w=",
        "SAfJecUS97w=",
        "SAfJcifhPlM=",
        "SAfJcifhPlM=",
        "SAfJecUS97w=",
        "SAfJecUS97w=",
        "SAfJcifhPlM=",
        "SAfJcifhPlM=",
        "SAfJecUS97w=",
        "SAfJecUS97w=",
        "SAfJcifhPlM=",
        "SAfJcifhPlM=",
        "SAfJecUS97w=",
        "SAfJecUS97w=",
        "SAfJcifhPlM=",
        "SAfJcifhPlM=",
        "SAfJecUS97w=",
        "SAfJecUS97w=",
        "SAfJcifhPlM=",
        "SIALyvNPc8J5l8IhnFMMr14SGLJg6SuPL4sXLXs12dSBOWOYf4C8BYe9xi6k7XTTcQt5/Bg=",
        "SJy6qb0JNpSypiPNebIOovAyGNDCtuWcvxmXqiMtngeuRi4LXQt4R0fMubI2iyX2wEEuzv9JJeKhOw==",
        "SKA6gKm09FLYIjDARU0i7cqkJZaNsQVZUcKOHqD0ZqOSQYs7vlHUq0Iz4pWup95iNu+EGlQc",
        "SKuSM0Wrq/UoIb97/4aEPd2BsI4zYWxZexF2um9E1aEl3r/MTtvgEWM9nhfENnyOTE4PK6oXvAhOFoUCt02vDTaY",
        "SLISsi/USuPy7T99r2cBe2ov/fTztql124KCPNwWzKw1J9SPZQc7TqTjXLACfY4xHW2sOV++",
        "SLIGuIxQVO1+Mgkqs8ZXLwZiRAk/UA8OYLq/lBTQ9bVPv7YrzDI1qg7wndkKZpEdYb40+A==",
        "SLBRlFS7bJn5POrnULJKCcBtdJ1rKEevzJcYiJMTNbPSqilV6KUiYVhWvIlB",
        "SK++iK6iOiRTgbwjfppbwfrV/D6RTqflL5vnWH3ou25gmvjBaQecrThZDUsHMmvyj4jRhw+ojJs4xdJqjtg=",
        "SKH3gT36ZPl/KOBxqkKF7pBRfedBaY3XGT6ykuVlyx7w8A5L3Fwxc29J17Lb2zKqQUCiukCIAMM5N+92XCA=",
        "SJkHoeZT7p5umS4zmVeogMGkmESajaEv4Lgba6P8VLedNAwJOCahf4Ci5IYxHge6YPYyXw==",
        "SIKIf209w0Kd5uHXVUw3EOcZDAKl4jfvkXymWRNIOpavxFJmkb8E1NHijuXYOODAgZOghheT9/D5SpAXbAcLaltSjHxA",
        "SISA3ZfCpBxoxtnfFqdP4pQg5Xrx79ld/Di3jDtC7ucfssmQ0m7Ib0fJxaOsvgJbIpXRPP/3HTbEvSNORpag",
        "SJHTh+26DVVXjzZDVji45WfyNBpqcX2EWnr8L6ZX8kD6hpBmS5QpJ0lVDqhQ8diPRPzIPFmSGu66+JvA",
        "SI+mxIDUn+X6NPKir62Kx0veAiGvIcT3DxdKqqfLokEvshK9RlUwvDrb1E1CA/5/TABkmkbgksT+gHvW+g==",
        "SIJiGGdHggc6jsToR6I6wJaVkkCjrD8qoMSO3x8aRWAiGpMk2aV1OoJq8aXdB4RMeZSto0PQghAvgpA=",
        "SIDdtNuKDXUyIIMV9KQ6x9YvzKmivVvEZsj33agiXluGgELbcebn5eyGiUyE77RGDwfeM1m0MF1wwA==",
        "SIL2AFTNTMgxh6suD0UsikidpEeRaYuPtqX+2wqkT3OQq57cbWfZxHh6BOYaG/3M3Cvx1XqmXa6hNJGkj22w",
        "SJCKVIZzti9ihBIYSt9cjMVoQS7gIZrph9Sf+4wraVtEkHb/lBCVvpywnKTri/SNXz2Rt/4uB/duu8PiZydnfJl5DptW1nyU",
        "SIPmlQ4biRgf6hzaWLAwVMch2tFNICAyInp4A6Qf4rRMNFLX414HTDv9hbu9ni9wpjq0zjTy2mXoQ9aEEHEwTDiA",
        "SJIE0Exvvq1zGXGXyarfb31EHyDuC/m0/ZioQpoNy/+SnjLIvp+Ym9qTeM/NEFzdUqNXyanZNPs0",
        "SIPouGlaCSgP0kYed1yBG5LL76Xr/DR22mBInUFUrse82ja+dx1Gnb2ZLrr48op/QHoFfw36qlTolNQCnYdf",
        "SIQwwA+iWZcaETYZDgCsTdbc4DItwERVwDDOij8iRrwCVIwQdptwiKK5lkgVcCt2E7DRCHNqaPj3/5RI/Q9y7jgDABIzAg==",
        "SK692KOi4GK1gjiEJRhztZyhtEy/Brgcjs88Q2iZ9YACXrQ7VFMGoIj1F32kF+mwuh9+dJLsVdpB4A==",
        "SK696CDml5dNMObNUugkFlEBMuPJqsT4tm/EICQNV5UNH4DvW11PKXCQvOAHFtu2ZZQeKGlYxOkY",
        "SK587BzZNPwGVgPKHRZJupmZ1+3dxVejF+0A80zCka8aH9HRRAY+mFJFCx/7u+A=",
        "SKztlQimVNGD0RdIz4LodKKvFWyutuAybyfwDRQ0v5JhtOcs05c=",
        "SKs61QZMbfdhsoNvvv+wkbHaaeKuaMP8rAX+j1xyTZHcYWPisewBSU38YqOw",
        "SKs2NFcJF2WsL4DoB6Ri5bVXel6aly/DmZuiPZVAAbNVVH6UOhvxN19NOchn9phaOD3g",
        "SKmH/fjgzbdCd5kcqYqS0K4+6fCOoAh7qfQE0iWZYB/lIxiITnp/WVeGUWOGrV7E5NspgQ==",
        "SKftIZbL+OSSndHlgFfqUHgSrewLWtf5f7N+aHcwcKdCch5QxNOZphrA",
        "SKZeztm4ycNOaP0x2dmE5XMCFh+GWAFQ9/XqlpwidqaEMuQzzocO+rkRRXU=",
        "SKUWbtZTOE4G0IXdmWaJYC8MfclhrcV2EQalhUbrkOcVWt3yfkSFU0ySHhn1EWQOJi0Q5A==",
        "SKTje9qx7ytKxdQoFqNEJ/Y/zDFQ+N1jgZJotZZ/OhNdaCEdPEXr1TiHtNdv1iKOscMAlCfGt6FaC/mDz7nA",
        "SKIdaUpvQKZyoum/gkioI4YtxsRTpBrhr0gszdK4UK+Wy3W/mBb6hajMWwOynPfDOH7/XQVHza1g",
        "SJ0DJAau2qBAqNCSZ5iOGTXNe6S0xirxD+4XNb5vVwvWSukOE1POAK3w/vsD5B40xkA=",
        "SJxu3fLO6fvHBFeosrJ6cu1BlJaQDYzO7nT1crME2ymkS9euGvvfzOLV3WtA",
        "SJv0P56CDkx6TaSpop4tYKu+cnZJaDrb9vbjM4HxQ+zCm7rPoBlC1jWlzGM/d5vqOUMMUjnOcd+xUUyc",
        "SJsAtFde68oNEdUtTVP8ODJOjrv1A1aQUvGPocfkOOM7fYIxyBejKUHKOIdwrAxYSvgiUjHYgA==",
        "SJj5mWQwoyy0K3X+lnqjjeip/b8FQzIRwCiwcMvO3wpDbwzBRrCvfqXb1Ocg",
        "SAGLEA31FhO8Ag3XcC0+TcTou9KrN/yMFLY1STT8qWExnmp1wA==",
        "SAszH32V/JUcYsC+1FbxadRlxzDcuoUNcDEe",
        "SAfJecUTKsc0",
        "SAfJecUTKsc0",
        "SAfJcifhPlM=",
        "SAfJcifhPlM=",
        "SAfJecUTKsc0",
        "SAfJecUTKsc0",
        "SAfJcifhPlM=",
        "SAfJcifhPlM=",
        "SAfJecUTKsc0",
        "SAfJecUTKsc0",
        "SAfJcifhPlM=",
        "SAfJcifhPlM=",
        "SAfJecUTKsc0",
        "SAfJecUTKsc0",
        "SAfJcifhPlM=",
        "SAfJcifhPlM=",
        "SAfJecUTKsc0",
        "SAfJecUTKsc0",
        "SAfJcifhPlM=",
        "SAfJcifhPlM=",
    )
}
