// THIS FILE IS GENERATED BY tools/codegen. Do not edit by hand.
// Re-generate with `just codegen` (or `just typescript`).

import {
  type AmbientLightUpdate,
  type AssetCleared,
  type AssetGet,
  type AssetGot,
  type AssetNotFound,
  type AssetReady,
  type BluetoothInterface,
  type BluetoothPairingResult,
  type BluetoothPin,
  type BluetoothStatus,
  type BridgeThingMeta,
  type ClientToBridgeMsg,
  type ConnectBluetooth,
  type ConnectedDevice,
  type DisablePan,
  type EnablePan,
  type ForgetBluetooth,
  type GatewayStatus,
  type KVDelete,
  type KVGet,
  type KVPut,
  type MicMute,
  type MicUnmute,
  type OtaPowerOff,
  type OtaReboot,
  type PairBluetooth,
  type PairedDevicesMap,
  type PeerSnapshotMap,
  type PhoneCallAccept,
  type PhoneCallEnd,
  type PhoneCallImage,
  type PhoneCallInfo,
  type PhoneCallMessage,
  type PlayerImage,
  type PlayerQueue,
  type PlayerState,
  type SeekTo,
  type SetBluetoothAlias,
  type SetRepeat,
  type SetShuffle,
  type SkipToIndex,
  type StorageResponse,
  type WireError,
  newUuidBytes,
} from '@bridgething/lib';
import { BridgethingClient, type ClientEvent } from './index';

export type TypedRequestResult<R, E> =
  | { ok: true; response: R }
  | { ok: false; kind: 'domain'; error: E }
  | { ok: false; kind: 'protocol'; error: WireError };

export type AssetInboundHandlers = {
  got: (msg: AssetGot) => void;
  notFound: (msg: AssetNotFound) => void;
  ready: (msg: AssetReady) => void;
  cleared: (msg: AssetCleared) => void;
};

export type BluetoothInboundHandlers = {
  status: (msg: BluetoothStatus) => void;
  connectedDevice: (msg: ConnectedDevice) => void;
  interface: (msg: BluetoothInterface) => void;
  pairingResult: (msg: BluetoothPairingResult) => void;
  pin: (msg: BluetoothPin) => void;
  pairedDevices: (msg: PairedDevicesMap) => void;
};

export type SystemInboundHandlers = {
  version: (msg: BridgeThingMeta) => void;
  gatewayStatus: (msg: GatewayStatus) => void;
  otaReboot: (msg: OtaReboot) => void;
  otaPowerOff: (msg: OtaPowerOff) => void;
  ambientLightUpdate: (msg: AmbientLightUpdate) => void;
  phoneCallInfo: (msg: PhoneCallInfo) => void;
};

export type PlayerInboundHandlers = {
  playerIdle: () => void;
  playerState: (msg: PlayerState) => void;
  queue: (msg: PlayerQueue) => void;
  image: (msg: PlayerImage) => void;
};

export type ForwardInboundHandlers = {
  text: (msg: string) => void;
  json: (msg: unknown) => void;
  binary: (msg: Uint8Array) => void;
};

export class AssetSurface {
  constructor(private readonly _client: BridgethingClient) {}

  /** Subscribe to `Asset::Got` from the daemon. */
  onGot(handler: (msg: AssetGot) => void): () => void {
    return this._client.on(event => {
      if (event.type !== 'message') return;
      const data = event.message.data;
      if (data.type !== 'asset') return;
      const inner = data.data;
      if (inner.event !== 'got') return;
      handler(inner.data);
    });
  }

  /** Subscribe to `Asset::NotFound` from the daemon. */
  onNotFound(handler: (msg: AssetNotFound) => void): () => void {
    return this._client.on(event => {
      if (event.type !== 'message') return;
      const data = event.message.data;
      if (data.type !== 'asset') return;
      const inner = data.data;
      if (inner.event !== 'notFound') return;
      handler(inner.data);
    });
  }

  /** Subscribe to `Asset::Ready` from the daemon. */
  onReady(handler: (msg: AssetReady) => void): () => void {
    return this._client.on(event => {
      if (event.type !== 'message') return;
      const data = event.message.data;
      if (data.type !== 'asset') return;
      const inner = data.data;
      if (inner.event !== 'ready') return;
      handler(inner.data);
    });
  }

  /** Subscribe to `Asset::Cleared` from the daemon. */
  onCleared(handler: (msg: AssetCleared) => void): () => void {
    return this._client.on(event => {
      if (event.type !== 'message') return;
      const data = event.message.data;
      if (data.type !== 'asset') return;
      const inner = data.data;
      if (inner.event !== 'cleared') return;
      handler(inner.data);
    });
  }

  /** Exhaustive subscribe over all inbound `Asset` variants. */
  subscribe(handlers: AssetInboundHandlers): () => void {
    return this._subscribe(handlers, false);
  }

  /** Same as `subscribe` but every handler is optional. */
  subscribePartial(handlers: Partial<AssetInboundHandlers>): () => void {
    return this._subscribe(handlers, true);
  }

  private _subscribe(handlers: Partial<AssetInboundHandlers>, partial: boolean): () => void {
    return this._client.on(event => {
      if (event.type !== 'message') return;
      const data = event.message.data;
      if (data.type !== 'asset') return;
      const inner = data.data;
      switch (inner.event) {
        case 'got': {
          handlers.got?.(inner.data);
          return;
        }
        case 'notFound': {
          handlers.notFound?.(inner.data);
          return;
        }
        case 'ready': {
          handlers.ready?.(inner.data);
          return;
        }
        case 'cleared': {
          handlers.cleared?.(inner.data);
          return;
        }
        default: {
          if (!partial) this._client.logger.warn('Asset: no handler for inner', inner);
          return;
        }
      }
    });
  }

  /** Typed request to the daemon: webapp sends, daemon responds. */
  async get(req: AssetGet, options?: { timeoutMs?: number }): Promise<TypedRequestResult<AssetGot, AssetNotFound>> {
    const wireData: ClientToBridgeMsg['data'] = { type: 'asset', data: { event: 'get', data: req } };
    const response = await this._client.request(wireData, options?.timeoutMs);
    const d = response.data;
    if (d.type === 'asset') {
      const inner = d.data;
      if (inner.event === 'got') return { ok: true, response: inner.data };
      if (inner.event === 'notFound') return { ok: false, kind: 'domain', error: inner.data };
    }
    if (d.type === 'error') return { ok: false, kind: 'protocol', error: d.data };
    return { ok: false, kind: 'protocol', error: { type: 'unsupported' } };
  }
}

export class BluetoothSurface {
  constructor(private readonly _client: BridgethingClient) {}

  /** Subscribe to `Bluetooth::Status` from the daemon. */
  onStatus(handler: (msg: BluetoothStatus) => void): () => void {
    return this._client.on(event => {
      if (event.type !== 'message') return;
      const data = event.message.data;
      if (data.type !== 'bluetooth') return;
      const inner = data.data;
      if (inner.event !== 'status') return;
      handler(inner.data);
    });
  }

  /** Subscribe to `Bluetooth::ConnectedDevice` from the daemon. */
  onConnectedDevice(handler: (msg: ConnectedDevice) => void): () => void {
    return this._client.on(event => {
      if (event.type !== 'message') return;
      const data = event.message.data;
      if (data.type !== 'bluetooth') return;
      const inner = data.data;
      if (inner.event !== 'connectedDevice') return;
      handler(inner.data);
    });
  }

  /** Subscribe to `Bluetooth::Interface` from the daemon. */
  onInterface(handler: (msg: BluetoothInterface) => void): () => void {
    return this._client.on(event => {
      if (event.type !== 'message') return;
      const data = event.message.data;
      if (data.type !== 'bluetooth') return;
      const inner = data.data;
      if (inner.event !== 'interface') return;
      handler(inner.data);
    });
  }

  /** Subscribe to `Bluetooth::PairingResult` from the daemon. */
  onPairingResult(handler: (msg: BluetoothPairingResult) => void): () => void {
    return this._client.on(event => {
      if (event.type !== 'message') return;
      const data = event.message.data;
      if (data.type !== 'bluetooth') return;
      const inner = data.data;
      if (inner.event !== 'pairingResult') return;
      handler(inner.data);
    });
  }

  /** Subscribe to `Bluetooth::Pin` from the daemon. */
  onPin(handler: (msg: BluetoothPin) => void): () => void {
    return this._client.on(event => {
      if (event.type !== 'message') return;
      const data = event.message.data;
      if (data.type !== 'bluetooth') return;
      const inner = data.data;
      if (inner.event !== 'pin') return;
      handler(inner.data);
    });
  }

  /** Subscribe to `Bluetooth::PairedDevices` from the daemon. */
  onPairedDevices(handler: (msg: PairedDevicesMap) => void): () => void {
    return this._client.on(event => {
      if (event.type !== 'message') return;
      const data = event.message.data;
      if (data.type !== 'bluetooth') return;
      const inner = data.data;
      if (inner.event !== 'pairedDevices') return;
      handler(inner.data);
    });
  }

  /** Exhaustive subscribe over all inbound `Bluetooth` variants. */
  subscribe(handlers: BluetoothInboundHandlers): () => void {
    return this._subscribe(handlers, false);
  }

  /** Same as `subscribe` but every handler is optional. */
  subscribePartial(handlers: Partial<BluetoothInboundHandlers>): () => void {
    return this._subscribe(handlers, true);
  }

  private _subscribe(handlers: Partial<BluetoothInboundHandlers>, partial: boolean): () => void {
    return this._client.on(event => {
      if (event.type !== 'message') return;
      const data = event.message.data;
      if (data.type !== 'bluetooth') return;
      const inner = data.data;
      switch (inner.event) {
        case 'status': {
          handlers.status?.(inner.data);
          return;
        }
        case 'connectedDevice': {
          handlers.connectedDevice?.(inner.data);
          return;
        }
        case 'interface': {
          handlers.interface?.(inner.data);
          return;
        }
        case 'pairingResult': {
          handlers.pairingResult?.(inner.data);
          return;
        }
        case 'pin': {
          handlers.pin?.(inner.data);
          return;
        }
        case 'pairedDevices': {
          handlers.pairedDevices?.(inner.data);
          return;
        }
        default: {
          if (!partial) this._client.logger.warn('Bluetooth: no handler for inner', inner);
          return;
        }
      }
    });
  }

  /** Send `Bluetooth::Connect` to the daemon. */
  async connect(payload: ConnectBluetooth): Promise<void> {
    const msg: ClientToBridgeMsg = {
      id: newUuidBytes(),
      meta: { kind: 'command' },
      data: { type: 'bluetooth', data: { event: 'connect', data: payload } },
    };
    await this._client.send(msg);
  }

  /** Send `Bluetooth::Scan` to the daemon. */
  async scan(): Promise<void> {
    const msg: ClientToBridgeMsg = {
      id: newUuidBytes(),
      meta: { kind: 'command' },
      data: { type: 'bluetooth', data: { event: 'scan' } },
    };
    await this._client.send(msg);
  }

  /** Send `Bluetooth::EnableDiscoverable` to the daemon. */
  async enableDiscoverable(): Promise<void> {
    const msg: ClientToBridgeMsg = {
      id: newUuidBytes(),
      meta: { kind: 'command' },
      data: { type: 'bluetooth', data: { event: 'enableDiscoverable' } },
    };
    await this._client.send(msg);
  }

  /** Send `Bluetooth::DisableDiscoverable` to the daemon. */
  async disableDiscoverable(): Promise<void> {
    const msg: ClientToBridgeMsg = {
      id: newUuidBytes(),
      meta: { kind: 'command' },
      data: { type: 'bluetooth', data: { event: 'disableDiscoverable' } },
    };
    await this._client.send(msg);
  }

  /** Send `Bluetooth::Pair` to the daemon. */
  async pair(payload: PairBluetooth): Promise<void> {
    const msg: ClientToBridgeMsg = {
      id: newUuidBytes(),
      meta: { kind: 'command' },
      data: { type: 'bluetooth', data: { event: 'pair', data: payload } },
    };
    await this._client.send(msg);
  }

  /** Send `Bluetooth::Forget` to the daemon. */
  async forget(payload: ForgetBluetooth): Promise<void> {
    const msg: ClientToBridgeMsg = {
      id: newUuidBytes(),
      meta: { kind: 'command' },
      data: { type: 'bluetooth', data: { event: 'forget', data: payload } },
    };
    await this._client.send(msg);
  }

  /** Send `Bluetooth::EnablePan` to the daemon. */
  async enablePan(payload: EnablePan): Promise<void> {
    const msg: ClientToBridgeMsg = {
      id: newUuidBytes(),
      meta: { kind: 'command' },
      data: { type: 'bluetooth', data: { event: 'enablePan', data: payload } },
    };
    await this._client.send(msg);
  }

  /** Send `Bluetooth::DisablePan` to the daemon. */
  async disablePan(payload: DisablePan): Promise<void> {
    const msg: ClientToBridgeMsg = {
      id: newUuidBytes(),
      meta: { kind: 'command' },
      data: { type: 'bluetooth', data: { event: 'disablePan', data: payload } },
    };
    await this._client.send(msg);
  }

  /** Send `Bluetooth::SetAlias` to the daemon. */
  async setAlias(payload: SetBluetoothAlias): Promise<void> {
    const msg: ClientToBridgeMsg = {
      id: newUuidBytes(),
      meta: { kind: 'command' },
      data: { type: 'bluetooth', data: { event: 'setAlias', data: payload } },
    };
    await this._client.send(msg);
  }

  /** Typed request to the daemon: webapp sends, daemon responds. */
  async list(options?: { timeoutMs?: number }): Promise<TypedRequestResult<PairedDevicesMap, never>> {
    const wireData: ClientToBridgeMsg['data'] = { type: 'bluetooth', data: { event: 'list' } };
    const response = await this._client.request(wireData, options?.timeoutMs);
    const d = response.data;
    if (d.type === 'bluetooth') {
      const inner = d.data;
      if (inner.event === 'pairedDevices') return { ok: true, response: inner.data };
    }
    if (d.type === 'error') return { ok: false, kind: 'protocol', error: d.data };
    return { ok: false, kind: 'protocol', error: { type: 'unsupported' } };
  }
}

export class SystemSurface {
  constructor(private readonly _client: BridgethingClient) {}

  /** Subscribe to `System::Version` from the daemon. */
  onVersion(handler: (msg: BridgeThingMeta) => void): () => void {
    return this._client.on(event => {
      if (event.type !== 'message') return;
      const data = event.message.data;
      if (data.type !== 'system') return;
      const inner = data.data;
      if (inner.event !== 'version') return;
      handler(inner.data);
    });
  }

  /** Subscribe to `System::GatewayStatus` from the daemon. */
  onGatewayStatus(handler: (msg: GatewayStatus) => void): () => void {
    return this._client.on(event => {
      if (event.type !== 'message') return;
      const data = event.message.data;
      if (data.type !== 'system') return;
      const inner = data.data;
      if (inner.event !== 'gatewayStatus') return;
      handler(inner.data);
    });
  }

  /** Subscribe to `System::OtaReboot` from the daemon. */
  onOtaReboot(handler: (msg: OtaReboot) => void): () => void {
    return this._client.on(event => {
      if (event.type !== 'message') return;
      const data = event.message.data;
      if (data.type !== 'system') return;
      const inner = data.data;
      if (inner.event !== 'otaReboot') return;
      handler(inner.data);
    });
  }

  /** Subscribe to `System::OtaPowerOff` from the daemon. */
  onOtaPowerOff(handler: (msg: OtaPowerOff) => void): () => void {
    return this._client.on(event => {
      if (event.type !== 'message') return;
      const data = event.message.data;
      if (data.type !== 'system') return;
      const inner = data.data;
      if (inner.event !== 'otaPowerOff') return;
      handler(inner.data);
    });
  }

  /** Subscribe to `System::AmbientLightUpdate` from the daemon. */
  onAmbientLightUpdate(handler: (msg: AmbientLightUpdate) => void): () => void {
    return this._client.on(event => {
      if (event.type !== 'message') return;
      const data = event.message.data;
      if (data.type !== 'system') return;
      const inner = data.data;
      if (inner.event !== 'ambientLightUpdate') return;
      handler(inner.data);
    });
  }

  /** Subscribe to `System::PhoneCallInfo` from the daemon. */
  onPhoneCallInfo(handler: (msg: PhoneCallInfo) => void): () => void {
    return this._client.on(event => {
      if (event.type !== 'message') return;
      const data = event.message.data;
      if (data.type !== 'system') return;
      const inner = data.data;
      if (inner.event !== 'phoneCallInfo') return;
      handler(inner.data);
    });
  }

  /** Exhaustive subscribe over all inbound `System` variants. */
  subscribe(handlers: SystemInboundHandlers): () => void {
    return this._subscribe(handlers, false);
  }

  /** Same as `subscribe` but every handler is optional. */
  subscribePartial(handlers: Partial<SystemInboundHandlers>): () => void {
    return this._subscribe(handlers, true);
  }

  private _subscribe(handlers: Partial<SystemInboundHandlers>, partial: boolean): () => void {
    return this._client.on(event => {
      if (event.type !== 'message') return;
      const data = event.message.data;
      if (data.type !== 'system') return;
      const inner = data.data;
      switch (inner.event) {
        case 'version': {
          handlers.version?.(inner.data);
          return;
        }
        case 'gatewayStatus': {
          handlers.gatewayStatus?.(inner.data);
          return;
        }
        case 'otaReboot': {
          handlers.otaReboot?.(inner.data);
          return;
        }
        case 'otaPowerOff': {
          handlers.otaPowerOff?.(inner.data);
          return;
        }
        case 'ambientLightUpdate': {
          handlers.ambientLightUpdate?.(inner.data);
          return;
        }
        case 'phoneCallInfo': {
          handlers.phoneCallInfo?.(inner.data);
          return;
        }
        default: {
          if (!partial) this._client.logger.warn('System: no handler for inner', inner);
          return;
        }
      }
    });
  }

  /** Send `System::Reboot` to the daemon. */
  async reboot(): Promise<void> {
    const msg: ClientToBridgeMsg = {
      id: newUuidBytes(),
      meta: { kind: 'command' },
      data: { type: 'system', data: { event: 'reboot' } },
    };
    await this._client.send(msg);
  }

  /** Send `System::PowerOff` to the daemon. */
  async powerOff(): Promise<void> {
    const msg: ClientToBridgeMsg = {
      id: newUuidBytes(),
      meta: { kind: 'command' },
      data: { type: 'system', data: { event: 'powerOff' } },
    };
    await this._client.send(msg);
  }

  /** Send `System::FactoryReset` to the daemon. */
  async factoryReset(): Promise<void> {
    const msg: ClientToBridgeMsg = {
      id: newUuidBytes(),
      meta: { kind: 'command' },
      data: { type: 'system', data: { event: 'factoryReset' } },
    };
    await this._client.send(msg);
  }

  /** Send `System::PhoneCallAccept` to the daemon. */
  async phoneCallAccept(payload: PhoneCallAccept): Promise<void> {
    const msg: ClientToBridgeMsg = {
      id: newUuidBytes(),
      meta: { kind: 'command' },
      data: { type: 'system', data: { event: 'phoneCallAccept', data: payload } },
    };
    await this._client.send(msg);
  }

  /** Send `System::PhoneCallEnd` to the daemon. */
  async phoneCallEnd(payload: PhoneCallEnd): Promise<void> {
    const msg: ClientToBridgeMsg = {
      id: newUuidBytes(),
      meta: { kind: 'command' },
      data: { type: 'system', data: { event: 'phoneCallEnd', data: payload } },
    };
    await this._client.send(msg);
  }

  /** Typed request to the daemon: webapp sends, daemon responds. */
  async versionRequest(options?: { timeoutMs?: number }): Promise<TypedRequestResult<BridgeThingMeta, never>> {
    const wireData: ClientToBridgeMsg['data'] = { type: 'system', data: { event: 'versionRequest' } };
    const response = await this._client.request(wireData, options?.timeoutMs);
    const d = response.data;
    if (d.type === 'system') {
      const inner = d.data;
      if (inner.event === 'version') return { ok: true, response: inner.data };
    }
    if (d.type === 'error') return { ok: false, kind: 'protocol', error: d.data };
    return { ok: false, kind: 'protocol', error: { type: 'unsupported' } };
  }

  /** Typed request to the daemon: webapp sends, daemon responds. */
  async gatewayStatusRequest(options?: { timeoutMs?: number }): Promise<TypedRequestResult<GatewayStatus, never>> {
    const wireData: ClientToBridgeMsg['data'] = { type: 'system', data: { event: 'gatewayStatusRequest' } };
    const response = await this._client.request(wireData, options?.timeoutMs);
    const d = response.data;
    if (d.type === 'system') {
      const inner = d.data;
      if (inner.event === 'gatewayStatus') return { ok: true, response: inner.data };
    }
    if (d.type === 'error') return { ok: false, kind: 'protocol', error: d.data };
    return { ok: false, kind: 'protocol', error: { type: 'unsupported' } };
  }
}

export class PlayerSurface {
  constructor(private readonly _client: BridgethingClient) {}

  /** Subscribe to `Player::PlayerIdle` from the daemon. */
  onPlayerIdle(handler: () => void): () => void {
    return this._client.on(event => {
      if (event.type !== 'message') return;
      const data = event.message.data;
      if (data.type !== 'player') return;
      const inner = data.data;
      if (inner.event !== 'playerIdle') return;
      handler();
    });
  }

  /** Subscribe to `Player::PlayerState` from the daemon. */
  onPlayerState(handler: (msg: PlayerState) => void): () => void {
    return this._client.on(event => {
      if (event.type !== 'message') return;
      const data = event.message.data;
      if (data.type !== 'player') return;
      const inner = data.data;
      if (inner.event !== 'playerState') return;
      handler(inner.data);
    });
  }

  /** Subscribe to `Player::Queue` from the daemon. */
  onQueue(handler: (msg: PlayerQueue) => void): () => void {
    return this._client.on(event => {
      if (event.type !== 'message') return;
      const data = event.message.data;
      if (data.type !== 'player') return;
      const inner = data.data;
      if (inner.event !== 'queue') return;
      handler(inner.data);
    });
  }

  /** Subscribe to `Player::Image` from the daemon. */
  onImage(handler: (msg: PlayerImage) => void): () => void {
    return this._client.on(event => {
      if (event.type !== 'message') return;
      const data = event.message.data;
      if (data.type !== 'player') return;
      const inner = data.data;
      if (inner.event !== 'image') return;
      handler(inner.data);
    });
  }

  /** Exhaustive subscribe over all inbound `Player` variants. */
  subscribe(handlers: PlayerInboundHandlers): () => void {
    return this._subscribe(handlers, false);
  }

  /** Same as `subscribe` but every handler is optional. */
  subscribePartial(handlers: Partial<PlayerInboundHandlers>): () => void {
    return this._subscribe(handlers, true);
  }

  private _subscribe(handlers: Partial<PlayerInboundHandlers>, partial: boolean): () => void {
    return this._client.on(event => {
      if (event.type !== 'message') return;
      const data = event.message.data;
      if (data.type !== 'player') return;
      const inner = data.data;
      switch (inner.event) {
        case 'playerIdle': {
          handlers.playerIdle?.();
          return;
        }
        case 'playerState': {
          handlers.playerState?.(inner.data);
          return;
        }
        case 'queue': {
          handlers.queue?.(inner.data);
          return;
        }
        case 'image': {
          handlers.image?.(inner.data);
          return;
        }
        default: {
          if (!partial) this._client.logger.warn('Player: no handler for inner', inner);
          return;
        }
      }
    });
  }
}

export class PeerSurface {
  constructor(private readonly _client: BridgethingClient) {}

  /** Subscribe to `Peer::Snapshot` from the daemon. */
  onSnapshot(handler: (msg: PeerSnapshotMap) => void): () => void {
    return this._client.on(event => {
      if (event.type !== 'message') return;
      const data = event.message.data;
      if (data.type !== 'peer') return;
      const inner = data.data;
      if (inner.event !== 'snapshot') return;
      handler(inner.data);
    });
  }
}

export class ForwardSurface {
  constructor(private readonly _client: BridgethingClient) {}

  /** Subscribe to `Forward::Text` from the daemon. */
  onText(handler: (msg: string) => void): () => void {
    return this._client.on(event => {
      if (event.type !== 'message') return;
      const data = event.message.data;
      if (data.type !== 'forward') return;
      const inner = data.data;
      if (inner.encoding !== 'text') return;
      handler(inner.data);
    });
  }

  /** Subscribe to `Forward::Json` from the daemon. */
  onJson(handler: (msg: unknown) => void): () => void {
    return this._client.on(event => {
      if (event.type !== 'message') return;
      const data = event.message.data;
      if (data.type !== 'forward') return;
      const inner = data.data;
      if (inner.encoding !== 'json') return;
      handler(inner.data);
    });
  }

  /** Subscribe to `Forward::Binary` from the daemon. */
  onBinary(handler: (msg: Uint8Array) => void): () => void {
    return this._client.on(event => {
      if (event.type !== 'message') return;
      const data = event.message.data;
      if (data.type !== 'forward') return;
      const inner = data.data;
      if (inner.encoding !== 'binary') return;
      handler(inner.data);
    });
  }

  /** Exhaustive subscribe over all inbound `Forward` variants. */
  subscribe(handlers: ForwardInboundHandlers): () => void {
    return this._subscribe(handlers, false);
  }

  /** Same as `subscribe` but every handler is optional. */
  subscribePartial(handlers: Partial<ForwardInboundHandlers>): () => void {
    return this._subscribe(handlers, true);
  }

  private _subscribe(handlers: Partial<ForwardInboundHandlers>, partial: boolean): () => void {
    return this._client.on(event => {
      if (event.type !== 'message') return;
      const data = event.message.data;
      if (data.type !== 'forward') return;
      const inner = data.data;
      switch (inner.encoding) {
        case 'text': {
          handlers.text?.(inner.data);
          return;
        }
        case 'json': {
          handlers.json?.(inner.data);
          return;
        }
        case 'binary': {
          handlers.binary?.(inner.data);
          return;
        }
        default: {
          if (!partial) this._client.logger.warn('Forward: no handler for inner', inner);
          return;
        }
      }
    });
  }

  /** Send `Forward::Text` to the daemon. */
  async text(payload: string): Promise<void> {
    const msg: ClientToBridgeMsg = {
      id: newUuidBytes(),
      meta: { kind: 'event' },
      data: { type: 'forward', data: { encoding: 'text', data: payload } },
    };
    await this._client.send(msg);
  }

  /** Send `Forward::Json` to the daemon. */
  async json(payload: unknown): Promise<void> {
    const msg: ClientToBridgeMsg = {
      id: newUuidBytes(),
      meta: { kind: 'event' },
      data: { type: 'forward', data: { encoding: 'json', data: payload } },
    };
    await this._client.send(msg);
  }

  /** Send `Forward::Binary` to the daemon. */
  async binary(payload: Uint8Array): Promise<void> {
    const msg: ClientToBridgeMsg = {
      id: newUuidBytes(),
      meta: { kind: 'event' },
      data: { type: 'forward', data: { encoding: 'binary', data: payload } },
    };
    await this._client.send(msg);
  }
}

export class VoiceSurface {
  constructor(private readonly _client: BridgethingClient) {}

  /** Send `Voice::Cancel` to the daemon. */
  async cancel(): Promise<void> {
    const msg: ClientToBridgeMsg = {
      id: newUuidBytes(),
      meta: { kind: 'command' },
      data: { type: 'voice', data: { event: 'cancel' } },
    };
    await this._client.send(msg);
  }

  /** Send `Voice::PushToTalk` to the daemon. */
  async pushToTalk(): Promise<void> {
    const msg: ClientToBridgeMsg = {
      id: newUuidBytes(),
      meta: { kind: 'command' },
      data: { type: 'voice', data: { event: 'pushToTalk' } },
    };
    await this._client.send(msg);
  }

  /** Send `Voice::MuteMic` to the daemon. */
  async muteMic(payload: MicMute): Promise<void> {
    const msg: ClientToBridgeMsg = {
      id: newUuidBytes(),
      meta: { kind: 'command' },
      data: { type: 'voice', data: { event: 'muteMic', data: payload } },
    };
    await this._client.send(msg);
  }

  /** Send `Voice::UnmuteMic` to the daemon. */
  async unmuteMic(payload: MicUnmute): Promise<void> {
    const msg: ClientToBridgeMsg = {
      id: newUuidBytes(),
      meta: { kind: 'command' },
      data: { type: 'voice', data: { event: 'unmuteMic', data: payload } },
    };
    await this._client.send(msg);
  }
}

export class InteractionSurface {
  constructor(private readonly _client: BridgethingClient) {}

  /** Send `Interaction::PhoneAnswer` to the daemon. */
  async phoneAnswer(): Promise<void> {
    const msg: ClientToBridgeMsg = {
      id: newUuidBytes(),
      meta: { kind: 'command' },
      data: { type: 'interaction', data: { event: 'phoneAnswer' } },
    };
    await this._client.send(msg);
  }

  /** Send `Interaction::PhoneDecline` to the daemon. */
  async phoneDecline(): Promise<void> {
    const msg: ClientToBridgeMsg = {
      id: newUuidBytes(),
      meta: { kind: 'command' },
      data: { type: 'interaction', data: { event: 'phoneDecline' } },
    };
    await this._client.send(msg);
  }

  /** Send `Interaction::PhoneCallImage` to the daemon. */
  async phoneCallImage(payload: PhoneCallImage): Promise<void> {
    const msg: ClientToBridgeMsg = {
      id: newUuidBytes(),
      meta: { kind: 'command' },
      data: { type: 'interaction', data: { event: 'phoneCallImage', data: payload } },
    };
    await this._client.send(msg);
  }

  /** Send `Interaction::PhoneCallMessage` to the daemon. */
  async phoneCallMessage(payload: PhoneCallMessage): Promise<void> {
    const msg: ClientToBridgeMsg = {
      id: newUuidBytes(),
      meta: { kind: 'command' },
      data: { type: 'interaction', data: { event: 'phoneCallMessage', data: payload } },
    };
    await this._client.send(msg);
  }

  /** Send `Interaction::IncreaseVolume` to the daemon. */
  async increaseVolume(): Promise<void> {
    const msg: ClientToBridgeMsg = {
      id: newUuidBytes(),
      meta: { kind: 'command' },
      data: { type: 'interaction', data: { event: 'increaseVolume' } },
    };
    await this._client.send(msg);
  }

  /** Send `Interaction::DecreaseVolume` to the daemon. */
  async decreaseVolume(): Promise<void> {
    const msg: ClientToBridgeMsg = {
      id: newUuidBytes(),
      meta: { kind: 'command' },
      data: { type: 'interaction', data: { event: 'decreaseVolume' } },
    };
    await this._client.send(msg);
  }

  /** Send `Interaction::MuteToggle` to the daemon. */
  async muteToggle(): Promise<void> {
    const msg: ClientToBridgeMsg = {
      id: newUuidBytes(),
      meta: { kind: 'command' },
      data: { type: 'interaction', data: { event: 'muteToggle' } },
    };
    await this._client.send(msg);
  }

  /** Send `Interaction::SkipToIndex` to the daemon. */
  async skipToIndex(payload: SkipToIndex): Promise<void> {
    const msg: ClientToBridgeMsg = {
      id: newUuidBytes(),
      meta: { kind: 'command' },
      data: { type: 'interaction', data: { event: 'skipToIndex', data: payload } },
    };
    await this._client.send(msg);
  }

  /** Send `Interaction::SkipNext` to the daemon. */
  async skipNext(): Promise<void> {
    const msg: ClientToBridgeMsg = {
      id: newUuidBytes(),
      meta: { kind: 'command' },
      data: { type: 'interaction', data: { event: 'skipNext' } },
    };
    await this._client.send(msg);
  }

  /** Send `Interaction::SkipPrev` to the daemon. */
  async skipPrev(): Promise<void> {
    const msg: ClientToBridgeMsg = {
      id: newUuidBytes(),
      meta: { kind: 'command' },
      data: { type: 'interaction', data: { event: 'skipPrev' } },
    };
    await this._client.send(msg);
  }

  /** Send `Interaction::SeekTo` to the daemon. */
  async seekTo(payload: SeekTo): Promise<void> {
    const msg: ClientToBridgeMsg = {
      id: newUuidBytes(),
      meta: { kind: 'command' },
      data: { type: 'interaction', data: { event: 'seekTo', data: payload } },
    };
    await this._client.send(msg);
  }

  /** Send `Interaction::Pause` to the daemon. */
  async pause(): Promise<void> {
    const msg: ClientToBridgeMsg = {
      id: newUuidBytes(),
      meta: { kind: 'command' },
      data: { type: 'interaction', data: { event: 'pause' } },
    };
    await this._client.send(msg);
  }

  /** Send `Interaction::Resume` to the daemon. */
  async resume(): Promise<void> {
    const msg: ClientToBridgeMsg = {
      id: newUuidBytes(),
      meta: { kind: 'command' },
      data: { type: 'interaction', data: { event: 'resume' } },
    };
    await this._client.send(msg);
  }

  /** Send `Interaction::SetShuffle` to the daemon. */
  async setShuffle(payload: SetShuffle): Promise<void> {
    const msg: ClientToBridgeMsg = {
      id: newUuidBytes(),
      meta: { kind: 'command' },
      data: { type: 'interaction', data: { event: 'setShuffle', data: payload } },
    };
    await this._client.send(msg);
  }

  /** Send `Interaction::SetRepeat` to the daemon. */
  async setRepeat(payload: SetRepeat): Promise<void> {
    const msg: ClientToBridgeMsg = {
      id: newUuidBytes(),
      meta: { kind: 'command' },
      data: { type: 'interaction', data: { event: 'setRepeat', data: payload } },
    };
    await this._client.send(msg);
  }
}

export class StoreSurface {
  constructor(private readonly _client: BridgethingClient) {}

  /** Typed request to the daemon: webapp sends, daemon responds. */
  async get(req: KVGet, options?: { timeoutMs?: number }): Promise<TypedRequestResult<StorageResponse, never>> {
    const wireData: ClientToBridgeMsg['data'] = { type: 'store', data: { event: 'get', data: req } };
    const response = await this._client.request(wireData, options?.timeoutMs);
    const d = response.data;
    if (d.type === 'store') {
      const inner = d.data;
      if (inner.event === 'response') return { ok: true, response: inner.data };
    }
    if (d.type === 'error') return { ok: false, kind: 'protocol', error: d.data };
    return { ok: false, kind: 'protocol', error: { type: 'unsupported' } };
  }

  /** Typed request to the daemon: webapp sends, daemon responds. */
  async put(req: KVPut, options?: { timeoutMs?: number }): Promise<TypedRequestResult<StorageResponse, never>> {
    const wireData: ClientToBridgeMsg['data'] = { type: 'store', data: { event: 'put', data: req } };
    const response = await this._client.request(wireData, options?.timeoutMs);
    const d = response.data;
    if (d.type === 'store') {
      const inner = d.data;
      if (inner.event === 'response') return { ok: true, response: inner.data };
    }
    if (d.type === 'error') return { ok: false, kind: 'protocol', error: d.data };
    return { ok: false, kind: 'protocol', error: { type: 'unsupported' } };
  }

  /** Typed request to the daemon: webapp sends, daemon responds. */
  async delete(req: KVDelete, options?: { timeoutMs?: number }): Promise<TypedRequestResult<StorageResponse, never>> {
    const wireData: ClientToBridgeMsg['data'] = { type: 'store', data: { event: 'delete', data: req } };
    const response = await this._client.request(wireData, options?.timeoutMs);
    const d = response.data;
    if (d.type === 'store') {
      const inner = d.data;
      if (inner.event === 'response') return { ok: true, response: inner.data };
    }
    if (d.type === 'error') return { ok: false, kind: 'protocol', error: d.data };
    return { ok: false, kind: 'protocol', error: { type: 'unsupported' } };
  }
}

export type ClientMessageHandlers = {
  asset: AssetInboundHandlers;
  bluetooth: BluetoothInboundHandlers;
  system: SystemInboundHandlers;
  player: PlayerInboundHandlers;
  peer: PeerInboundHandlers;
  forward: ForwardInboundHandlers;
};

export type PartialClientMessageHandlers = {
  asset?: Partial<AssetInboundHandlers>;
  bluetooth?: Partial<BluetoothInboundHandlers>;
  system?: Partial<SystemInboundHandlers>;
  player?: Partial<PlayerInboundHandlers>;
  peer?: Partial<PeerInboundHandlers>;
  forward?: Partial<ForwardInboundHandlers>;
};

declare module './index' {
  interface BridgethingClient {
    /** Methods scoped to the `Asset` wire surface. */
    readonly asset: AssetSurface;
    /** Methods scoped to the `Bluetooth` wire surface. */
    readonly bluetooth: BluetoothSurface;
    /** Methods scoped to the `System` wire surface. */
    readonly system: SystemSurface;
    /** Methods scoped to the `Player` wire surface. */
    readonly player: PlayerSurface;
    /** Methods scoped to the `Peer` wire surface. */
    readonly peer: PeerSurface;
    /** Methods scoped to the `Forward` wire surface. */
    readonly forward: ForwardSurface;
    /** Methods scoped to the `Voice` wire surface. */
    readonly voice: VoiceSurface;
    /** Methods scoped to the `Interaction` wire surface. */
    readonly interaction: InteractionSurface;
    /** Methods scoped to the `Store` wire surface. */
    readonly store: StoreSurface;
    /** Exhaustive subscribe across every inbound wire surface. */
    subscribe(handlers: ClientMessageHandlers): () => void;
    subscribePartial(handlers: PartialClientMessageHandlers): () => void;
  }
}

type ClientSurfaceCache = {
  asset?: AssetSurface;
  bluetooth?: BluetoothSurface;
  system?: SystemSurface;
  player?: PlayerSurface;
  peer?: PeerSurface;
  forward?: ForwardSurface;
  voice?: VoiceSurface;
  interaction?: InteractionSurface;
  store?: StoreSurface;
};

/**
 * Apply codegen-emitted prototype augmentations to BridgethingClient.
 * Called once from `index.ts` after the class definition. Idempotent.
 */
export function applyDispatch(): void {
  const surfaceCache = new WeakMap<BridgethingClient, ClientSurfaceCache>();
  function bucketFor(c: BridgethingClient): ClientSurfaceCache {
    let bucket = surfaceCache.get(c);
    if (!bucket) {
      bucket = {};
      surfaceCache.set(c, bucket);
    }
    return bucket;
  }

  Object.defineProperty(BridgethingClient.prototype, 'asset', {
    configurable: true,
    enumerable: true,
    get(this: BridgethingClient): AssetSurface {
      const bucket = bucketFor(this);
      return (bucket.asset ??= new AssetSurface(this));
    },
  });
  Object.defineProperty(BridgethingClient.prototype, 'bluetooth', {
    configurable: true,
    enumerable: true,
    get(this: BridgethingClient): BluetoothSurface {
      const bucket = bucketFor(this);
      return (bucket.bluetooth ??= new BluetoothSurface(this));
    },
  });
  Object.defineProperty(BridgethingClient.prototype, 'system', {
    configurable: true,
    enumerable: true,
    get(this: BridgethingClient): SystemSurface {
      const bucket = bucketFor(this);
      return (bucket.system ??= new SystemSurface(this));
    },
  });
  Object.defineProperty(BridgethingClient.prototype, 'player', {
    configurable: true,
    enumerable: true,
    get(this: BridgethingClient): PlayerSurface {
      const bucket = bucketFor(this);
      return (bucket.player ??= new PlayerSurface(this));
    },
  });
  Object.defineProperty(BridgethingClient.prototype, 'peer', {
    configurable: true,
    enumerable: true,
    get(this: BridgethingClient): PeerSurface {
      const bucket = bucketFor(this);
      return (bucket.peer ??= new PeerSurface(this));
    },
  });
  Object.defineProperty(BridgethingClient.prototype, 'forward', {
    configurable: true,
    enumerable: true,
    get(this: BridgethingClient): ForwardSurface {
      const bucket = bucketFor(this);
      return (bucket.forward ??= new ForwardSurface(this));
    },
  });
  Object.defineProperty(BridgethingClient.prototype, 'voice', {
    configurable: true,
    enumerable: true,
    get(this: BridgethingClient): VoiceSurface {
      const bucket = bucketFor(this);
      return (bucket.voice ??= new VoiceSurface(this));
    },
  });
  Object.defineProperty(BridgethingClient.prototype, 'interaction', {
    configurable: true,
    enumerable: true,
    get(this: BridgethingClient): InteractionSurface {
      const bucket = bucketFor(this);
      return (bucket.interaction ??= new InteractionSurface(this));
    },
  });
  Object.defineProperty(BridgethingClient.prototype, 'store', {
    configurable: true,
    enumerable: true,
    get(this: BridgethingClient): StoreSurface {
      const bucket = bucketFor(this);
      return (bucket.store ??= new StoreSurface(this));
    },
  });

  BridgethingClient.prototype.subscribe = function (handlers: ClientMessageHandlers): () => void {
    return outerSubscribe(this, handlers, false);
  };
  BridgethingClient.prototype.subscribePartial = function (handlers: PartialClientMessageHandlers): () => void {
    return outerSubscribe(this, handlers, true);
  };
}

function outerSubscribe(c: BridgethingClient, handlers: PartialClientMessageHandlers, partial: boolean): () => void {
  return c.on((event: ClientEvent) => {
    if (event.type !== 'message') return;
    const data = event.message.data;
    switch (data.type) {
      case 'asset': {
        const innerHandlers = handlers.asset;
        if (!innerHandlers) {
          if (!partial) c.logger.warn('subscribe: no handler for asset');
          return;
        }
        const inner = data.data;
        switch (inner.event) {
          case 'got': {
            innerHandlers.got?.(inner.data);
            return;
          }
          case 'notFound': {
            innerHandlers.notFound?.(inner.data);
            return;
          }
          case 'ready': {
            innerHandlers.ready?.(inner.data);
            return;
          }
          case 'cleared': {
            innerHandlers.cleared?.(inner.data);
            return;
          }
          default: {
            if (!partial) c.logger.warn('Asset: no handler for inner', inner);
            return;
          }
        }
      }
      case 'bluetooth': {
        const innerHandlers = handlers.bluetooth;
        if (!innerHandlers) {
          if (!partial) c.logger.warn('subscribe: no handler for bluetooth');
          return;
        }
        const inner = data.data;
        switch (inner.event) {
          case 'status': {
            innerHandlers.status?.(inner.data);
            return;
          }
          case 'connectedDevice': {
            innerHandlers.connectedDevice?.(inner.data);
            return;
          }
          case 'interface': {
            innerHandlers.interface?.(inner.data);
            return;
          }
          case 'pairingResult': {
            innerHandlers.pairingResult?.(inner.data);
            return;
          }
          case 'pin': {
            innerHandlers.pin?.(inner.data);
            return;
          }
          case 'pairedDevices': {
            innerHandlers.pairedDevices?.(inner.data);
            return;
          }
          default: {
            if (!partial) c.logger.warn('Bluetooth: no handler for inner', inner);
            return;
          }
        }
      }
      case 'system': {
        const innerHandlers = handlers.system;
        if (!innerHandlers) {
          if (!partial) c.logger.warn('subscribe: no handler for system');
          return;
        }
        const inner = data.data;
        switch (inner.event) {
          case 'version': {
            innerHandlers.version?.(inner.data);
            return;
          }
          case 'gatewayStatus': {
            innerHandlers.gatewayStatus?.(inner.data);
            return;
          }
          case 'otaReboot': {
            innerHandlers.otaReboot?.(inner.data);
            return;
          }
          case 'otaPowerOff': {
            innerHandlers.otaPowerOff?.(inner.data);
            return;
          }
          case 'ambientLightUpdate': {
            innerHandlers.ambientLightUpdate?.(inner.data);
            return;
          }
          case 'phoneCallInfo': {
            innerHandlers.phoneCallInfo?.(inner.data);
            return;
          }
          default: {
            if (!partial) c.logger.warn('System: no handler for inner', inner);
            return;
          }
        }
      }
      case 'player': {
        const innerHandlers = handlers.player;
        if (!innerHandlers) {
          if (!partial) c.logger.warn('subscribe: no handler for player');
          return;
        }
        const inner = data.data;
        switch (inner.event) {
          case 'playerIdle': {
            innerHandlers.playerIdle?.();
            return;
          }
          case 'playerState': {
            innerHandlers.playerState?.(inner.data);
            return;
          }
          case 'queue': {
            innerHandlers.queue?.(inner.data);
            return;
          }
          case 'image': {
            innerHandlers.image?.(inner.data);
            return;
          }
          default: {
            if (!partial) c.logger.warn('Player: no handler for inner', inner);
            return;
          }
        }
      }
      case 'peer': {
        const innerHandlers = handlers.peer;
        if (!innerHandlers) {
          if (!partial) c.logger.warn('subscribe: no handler for peer');
          return;
        }
        const inner = data.data;
        switch (inner.event) {
          case 'snapshot': {
            innerHandlers.snapshot?.(inner.data);
            return;
          }
          default: {
            if (!partial) c.logger.warn('Peer: no handler for inner', inner);
            return;
          }
        }
      }
      case 'forward': {
        const innerHandlers = handlers.forward;
        if (!innerHandlers) {
          if (!partial) c.logger.warn('subscribe: no handler for forward');
          return;
        }
        const inner = data.data;
        switch (inner.encoding) {
          case 'text': {
            innerHandlers.text?.(inner.data);
            return;
          }
          case 'json': {
            innerHandlers.json?.(inner.data);
            return;
          }
          case 'binary': {
            innerHandlers.binary?.(inner.data);
            return;
          }
          default: {
            if (!partial) c.logger.warn('Forward: no handler for inner', inner);
            return;
          }
        }
      }
      default: {
        if (!partial) c.logger.warn('subscribe: no handler for unknown wire variant', data);
        return;
      }
    }
  });
}
