// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Device, Peer, PhoneCallDirection, PhoneCallStatus, PlaybackOptions, PlaybackRestrictions, RepeatMode, Track } from "./shared";

export type AmbientLightUpdate = { brightness: number, };

export type AssetCleared = { id: string, };

export type AssetGot = { requestId: string, id: string, bytes: Uint8Array, mime: string | null, };

export type AssetNotFound = { requestId: string, id: string, };

export type AssetReady = { id: string, };

export type AssetReady = { id: string, };

export type BluetoothInterface = { mac: string, name: string, interface: string, };

export type BluetoothPairingResult = { success: boolean, };

export type BluetoothPin = { mac: string, name: string, pin: string, };

export type BluetoothStatus = { connected: boolean, };

/**
 * Daemon-side asset events. `Got` and `NotFound` resolve a webapp `Get`
 * (correlated by request_id). `Ready` broadcasts to all connected
 * webapps whenever the cache gains an asset, regardless of source
 * (companion push, iAP2 FileTransfer, request fulfilment, lazy disk
 * load). `Cleared` broadcasts on every eviction path - LRU pressure,
 * TTL expiry, companion-issued Clear, daemon shutdown - so SDK
 * consumers can drop Blob URLs and refetch as needed.
 */
export type BridgeToClientAssetMsg = { "event": "got", "data": AssetGot } | { "event": "notFound", "data": AssetNotFound } | { "event": "ready", "data": AssetReady } | { "event": "cleared", "data": AssetCleared };

export type BridgeToClientBluetoothMsg = { "event": "status", "data": BluetoothStatus } | { "event": "connectedDevice", "data": ConnectedDevice } | { "event": "interface", "data": BluetoothInterface } | { "event": "pairingResult", "data": BluetoothPairingResult } | { "event": "pin", "data": BluetoothPin } | { "event": "pairedDevices", "data": PairedDevicesMap };

/**
 * Daemon → webapp interaction events. None defined yet; the variant
 * exists on the outer wire so the surface is reserved for future
 * daemon-pushed UI hints (haptic prompt, focus change, etc.).
 */
export type BridgeToClientInteractionMsg = never;

export type BridgeToClientPeerMsg = { "event": "snapshot", "data": PeerSnapshotMap };

export type BridgeToClientPlayerMsg = { "event": "playerIdle" } | { "event": "playerState", "data": PlayerState } | { "event": "queue", "data": PlayerQueue } | { "event": "image", "data": PlayerImage };

export type BridgeToClientStoreMsg = { "event": "response", "data": StorageResponse };

export type ClientToBridgeBluetoothMsg = { "event": "list" } | { "event": "connect", "data": ConnectBluetooth } | { "event": "scan" } | { "event": "enableDiscoverable" } | { "event": "disableDiscoverable" } | { "event": "pair", "data": PairBluetooth } | { "event": "forget", "data": ForgetBluetooth } | { "event": "enablePan", "data": EnablePan } | { "event": "disablePan", "data": DisablePan } | { "event": "setAlias", "data": SetBluetoothAlias };

export type ClientToBridgeBluetoothMsg = { "event": "list" } | { "event": "connect", "data": ConnectBluetooth } | { "event": "scan" } | { "event": "enableDiscoverable" } | { "event": "disableDiscoverable" } | { "event": "pair", "data": PairBluetooth } | { "event": "forget", "data": ForgetBluetooth } | { "event": "enablePan", "data": EnablePan } | { "event": "disablePan", "data": DisablePan } | { "event": "setAlias", "data": SetBluetoothAlias };

export type ClientToBridgeInteractionMsg = { "event": "phoneAnswer" } | { "event": "phoneDecline" } | { "event": "phoneCallImage", "data": PhoneCallImage } | { "event": "phoneCallMessage", "data": PhoneCallMessage } | { "event": "increaseVolume" } | { "event": "decreaseVolume" } | { "event": "muteToggle" } | { "event": "skipToIndex", "data": SkipToIndex } | { "event": "skipNext" } | { "event": "skipPrev" } | { "event": "seekTo", "data": SeekTo } | { "event": "pause" } | { "event": "resume" } | { "event": "setShuffle", "data": SetShuffle } | { "event": "setRepeat", "data": SetRepeat };

export type ClientToBridgeStoreMsg = { "event": "get", "data": KVGet } | { "event": "put", "data": KVPut } | { "event": "delete", "data": KVDelete };

export type ClientToBridgeSystemMsg = { "event": "versionRequest" } | { "event": "gatewayStatusRequest" } | { "event": "reboot" } | { "event": "powerOff" } | { "event": "factoryReset" } | { "event": "phoneCallAccept", "data": PhoneCallAccept } | { "event": "phoneCallEnd", "data": PhoneCallEnd };

export type ClientToBridgeSystemMsg = { "event": "versionRequest" } | { "event": "gatewayStatusRequest" } | { "event": "reboot" } | { "event": "powerOff" } | { "event": "factoryReset" } | { "event": "phoneCallAccept", "data": PhoneCallAccept } | { "event": "phoneCallEnd", "data": PhoneCallEnd };

export type ClientToBridgeVoiceMsg = { "event": "cancel" } | { "event": "pushToTalk" } | { "event": "muteMic", "data": MicMute } | { "event": "unmuteMic", "data": MicUnmute };

export type ClientToBridgeVoiceMsg = { "event": "cancel" } | { "event": "pushToTalk" } | { "event": "muteMic", "data": MicMute } | { "event": "unmuteMic", "data": MicUnmute };

export type ConnectBluetooth = { mac: string, };

export type ConnectBluetooth = { mac: string, };

export type ConnectedDevice = { name: string, mac: string, };

export type ForgetBluetooth = { mac: string, };

export type ForgetBluetooth = { mac: string, };

export type GatewayStatus = { address: string, connected: boolean, adapterVersion: string, libVersion: string, libbridgethingVersion: string, appName: string, appVersion: string, osName: string, };

export type GatewayStatus = { address: string, connected: boolean, adapterVersion: string, libVersion: string, libbridgethingVersion: string, appName: string, appVersion: string, osName: string, };

/**
 * Webapp request: delete the KV storage entry at `key`.
 */
export type KVDelete = { key: string, };

/**
 * Webapp request: delete the KV storage entry at `key`.
 */
export type KVDelete = { key: string, };

export type MicUnmute = { preserve: boolean, };

export type OtaPowerOff = { delayMs: number, };

export type OtaPowerOff = { delayMs: number, };

export type PairBluetooth = { mac: string, };

/**
 * Map of MAC string → `Device`. Wraps `HashMap` so codegen has a named
 * type to import for the typed request response.
 */
export type PairedDevicesMap = { [key in string]: Device };

/**
 * Map of peer-id → `Peer`. Wraps `HashMap` so codegen has a named type
 * to expose for inbound listeners.
 */
export type PeerSnapshotMap = { [key in string]: Peer };

export type PhoneCallAccept = { callId: string, };

export type PhoneCallEnd = { callId: string, };

export type PhoneCallEnd = { callId: string, };

export type PhoneCallImage = { phoneNumber: string, };

export type PhoneCallInfo = { remoteId: string, displayName: string, status: PhoneCallStatus, callDir: PhoneCallDirection, callId: string, };

export type PhoneCallInfo = { remoteId: string, displayName: string, status: PhoneCallStatus, callDir: PhoneCallDirection, callId: string, };

export type PhoneCallInfo = { remoteId: string, displayName: string, status: PhoneCallStatus, callDir: PhoneCallDirection, callId: string, };
ring, };
tring, };
atMode: RepeatMode, };
neCallMessage = { phoneNumber: string, message: string, };
 callDir: PhoneCallDirection, callId: string, };
ring, };
tring, };
g, };

export type PlayerImage = { id: string, height: number, width: number, data: string, };

export type PlayerQueue = { next: Array<Track>, current: Track, previous: Array<Track>, };

export type PlayerState = { contextId: string, contextTitle: string, isPaused: boolean, playbackOptions: PlaybackOptions, playbackPosition: number, playbackRestrictions: PlaybackRestrictions, playbackSpeed: number, track: Track, };

export type PlayerState = { contextId: string, contextTitle: string, isPaused: boolean, playbackOptions: PlaybackOptions, playbackPosition: number, playbackRestrictions: PlaybackRestrictions, playbackSpeed: number, track: Track, };

export type SeekTo = { positionMs: number, };

export type SeekTo = { positionMs: number, };

export type SetBluetoothAlias = { name: string, };

export type SetBluetoothAlias = { name: string, };

export type SetRepeat = { repeatMode: RepeatMode, };

export type SetRepeat = { repeatMode: RepeatMode, };

export type SkipToIndex = { index: number, };
 number, };

export type StorageResponse = { key: string, value: string | null, };
r, };
 number, };
};
umber, };

export type StorageResponse = { key: string, value: string | null, };
r, };
 number, };
};
 number, };
};
