// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BridgeThingMeta, ForwardMessage, GatewayMeta, WebappInfo } from "./shared";

export type BridgeFile = { path: string, data: Uint8Array, };

/**
 * Bridge-side request for a runtime file the gateway has access to.
 * Triggered by HTTP misses inside the `/_gateway/` namespace. The gateway
 * replies with `GatewayToBridgeFileMsg::FileResponse`.
 */
export type BridgeToGatewayFileMsg = { "event": "fileRequest", "data": FileRequestData };

/**
 * bridgething -> gateway
 * messages from bridgething to the gateway (mobile or desktop app).
 *
 * these messages will pass over bluetooth.
 */
export type BridgeToGatewayMsg = { id: Uint8Array, meta: GatewayMsgMeta, data: BridgeToGatewayMsgData, };

export type BridgeToGatewayMsgData = { "type": "version", "data": BridgeThingMeta } | { "type": "file", "data": BridgeToGatewayFileMsg } | { "type": "webapp", "data": BridgeToGatewayWebappMsg } | { "type": "forward", "data": ForwardMessage } | { "type": "error", "data": GatewayError } | { "type": "ack" } | { "type": "done" };

export type BridgeToGatewayWebappMsg = { "event": "webapps", "data": WebappList } | { "event": "active", "data": WebappActive } | { "event": "switched", "data": WebappActive } | { "event": "installed", "data": WebappInfo } | { "event": "uninstalled", "data": WebappActive } | { "event": "webappError", "data": WebappError };

export type ChromeNavigate = { url: string, };

export type FileRequestData = { file: string, };

export type FileResponseData = { file: BridgeFile, };

/**
 * Protocol-level failure that the bridge ships when a request could not be
 * reached or dispatched. Carried by `BridgeToGatewayMsgData::Error`.
 *
 * Domain-level errors (predictable, op-specific failures the caller may want
 * to recover from) live inside the per-op response variant — for example
 * `BridgeToGatewayWebappMsg::WebappError(WebappError)`.
 */
export type GatewayError = { "type": "unsupported" } | { "type": "malformed", "data": { reason: string, } } | { "type": "handlerFailed", "data": { reason: string, } };

export type GatewayMsgMeta = { "kind": "command" } | { "kind": "event" } | { "kind": "request" } | { "kind": "response", "data": ResponseMeta };

export type GatewayToBridgeChromeMsg = { "event": "navigate", "data": ChromeNavigate };

/**
 * Gateway-served runtime file fetches. The bridge requests an asset on a
 * `_gateway/<path>` HTTP miss; the gateway responds with the bytes if it
 * has them.
 */
export type GatewayToBridgeFileMsg = { "event": "fileResponse", "data": FileResponseData };

/**
 * gateway -> bridgething
 * messages from the gateway (mobile or desktop app) to bridgething.
 *
 * these messages will pass over bluetooth.
 */
export type GatewayToBridgeMsg = { id: Uint8Array, meta: GatewayMsgMeta, data: GatewayToBridgeMsgData, };

export type GatewayToBridgeMsgData = { "type": "version", "data": GatewayMeta } | { "type": "file", "data": GatewayToBridgeFileMsg } | { "type": "chrome", "data": GatewayToBridgeChromeMsg } | { "type": "webapp", "data": GatewayToBridgeWebappMsg } | { "type": "forward", "data": ForwardMessage } | { "type": "error", "data": GatewayError };

export type GatewayToBridgeWebappMsg = { "event": "list" } | { "event": "getActive" } | { "event": "switchTo", "data": WebappSwitchTo } | { "event": "install", "data": WebappInstall } | { "event": "uninstall", "data": WebappUninstall };

export type ResponseMeta = { requestId: Uint8Array, };

export type WebappActive = { name: string, };

export type WebappError = { "type": "unknownWebapp", "data": { name: string, } } | { "type": "cannotUninstallBuiltin", "data": { name: string, } } | { "type": "installFailed", "data": { reason: string, } };

export type WebappInstall = { name: string, 
/**
 * zip archive whose top-level entries become the bundle contents.
 * Must include an `index.html` at the archive root.
 */
archive: Uint8Array, };

export type WebappList = { webapps: Array<WebappInfo>, };

export type WebappSwitchTo = { name: string, };

export type WebappUninstall = { name: string, };
