// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type {
  AssetRetention,
  BridgeThingMeta,
  BrowseResult,
  CallEndReason,
  CompanionAuthorityScope,
  DismissReason,
  FavoritesPage,
  ForwardMessage,
  GatewayCapabilities,
  GeoAccuracy,
  GeoError,
  HttpHeader,
  ItemKind,
  ItemRef,
  LibraryError,
  NetError,
  NetFetchRequest,
  NetFetchResponse,
  NetFetchStreamBegin,
  NetFetchStreamChunk,
  NetFetchStreamEnd,
  Notification,
  NotificationError,
  NotificationsPage,
  NowPlayingUpdate,
  PhoneCall,
  PhoneState,
  PlayContext,
  PlayerState,
  Position,
  QueueItem,
  QueuePosition,
  RecommendationsResult,
  RepeatMode,
  SearchResult,
  TimeInfo,
  WebappInfo,
  WsError,
  WsFrame,
} from './shared';
import type { MsgMeta, WireError } from './wire';

export type AssetClear = { id: string };

/**
 * Typed response payload for an `AssetRequest`. Mirrors `AssetPush`
 * without the retention hint - the daemon picks retention for assets
 * it asked for, since the lifecycle is request-scoped rather than
 * companion-managed.
 */
export type AssetGotReply = { id: string; bytes: Uint8Array; mime: string | null };

/**
 * Domain error response for an `AssetRequest`: the companion does not
 * have the requested asset.
 */
export type AssetNotFoundReply = { id: string };

/**
 * Single-frame asset push for small, latency-critical, memory-resident
 * assets (album art). Daemon-side checks: `bytes.len()` must be
 * <= `ASSET_PUSH_SINGLE_FRAME_MAX_BYTES` and `retention` must NOT be
 * `Persistent`. Larger payloads or persistent retention require the
 * chunked `PushBegin`/`PushChunk` flow.
 */
export type AssetPush = { id: string; bytes: Uint8Array; mime: string | null; retention: AssetRetention };

/**
 * Drop the daemon-side partial for `id`. The companion's escape hatch
 * when it wants to clean up a push it can no longer complete.
 */
export type AssetPushAbandon = { id: string };

/**
 * Open or resume a chunked asset push. Daemon responds with
 * `AssetPushBeginAck { resume_from_offset }` (the byte offset the next
 * `AssetPushChunk` should start at, 0 for fresh pushes) or
 * `AssetPushBeginRejected { reason }` (conflicting in-flight id with
 * mismatched size/sha, budget exhausted, etc.).
 *
 * Required for any push with `retention = Persistent` and for any push
 * larger than `ASSET_PUSH_SINGLE_FRAME_MAX_BYTES`.
 */
export type AssetPushBegin = {
  id: string;
  expectedSize: number;
  expectedSha256: string | null;
  mime: string | null;
  retention: AssetRetention;
};

/**
 * Successful response to `AssetPushBegin`. `resume_from_offset` is the
 * byte offset the next `AssetPushChunk` should start at: 0 for fresh
 * pushes, or the daemon's recovered partial length for a resume.
 */
export type AssetPushBeginAck = { resumeFromOffset: number };

/**
 * Domain-error response to `AssetPushBegin`: the daemon refuses to
 * start or resume this push (conflicting in-flight id, budget
 * exhausted, oversized, etc.).
 */
export type AssetPushBeginRejected = { reason: string };

/**
 * Streaming chunk of an asset push opened by `AssetPushBegin`.
 * `offset` must equal the daemon's current `received` for this id.
 * `last:true` triggers post-stream verify (size + optional sha256)
 * and commit to the asset cache.
 */
export type AssetPushChunk = { id: string; offset: number; bytes: Uint8Array; last: boolean };

export type AssetRequest = { id: string; requestId: Uint8Array };

export type AuthorityClaim = { scope: CompanionAuthorityScope };

export type AuthorityRelease = { scope: CompanionAuthorityScope };

export type BridgeToGatewayAssetMsg =
  | { event: 'request'; data: AssetRequest }
  | { event: 'pushBeginAck'; data: AssetPushBeginAck }
  | { event: 'pushBeginRejected'; data: AssetPushBeginRejected };

export type BridgeToGatewayAudioMsg =
  | { event: 'volumeUp' }
  | { event: 'volumeDown' }
  | { event: 'setVolume'; data: SetVolume }
  | { event: 'muteToggle' }
  | { event: 'setMute'; data: SetMute }
  | { event: 'tts'; data: Tts }
  | { event: 'ttsCancel'; data: TtsCancel }
  | { event: 'ttsCancelAll' }
  | { event: 'earcon'; data: Earcon };

export type BridgeToGatewayGeoMsg =
  | { event: 'watch'; data: GeoWatch }
  | { event: 'unwatch' }
  | { event: 'getOnce'; data: GeoGetOnce };

export type BridgeToGatewayLibraryMsg =
  | { event: 'browse'; data: LibraryBrowseRequest }
  | { event: 'search'; data: LibrarySearchRequest }
  | { event: 'recommendations'; data: LibraryRecommendationsRequest }
  | { event: 'favoritesList'; data: LibraryFavoritesListRequest }
  | { event: 'favoritesToggle'; data: FavoritesToggle }
  | { event: 'favoritesSet'; data: FavoritesSet };

/**
 * bridgething -> gateway
 * messages from bridgething to the gateway (mobile or desktop app).
 *
 * these messages will pass over bluetooth.
 */
export type BridgeToGatewayMsg = { id: Uint8Array; meta: MsgMeta; data: BridgeToGatewayMsgData };

export type BridgeToGatewayMsgData =
  | { type: 'version'; data: BridgeThingMeta }
  | { type: 'asset'; data: BridgeToGatewayAssetMsg }
  | { type: 'audio'; data: BridgeToGatewayAudioMsg }
  | { type: 'geo'; data: BridgeToGatewayGeoMsg }
  | { type: 'library'; data: BridgeToGatewayLibraryMsg }
  | { type: 'net'; data: BridgeToGatewayNetMsg }
  | { type: 'notifications'; data: BridgeToGatewayNotificationsMsg }
  | { type: 'phone'; data: BridgeToGatewayPhoneMsg }
  | { type: 'player'; data: BridgeToGatewayPlayerMsg }
  | { type: 'system'; data: BridgeToGatewaySystemMsg }
  | { type: 'webapp'; data: BridgeToGatewayWebappMsg }
  | { type: 'forward'; data: ForwardMessage }
  | { type: 'error'; data: WireError }
  | { type: 'ack' }
  | { type: 'done' };

export type BridgeToGatewayNetMsg =
  | { event: 'fetch'; data: NetFetchRequestMsg }
  | { event: 'wsOpen'; data: NetWsOpen }
  | { event: 'wsClose'; data: NetWsClose }
  | { event: 'wsSend'; data: NetWsSend };

export type BridgeToGatewayNotificationsMsg =
  | { event: 'list'; data: NotificationsListRequest }
  | { event: 'invokePositive'; data: NotificationInvoke }
  | { event: 'invokeNegative'; data: NotificationInvoke };

export type BridgeToGatewayPhoneMsg =
  | { event: 'answer'; data: PhoneCallAction }
  | { event: 'decline'; data: PhoneCallAction }
  | { event: 'end'; data: PhoneCallAction }
  | { event: 'hold'; data: PhoneCallAction }
  | { event: 'unhold'; data: PhoneCallAction }
  | { event: 'stateGet' };

/**
 * Bridge → gateway player verbs. The companion-side SDK dispatches each
 * to its native player integration (Spotify SDK, Apple Music SDK,
 * MediaSession). Routing for `Play(uri)` is gated on
 * `Capabilities.uri_schemes` — daemon never forwards a URI no
 * connected gateway claims.
 */
export type BridgeToGatewayPlayerMsg =
  | { event: 'play'; data: PlayUri }
  | { event: 'queue'; data: QueueUri }
  | { event: 'pause' }
  | { event: 'resume' }
  | { event: 'skipNext' }
  | { event: 'skipPrev' }
  | { event: 'skipToIndex'; data: SkipToIndex }
  | { event: 'seekTo'; data: SeekTo }
  | { event: 'setShuffle'; data: SetShuffle }
  | { event: 'setRepeat'; data: SetRepeat }
  | { event: 'setSpeed'; data: SetSpeed }
  | { event: 'setCrossfade'; data: SetCrossfade };

export type BridgeToGatewaySystemMsg =
  | { event: 'otaProgress'; data: OtaProgress }
  | { event: 'otaError'; data: OtaError }
  | { event: 'otaBeginAck'; data: OtaBeginAck }
  | { event: 'otaBeginRejected'; data: OtaBeginRejected };

export type BridgeToGatewayWebappMsg =
  | { event: 'webapps'; data: WebappList }
  | { event: 'active'; data: WebappActive }
  | { event: 'switched'; data: WebappActive }
  | { event: 'installed'; data: WebappInfo }
  | { event: 'uninstalled'; data: WebappActive }
  | { event: 'webappError'; data: WebappError };

export type BrowseReply = { result: BrowseResult };

export type ChromeNavigate = { url: string };

/**
 * Play a named earcon from `AudioCapabilities.earcons`. Unknown names
 * surface as `AudioError::EarconNotFound`.
 */
export type Earcon = { name: string };

/**
 * Fired when the favorited / liked status of an item changes —
 * regardless of whether it was driven by the daemon (FavoritesToggle/Set
 * command) or by the user mutating it on the gateway-side app directly.
 */
export type FavoriteChanged = { uri: string; liked: boolean };

export type FavoritesListReply = { page: FavoritesPage };

export type FavoritesSet = { item: ItemRef; liked: boolean };

export type FavoritesToggle = { item: ItemRef };

export type GatewayToBridgeAssetMsg =
  | { event: 'push'; data: AssetPush }
  | { event: 'clear'; data: AssetClear }
  | { event: 'pushBegin'; data: AssetPushBegin }
  | { event: 'pushChunk'; data: AssetPushChunk }
  | { event: 'pushAbandon'; data: AssetPushAbandon }
  | { event: 'got'; data: AssetGotReply }
  | { event: 'notFound'; data: AssetNotFoundReply };

export type GatewayToBridgeAudioMsg =
  | { event: 'ttsStarted'; data: TtsStarted }
  | { event: 'ttsEnded'; data: TtsEnded }
  | { event: 'volumeChanged'; data: VolumeChanged };

/**
 * Companion declares per-scope authority. `Claim` is idempotent and may
 * be re-issued to refresh the freshness timestamp. `Release` is the
 * "stop preferring my data for this scope" signal. Stale claims fall
 * back automatically after `AUTHORITY_STALE_TIMEOUT_SECS` (default 5).
 */
export type GatewayToBridgeAuthorityMsg =
  | { event: 'claim'; data: AuthorityClaim }
  | { event: 'release'; data: AuthorityRelease };

/**
 * Companion-driven capabilities surface. The companion sends `Announce`
 * immediately on session-up (before any other surface activity) and
 * re-sends on any change. The daemon's PeerTracker flips
 * `companion_active` on receipt and seeds initial snapshots for every
 * surface where the companion is claiming authority.
 */
export type GatewayToBridgeCapabilitiesMsg = { event: 'announce'; data: GatewayCapabilities };

export type GatewayToBridgeChromeMsg = { event: 'navigate'; data: ChromeNavigate };

export type GatewayToBridgeGeoMsg =
  | { event: 'position'; data: Position }
  | { event: 'getOnceReply'; data: GeoGetOnceReply }
  | { event: 'errorReply'; data: GeoErrorReply };

export type GatewayToBridgeLibraryMsg =
  | { event: 'browseReply'; data: BrowseReply }
  | { event: 'searchReply'; data: SearchReply }
  | { event: 'recommendationsReply'; data: RecommendationsReply }
  | { event: 'favoritesListReply'; data: FavoritesListReply }
  | { event: 'libraryErrorReply'; data: LibraryErrorReply }
  | { event: 'favoriteChanged'; data: FavoriteChanged };

/**
 * gateway -> bridgething
 * messages from the gateway (mobile or desktop app) to bridgething.
 *
 * these messages will pass over bluetooth.
 */
export type GatewayToBridgeMsg = { id: Uint8Array; meta: MsgMeta; data: GatewayToBridgeMsgData };

export type GatewayToBridgeMsgData =
  | { type: 'asset'; data: GatewayToBridgeAssetMsg }
  | { type: 'audio'; data: GatewayToBridgeAudioMsg }
  | { type: 'authority'; data: GatewayToBridgeAuthorityMsg }
  | { type: 'capabilities'; data: GatewayToBridgeCapabilitiesMsg }
  | { type: 'chrome'; data: GatewayToBridgeChromeMsg }
  | { type: 'geo'; data: GatewayToBridgeGeoMsg }
  | { type: 'library'; data: GatewayToBridgeLibraryMsg }
  | { type: 'net'; data: GatewayToBridgeNetMsg }
  | { type: 'notifications'; data: GatewayToBridgeNotificationsMsg }
  | { type: 'phone'; data: GatewayToBridgePhoneMsg }
  | { type: 'player'; data: GatewayToBridgePlayerMsg }
  | { type: 'system'; data: GatewayToBridgeSystemMsg }
  | { type: 'time'; data: GatewayToBridgeTimeMsg }
  | { type: 'webapp'; data: GatewayToBridgeWebappMsg }
  | { type: 'error'; data: WireError };

export type GatewayToBridgeNetMsg =
  | { event: 'fetchReply'; data: NetFetchReply }
  | { event: 'fetchErrorReply'; data: NetFetchErrorReply }
  | { event: 'fetchStreamBegin'; data: NetFetchStreamBegin }
  | { event: 'fetchStreamChunk'; data: NetFetchStreamChunk }
  | { event: 'fetchStreamEnd'; data: NetFetchStreamEnd }
  | { event: 'wsOpenReply'; data: NetWsOpenReply }
  | { event: 'wsErrorReply'; data: NetWsErrorReply }
  | { event: 'wsOpened'; data: NetWsOpened }
  | { event: 'wsMessage'; data: NetWsMessage }
  | { event: 'wsClosed'; data: NetWsClosed }
  | { event: 'wsErrorEvent'; data: NetWsErrorEvent };

export type GatewayToBridgeNotificationsMsg =
  | { event: 'listReply'; data: NotificationsListReply }
  | { event: 'errorReply'; data: NotificationsErrorReply }
  | { event: 'posted'; data: Notification }
  | { event: 'updated'; data: Notification }
  | { event: 'removed'; data: NotificationRemoved };

export type GatewayToBridgePhoneMsg =
  | { event: 'snapshot'; data: PhoneStateReply }
  | { event: 'callStarted'; data: PhoneCall }
  | { event: 'callUpdated'; data: PhoneCall }
  | { event: 'callEnded'; data: PhoneCallEnded }
  | { event: 'stateReply'; data: PhoneStateReply };

/**
 * Gateway → bridge player events. `Snapshot` is the initial-state event
 * fired at announce when the companion claims player authority;
 * `Delta` is the ongoing partial-update stream (the only delta-shaped
 * event in the wire protocol — every other surface uses snapshots).
 * `QueueChanged` fires when the queue mutates without a track change
 * (companion-side reorder, prefetch).
 */
export type GatewayToBridgePlayerMsg =
  | { event: 'snapshot'; data: PlayerState }
  | { event: 'delta'; data: NowPlayingUpdate }
  | { event: 'queueChanged'; data: QueueSnapshot };

export type GatewayToBridgeSystemMsg =
  | { event: 'otaBegin'; data: OtaBegin }
  | { event: 'otaChunk'; data: OtaChunk }
  | { event: 'otaAbandon'; data: OtaAbandon }
  | { event: 'cancelUpdate' };

/**
 * Companion-driven time surface. Companion sends `Snapshot` at announce
 * (announce-on-connect rule for any surface where companion claims
 * authority — Time always seeds) and again on tz / locale / clock-skew
 * changes.
 */
export type GatewayToBridgeTimeMsg = { event: 'snapshot'; data: TimeInfo };

export type GatewayToBridgeWebappMsg =
  | { event: 'list' }
  | { event: 'getActive' }
  | { event: 'switchTo'; data: WebappSwitchTo }
  | { event: 'install'; data: WebappInstall }
  | { event: 'uninstall'; data: WebappUninstall };

export type GeoErrorReply = { error: GeoError };

export type GeoGetOnce = { accuracy: GeoAccuracy };

export type GeoGetOnceReply = { position: Position };

/**
 * Bridge → companion watch forward. The daemon aggregates webapp
 * watches and re-issues this with the most-demanding accuracy +
 * fastest interval. `min_interval_ms = 0` lets the gateway pick.
 */
export type GeoWatch = { accuracy: GeoAccuracy; minIntervalMs: number };

export type LibraryBrowseRequest = {
  /**
   * Drilldown node id from a prior `BrowseFolder`. `None` means "root".
   */
  nodeId: string | null;
  pageToken: string | null;
};

export type LibraryErrorReply = { error: LibraryError };

export type LibraryFavoritesListRequest = { pageToken: string | null };

export type LibraryRecommendationsRequest = {
  seed: ItemRef | null;
  kind: ItemKind | null;
  limit: number | null;
  pageToken: string | null;
};

export type LibrarySearchRequest = { query: string; kinds: Array<ItemKind> | null; pageToken: string | null };

export type NetFetchErrorReply = { error: NetError };

export type NetFetchReply = { response: NetFetchResponse };

export type NetFetchRequestMsg = { request: NetFetchRequest };

export type NetWsClose = { connectionId: Uint8Array; code: number | null; reason: string | null };

export type NetWsClosed = { connectionId: Uint8Array; code: number; reason: string };

export type NetWsErrorEvent = { connectionId: Uint8Array; error: WsError };

export type NetWsErrorReply = { error: WsError };

export type NetWsMessage = { connectionId: Uint8Array; frame: WsFrame };

export type NetWsOpen = { url: string; protocols: Array<string> | null; headers: Array<HttpHeader> | null };

export type NetWsOpenReply = { connectionId: Uint8Array; acceptedProtocol: string | null };

export type NetWsOpened = { connectionId: Uint8Array; acceptedProtocol: string | null };

export type NetWsSend = { connectionId: Uint8Array; frame: WsFrame };

export type NotificationInvoke = { id: string };

export type NotificationRemoved = { id: string; reason: DismissReason };

export type NotificationsErrorReply = { error: NotificationError };

export type NotificationsListReply = { page: NotificationsPage };

export type NotificationsListRequest = { pageToken: string | null };

/**
 * Drop the daemon-side partial for `update_id`. After `CancelUpdate`
 * keeps the partial for resume; `OtaAbandon` is the explicit clean-up
 * when the companion no longer wants to retry this artifact.
 */
export type OtaAbandon = { updateId: string };

/**
 * Companion-initiated OTA: opens or resumes a streaming push of a
 * `.swu` artifact identified by its sha256. The daemon responds with
 * `OtaBeginAck { resume_from_offset }` (the byte offset the next
 * `OtaChunk` should start at, 0 for fresh pushes) or
 * `OtaBeginRejected { reason }` (already-running OTA, conflicting
 * in-flight update_id with mismatched size/sha, or budget exhausted).
 *
 * `update_id` is the sha256 of the .swu, hex-encoded. Content-addressed
 * so resume across daemon restarts and retries-after-failure both work
 * without companion-side state to track.
 */
export type OtaBegin = { updateId: string; manifestUrl: string | null; expectedSha256: string; expectedSize: number };

/**
 * Successful response to `OtaBegin`. `resume_from_offset` is the byte
 * offset the next `OtaChunk` should start at: 0 for fresh pushes, or
 * the daemon's recovered partial length for a resume.
 */
export type OtaBeginAck = { resumeFromOffset: number };

/**
 * Domain-error response to `OtaBegin`: the daemon refuses to start
 * or resume this push (already-running OTA, conflicting in-flight
 * update_id with mismatched size/sha, budget exhausted).
 */
export type OtaBeginRejected = { reason: string };

/**
 * Streaming chunk of a .swu push opened by `OtaBegin`. `offset` must
 * equal the daemon's current `received` for the transfer (chunks are
 * strictly in-order; the companion learns the resume offset from
 * `OtaBeginAck`). `last:true` triggers post-stream verify (size +
 * sha256) followed by `Verifying`/`Writing`/`Confirming`/`Reboot`
 * phase progress events.
 */
export type OtaChunk = { updateId: string; offset: number; bytes: Uint8Array; last: boolean };

export type OtaError = { code: OtaErrorCode; msg: string };

/**
 * Terminal error from the OTA orchestrator. After an `OtaError` the
 * orchestrator is back to idle and a fresh `OtaBegin` may be sent.
 */
export type OtaErrorCode =
  | 'unknownUpdate'
  | 'offsetMismatch'
  | 'hashMismatch'
  | 'sizeMismatch'
  | 'cancelled'
  | 'writeFailed'
  | 'confirmFailed'
  | 'internal';

/**
 * Stage of the OTA orchestrator. `Streaming` covers the chunk-by-chunk
 * push of the `.swu` from companion to daemon-disk; `Verifying` runs
 * the post-stream sha256 + size check; `Writing` streams the on-disk
 * `.swu` to libswupdate; `Confirming` flips slot try-counter state;
 * `Reboot` is the terminal stage emitted just before the daemon
 * triggers the reboot.
 */
export type OtaPhase = 'streaming' | 'verifying' | 'writing' | 'confirming' | 'reboot';

/**
 * Per-phase progress tick. `percent` is 0-100 within the current
 * phase, not the overall flow. `eta_ms` is best-effort remaining time
 * for the phase when the orchestrator can compute it.
 */
export type OtaProgress = { phase: OtaPhase; percent: number; etaMs: number | null };

export type PhoneCallAction = { callId: string };

export type PhoneCallEnded = { callId: string; reason: CallEndReason };

/**
 * Typed reply payload for `PhoneStateGet` and the unsolicited
 * announce-time snapshot the companion proactively pushes per the
 * announce-on-connect rule.
 */
export type PhoneStateReply = { state: PhoneState };

/**
 * Play a URI on the gateway. `context` lets the gateway honor playlist
 * / album semantics for skip-next when both sides understand the
 * scheme. The daemon parses the scheme and only forwards if a
 * connected gateway claims it; otherwise returns `PlayerError::SchemeUnclaimed`.
 */
export type PlayUri = { uri: string; context: PlayContext | null };

/**
 * Snapshot of the player queue as the companion sees it. Sent on
 * queue mutations the gateway can detect (user reorder, queue clear,
 * gapless prefetch landing). The daemon overwrites its cached queue
 * from this and re-broadcasts to webapps.
 */
export type QueueSnapshot = { items: Array<QueueItem> };

export type QueueUri = { uri: string; position: QueuePosition };

export type RecommendationsReply = { result: RecommendationsResult };

export type SearchReply = { result: SearchResult };

export type SeekTo = { positionMs: number };

/**
 * `duration_ms = None` turns crossfade off; `Some(0)` is also off but
 * distinguishes intent.
 */
export type SetCrossfade = { durationMs: number | null };

export type SetMute = { muted: boolean };

export type SetRepeat = { mode: RepeatMode };

export type SetShuffle = { on: boolean };

/**
 * Set absolute playback rate. `1.0` is normal speed; gateways with
 * limited speed support clamp to their nearest supported value.
 */
export type SetSpeed = { speed: number };

export type SetVolume = { level: number };

export type SkipToIndex = { index: number };

/**
 * Fire-and-forget TTS request. `id` is webapp-assigned (no request
 * round-trip) and used for cancellation + matching back-to-back
 * `TtsStarted`/`TtsEnded` events. `voice` selects from
 * `AudioCapabilities.voices`; `None` uses the gateway's default.
 */
export type Tts = { id: Uint8Array; text: string; voice: string | null };

export type TtsCancel = { id: Uint8Array };

/**
 * Fired when the TTS request finished. `completed` is true when the
 * full text was spoken; false when preempted, cancelled, or the
 * companion dropped it.
 */
export type TtsEnded = { id: Uint8Array; completed: boolean };

/**
 * Fired when the companion has begun speaking the TTS request with this
 * id. May arrive after `TtsEnded` is dropped (e.g. companion preempted
 * before speech started); webapps should treat both as best-effort.
 */
export type TtsStarted = { id: Uint8Array };

/**
 * Volume / mute snapshot. Fired on any change to either; webapps treat
 * `level` as the canonical value.
 */
export type VolumeChanged = { level: number; muted: boolean };

export type WebappActive = { name: string };

export type WebappError =
  | { type: 'unknownWebapp'; data: { name: string } }
  | { type: 'cannotUninstallBuiltin'; data: { name: string } }
  | { type: 'installFailed'; data: { reason: string } };

export type WebappInstall = {
  name: string;
  /**
   * zip archive whose top-level entries become the bundle contents.
   * Must include an `index.html` at the archive root.
   */
  archive: Uint8Array;
};

export type WebappList = { webapps: Array<WebappInfo> };

export type WebappSwitchTo = { name: string };

export type WebappUninstall = { name: string };
