// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GatewayError } from './gateway';
import type {
  BridgeThingMeta,
  Device,
  ForwardMessage,
  PhoneCallDirection,
  PhoneCallStatus,
  PlaybackOptions,
  PlaybackRestrictions,
  Track,
} from './shared';

export type GatewayStatus = {
  address: string;
  connected: boolean;
  adapterVersion: string;
  libVersion: string;
  libbridgethingVersion: string;
  appName: string;
  appVersion: string;
  osName: string;
};

export type ServerBluetoothEvent =
  | { event: 'status'; data: { connected: boolean } }
  | { event: 'connectedDevice'; data: { name: string; mac: string } }
  | { event: 'interface'; data: { mac: string; name: string; interface: string } }
  | { event: 'paringResult'; data: { success: boolean } }
  | { event: 'pin'; data: { mac: string; name: string; pin: string } }
  | { event: 'pairedDevices'; data: { [key in string]: Device } };

/**
 * bridgething -> client
 * messages from bridgething to the client (usually webpage) on the car thing.
 *
 * these messages will pass through a websocket.
 */
export type ServerEvent = { id: string } & (
  | ({ type: 'bluetooth' } & ServerBluetoothEvent)
  | ({ type: 'storage' } & ServerStorageEvent)
  | ({ type: 'system' } & ServerSystemEvent)
  | ({ type: 'interaction' } & ServerInteractionEvent)
  | ({ type: 'player' } & ServerPlayerEvent)
  | ({ type: 'forward' } & ForwardMessage)
  | ({ type: 'error' } & GatewayError)
  | { type: 'ack' }
) &
  ({ meta: 'request' } | { meta: 'response'; requestId: string } | { meta: 'event' });

export type ServerEventData =
  | ({ type: 'bluetooth' } & ServerBluetoothEvent)
  | ({ type: 'storage' } & ServerStorageEvent)
  | ({ type: 'system' } & ServerSystemEvent)
  | ({ type: 'interaction' } & ServerInteractionEvent)
  | ({ type: 'player' } & ServerPlayerEvent)
  | ({ type: 'forward' } & ForwardMessage)
  | ({ type: 'error' } & GatewayError)
  | { type: 'ack' };

export type ServerEventType = { meta: 'request' } | { meta: 'response'; requestId: string } | { meta: 'event' };

export type ServerInteractionEvent = never;

export type ServerPlayerEvent =
  | { event: 'playerIdle' }
  | {
      event: 'playerState';
      data: {
        contextId: string;
        contextTitle: string;
        isPaused: boolean;
        playbackOptions: PlaybackOptions;
        playbackPosition: number;
        playbackRestrictions: PlaybackRestrictions;
        playbackSpeed: number;
        track: Track;
      };
    }
  | { event: 'queue'; data: { next: Array<Track>; current: Track; previous: Array<Track> } }
  | { event: 'image'; data: { id: string; height: number; width: number; data: string } };

export type ServerStorageEvent = { event: 'response'; data: StorageResponse };

export type ServerSystemEvent =
  | { event: 'version'; data: BridgeThingMeta }
  | { event: 'gatewayStatus'; data: GatewayStatus }
  | { event: 'otaReboot'; data: { delayMs: number } }
  | { event: 'otaPowerOff'; data: { delayMs: number } }
  | { event: 'ambientLightUpdate'; data: { brightness: number } }
  | {
      event: 'phoneCallInfo';
      data: {
        remoteId: string;
        displayName: string;
        status: PhoneCallStatus;
        callDir: PhoneCallDirection;
        callId: string;
      };
    };

export type StorageResponse = { key: string; value: string | null };
