// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Album = { id: string; name: string };

export type Artist = { id: string; name: string };

export type BridgeThingMeta = {
  bridgethingVersion: string;
  libbridgethingVersion: string;
  appName: string;
  appVersion: string;
  osName: string;
  osVersion: string;
  osDescription: string;
  btMac: string;
  serialNumber: string;
  fccId: string;
  icId: string;
  modelName: string;
  imageBuildId: string;
  imageBuildDate: string;
  imageDistro: string;
  imageDistroVersion: string;
  imageMachine: string;
  discord: string;
  credits: string;
};

export type Device = { name: string; type: DeviceType; mac: string; default: boolean };

export type DeviceType = 'android' | 'iOS' | 'windows' | 'macOS' | 'linux' | 'unknown';

export type ForwardMessage =
  | { encoding: 'text'; data: string }
  | { encoding: 'json'; data: unknown }
  | { encoding: 'binary'; data: Uint8Array };

export type ForwardMessage =
  | { encoding: 'text'; data: string }
  | { encoding: 'json'; data: unknown }
  | { encoding: 'binary'; data: Uint8Array };

export type ForwardMessage =
  | { encoding: 'text'; data: string }
  | { encoding: 'json'; data: unknown }
  | { encoding: 'binary'; data: Uint8Array };

export type GatewayMeta = {
  adapterVersion: string;
  libVersion: string;
  libbridgethingVersion: string;
  appName: string;
  appVersion: string;
  osName: string;
};

export type GatewayMeta = {
  adapterVersion: string;
  libVersion: string;
  libbridgethingVersion: string;
  appName: string;
  appVersion: string;
  osName: string;
};

export type Peer = { device: Device; paired: boolean; iap2: PeerIap2Status; companion: PeerCompanionStatus };

export type PeerCompanionStatus = { type: 'none' } | { type: 'pending' } | { type: 'connected'; data: GatewayMeta };

export type PeerIap2Status = 'none' | 'linkUp' | 'authenticated' | 'identified';

export type PlaybackOptions = { repeat: RepeatMode; shuffle: boolean };

export type PlaybackRestrictions = {
  can_repeat_context: boolean;
  can_repeat_track: boolean;
  can_seek: boolean;
  can_skip_next: boolean;
  can_skip_prev: boolean;
  can_toggle_shuffle: boolean;
  can_like: boolean;
  can_change_volume: boolean;
  can_set_output: boolean;
};

/**
 * `repeat` is a typed enum (Off/All/One) shared with
 * the canonical `PlaybackOptions` shape webapps already render and
 * with the outbound `SetRepeat` interaction command. iOS, Android,
 * Spotify, and Apple Music all expose three repeat states; the
 * underlying transports (iAP2 NowPlaying CSM, MediaSession, etc.)
 * translate to/from this enum.
 */
export type RepeatMode = 'off' | 'all' | 'one';

/**
 * `repeat` is a typed enum (Off/All/One) shared with
 * the canonical `PlaybackOptions` shape webapps already render and
 * with the outbound `SetRepeat` interaction command. iOS, Android,
 * Spotify, and Apple Music all expose three repeat states; the
 * underlying transports (iAP2 NowPlaying CSM, MediaSession, etc.)
 * translate to/from this enum.
 */
export type RepeatMode = 'off' | 'all' | 'one';

export type Track = {
  id: string;
  name: string;
  album: Album;
  artist: Artist;
  artists: Array<Artist>;
  duration_ms: number;
  image_id: string;
  saved: boolean;
};

export type TtlRetention = { seconds: number };

export type WebappInfo = { name: string; source: WebappSource; version: string | null; description: string | null };

/**
 * Source of a webapp bundle. Built-in apps live in the read-only image
 * (rootfs) and cannot be uninstalled. Installed apps live on the data
 * partition and shadow built-ins of the same name.
 */
export type WebappSource = 'builtin' | 'installed';
