// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Intent the sender signals for each message. Lets the receiver know
 * whether to send back a typed response, treat it as a one-way command,
 * or pair it against a pending request.
 */
export type MsgMeta =
  | { kind: 'command' }
  | { kind: 'event' }
  | { kind: 'request' }
  | { kind: 'response'; data: ResponseMeta };

/**
 * Intent the sender signals for each message. Lets the receiver know
 * whether to send back a typed response, treat it as a one-way command,
 * or pair it against a pending request.
 */
export type MsgMeta =
  | { kind: 'command' }
  | { kind: 'event' }
  | { kind: 'request' }
  | { kind: 'response'; data: ResponseMeta };

/**
 * Correlation handle the responder echoes back so the requester's
 * pending future can resolve.
 */
export type ResponseMeta = { requestId: Uint8Array };

/**
 * Correlation handle the responder echoes back so the requester's
 * pending future can resolve.
 */
export type ResponseMeta = { requestId: Uint8Array };
